/*
 * This file is generated by jOOQ.
 */
package se.dansbart.jooq.routines;


import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;

import se.dansbart.jooq.Public;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ShowLimit extends AbstractRoutine<Float> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>public.show_limit.RETURN_VALUE</code>.
     */
    public static final Parameter<Float> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", SQLDataType.REAL, false, false);

    /**
     * Create a new routine call instance
     */
    public ShowLimit() {
        super("show_limit", Public.PUBLIC, SQLDataType.REAL);

        setReturnParameter(RETURN_VALUE);
    }
}
