/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface Album {
  id?: string;
  title?: string;
  coverImageUrl?: string;
  releaseDate?: string;
  spotifyId?: string;
  artistId?: string;
}
