/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface Artist {
  id?: string;
  name?: string;
  imageUrl?: string;
  spotifyId?: string;
  isVerified?: boolean;
}
