/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface DanceStyleDto {
  id?: string;
  danceStyle?: string;
  subStyle?: string;
  isPrimary?: boolean;
  confidence?: number;
  tempoCategory?: string;
  bpmMultiplier?: number;
  effectiveBpm?: number;
  confirmationCount?: number;
  isUserConfirmed?: boolean;
}
