services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - /app/node_modules  # Prevent overwriting node_modules
    environment:
      - NODE_ENV=development
