services:
  backend:
    image: ghcr.io/svnoak/dansbart-backend:production
    platform: linux/amd64
    env_file:
      - .env
    depends_on:
      - db
      - redis
    expose:
      - "8000"
    networks:
      - default
    restart: unless-stopped

  db:
    image: pgvector/pgvector:pg15
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB:-dansbart}
    networks:
      - default
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    networks:
      - default
    restart: unless-stopped

  frontend:
    image: ghcr.io/svnoak/dansbart-frontend:production
    depends_on:
      - backend
    networks:
      - default
      - caddy_net
    labels:
      caddy: beta.dansbart.se dansbart.se
      caddy.reverse_proxy: "{{upstreams 80}}"
    restart: unless-stopped

  worker-audio:
    image: ghcr.io/svnoak/dansbart-audio-worker:production
    platform: linux/amd64
    command: celery -A app.core.celery_app worker --loglevel=info --pool=solo -Q audio
    env_file:
      - .env
    environment:
      - WORKER_TYPE=audio
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CUDA_VISIBLE_DEVICES=-1
    depends_on:
      - db
      - redis
    networks:
      - default
    shm_size: '2gb'
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4500M
    restart: unless-stopped


  worker-light:
    image: ghcr.io/svnoak/dansbart-light-worker:production
    platform: linux/amd64
    command: celery -A app.core.celery_app worker --loglevel=info --concurrency=2 --max-tasks-per-child=100 -Q light
    env_file:
      - .env
    environment:
      - WORKER_TYPE=light
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis
    networks:
      - default
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    restart: unless-stopped

networks:
  caddy_net:
    external: true
  default:
    driver: bridge

volumes:
  postgres_data_prod: