/*
 * This file is generated by jOOQ.
 */
package se.dansbart.jooq.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import se.dansbart.jooq.Indexes;
import se.dansbart.jooq.Keys;
import se.dansbart.jooq.Public;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ArtistCrawlLogs extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.artist_crawl_logs</code>
     */
    public static final ArtistCrawlLogs ARTIST_CRAWL_LOGS = new ArtistCrawlLogs();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.artist_crawl_logs.id</code>.
     */
    public final TableField<Record, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.artist_crawl_logs.spotify_artist_id</code>.
     */
    public final TableField<Record, String> SPOTIFY_ARTIST_ID = createField(DSL.name("spotify_artist_id"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.artist_crawl_logs.artist_name</code>.
     */
    public final TableField<Record, String> ARTIST_NAME = createField(DSL.name("artist_name"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.artist_crawl_logs.crawled_at</code>.
     */
    public final TableField<Record, OffsetDateTime> CRAWLED_AT = createField(DSL.name("crawled_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.artist_crawl_logs.tracks_found</code>.
     */
    public final TableField<Record, Integer> TRACKS_FOUND = createField(DSL.name("tracks_found"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.artist_crawl_logs.status</code>.
     */
    public final TableField<Record, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.artist_crawl_logs.detected_genres</code>.
     */
    public final TableField<Record, JSONB> DETECTED_GENRES = createField(DSL.name("detected_genres"), SQLDataType.JSONB, this, "");

    /**
     * The column
     * <code>public.artist_crawl_logs.music_genre_classification</code>.
     */
    public final TableField<Record, String> MUSIC_GENRE_CLASSIFICATION = createField(DSL.name("music_genre_classification"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.artist_crawl_logs.discovery_source</code>.
     */
    public final TableField<Record, String> DISCOVERY_SOURCE = createField(DSL.name("discovery_source"), SQLDataType.VARCHAR, this, "");

    private ArtistCrawlLogs(Name alias, Table<Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ArtistCrawlLogs(Name alias, Table<Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.artist_crawl_logs</code> table reference
     */
    public ArtistCrawlLogs(String alias) {
        this(DSL.name(alias), ARTIST_CRAWL_LOGS);
    }

    /**
     * Create an aliased <code>public.artist_crawl_logs</code> table reference
     */
    public ArtistCrawlLogs(Name alias) {
        this(alias, ARTIST_CRAWL_LOGS);
    }

    /**
     * Create a <code>public.artist_crawl_logs</code> table reference
     */
    public ArtistCrawlLogs() {
        this(DSL.name("artist_crawl_logs"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IX_ARTIST_CRAWL_LOGS_SPOTIFY_ARTIST_ID);
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.ARTIST_CRAWL_LOGS_PKEY;
    }

    @Override
    public List<UniqueKey<Record>> getUniqueKeys() {
        return Arrays.asList(Keys.UNIQUE_SPOTIFY_ARTIST_CRAWL);
    }

    @Override
    public ArtistCrawlLogs as(String alias) {
        return new ArtistCrawlLogs(DSL.name(alias), this);
    }

    @Override
    public ArtistCrawlLogs as(Name alias) {
        return new ArtistCrawlLogs(alias, this);
    }

    @Override
    public ArtistCrawlLogs as(Table<?> alias) {
        return new ArtistCrawlLogs(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ArtistCrawlLogs rename(String name) {
        return new ArtistCrawlLogs(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ArtistCrawlLogs rename(Name name) {
        return new ArtistCrawlLogs(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ArtistCrawlLogs rename(Table<?> name) {
        return new ArtistCrawlLogs(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ArtistCrawlLogs where(Condition condition) {
        return new ArtistCrawlLogs(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ArtistCrawlLogs where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ArtistCrawlLogs where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ArtistCrawlLogs where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ArtistCrawlLogs where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ArtistCrawlLogs where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ArtistCrawlLogs where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ArtistCrawlLogs where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ArtistCrawlLogs whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ArtistCrawlLogs whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
