/*
 * This file is generated by jOOQ.
 */
package se.dansbart.jooq.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import se.dansbart.jooq.Indexes;
import se.dansbart.jooq.Keys;
import se.dansbart.jooq.Public;
import se.dansbart.jooq.tables.Users.UsersPath;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CommunitySuggestions extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.community_suggestions</code>
     */
    public static final CommunitySuggestions COMMUNITY_SUGGESTIONS = new CommunitySuggestions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.community_suggestions.id</code>.
     */
    public final TableField<Record, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.community_suggestions.kind</code>.
     */
    public final TableField<Record, String> KIND = createField(DSL.name("kind"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.community_suggestions.payload</code>.
     */
    public final TableField<Record, JSONB> PAYLOAD = createField(DSL.name("payload"), SQLDataType.JSONB.nullable(false), this, "");

    /**
     * The column <code>public.community_suggestions.note</code>.
     */
    public final TableField<Record, String> NOTE = createField(DSL.name("note"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.community_suggestions.voter_id</code>.
     */
    public final TableField<Record, UUID> VOTER_ID = createField(DSL.name("voter_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.community_suggestions.status</code>.
     */
    public final TableField<Record, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR.nullable(false).defaultValue(DSL.field(DSL.raw("'pending'::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.community_suggestions.reviewed_by</code>.
     */
    public final TableField<Record, UUID> REVIEWED_BY = createField(DSL.name("reviewed_by"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.community_suggestions.reviewed_at</code>.
     */
    public final TableField<Record, OffsetDateTime> REVIEWED_AT = createField(DSL.name("reviewed_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.community_suggestions.review_note</code>.
     */
    public final TableField<Record, String> REVIEW_NOTE = createField(DSL.name("review_note"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.community_suggestions.resolved_ref_id</code>.
     */
    public final TableField<Record, UUID> RESOLVED_REF_ID = createField(DSL.name("resolved_ref_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.community_suggestions.activated_at</code>.
     */
    public final TableField<Record, OffsetDateTime> ACTIVATED_AT = createField(DSL.name("activated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.community_suggestions.created_at</code>.
     */
    public final TableField<Record, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private CommunitySuggestions(Name alias, Table<Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CommunitySuggestions(Name alias, Table<Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.community_suggestions</code> table
     * reference
     */
    public CommunitySuggestions(String alias) {
        this(DSL.name(alias), COMMUNITY_SUGGESTIONS);
    }

    /**
     * Create an aliased <code>public.community_suggestions</code> table
     * reference
     */
    public CommunitySuggestions(Name alias) {
        this(alias, COMMUNITY_SUGGESTIONS);
    }

    /**
     * Create a <code>public.community_suggestions</code> table reference
     */
    public CommunitySuggestions() {
        this(DSL.name("community_suggestions"), null);
    }

    public <O extends Record> CommunitySuggestions(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
        super(path, childPath, parentPath, COMMUNITY_SUGGESTIONS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class CommunitySuggestionsPath extends CommunitySuggestions implements Path<Record> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> CommunitySuggestionsPath(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
            super(path, childPath, parentPath);
        }
        private CommunitySuggestionsPath(Name alias, Table<Record> aliased) {
            super(alias, aliased);
        }

        @Override
        public CommunitySuggestionsPath as(String alias) {
            return new CommunitySuggestionsPath(DSL.name(alias), this);
        }

        @Override
        public CommunitySuggestionsPath as(Name alias) {
            return new CommunitySuggestionsPath(alias, this);
        }

        @Override
        public CommunitySuggestionsPath as(Table<?> alias) {
            return new CommunitySuggestionsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_COMMUNITY_SUGGESTIONS_KIND_STATUS, Indexes.IDX_COMMUNITY_SUGGESTIONS_VOTER);
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.COMMUNITY_SUGGESTIONS_PKEY;
    }

    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.asList(Keys.COMMUNITY_SUGGESTIONS__COMMUNITY_SUGGESTIONS_REVIEWED_BY_FKEY);
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.COMMUNITY_SUGGESTIONS__COMMUNITY_SUGGESTIONS_REVIEWED_BY_FKEY, null);

        return _users;
    }

    @Override
    public List<Check<Record>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("community_suggestions_kind_check"), "(((kind)::text = ANY ((ARRAY['content'::character varying, 'dance_style'::character varying])::text[])))", true),
            Internal.createCheck(this, DSL.name("community_suggestions_status_check"), "(((status)::text = ANY ((ARRAY['pending'::character varying, 'accepted'::character varying, 'activated'::character varying, 'rejected'::character varying])::text[])))", true)
        );
    }

    @Override
    public CommunitySuggestions as(String alias) {
        return new CommunitySuggestions(DSL.name(alias), this);
    }

    @Override
    public CommunitySuggestions as(Name alias) {
        return new CommunitySuggestions(alias, this);
    }

    @Override
    public CommunitySuggestions as(Table<?> alias) {
        return new CommunitySuggestions(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CommunitySuggestions rename(String name) {
        return new CommunitySuggestions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CommunitySuggestions rename(Name name) {
        return new CommunitySuggestions(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CommunitySuggestions rename(Table<?> name) {
        return new CommunitySuggestions(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CommunitySuggestions where(Condition condition) {
        return new CommunitySuggestions(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CommunitySuggestions where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CommunitySuggestions where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CommunitySuggestions where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CommunitySuggestions where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CommunitySuggestions where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CommunitySuggestions where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CommunitySuggestions where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CommunitySuggestions whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CommunitySuggestions whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
