/*
 * This file is generated by jOOQ.
 */
package se.dansbart.jooq.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import se.dansbart.jooq.Indexes;
import se.dansbart.jooq.Keys;
import se.dansbart.jooq.Public;
import se.dansbart.jooq.tables.Dances.DancesPath;
import se.dansbart.jooq.tables.Tracks.TracksPath;
import se.dansbart.jooq.tables.Users.UsersPath;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DanceTracks extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.dance_tracks</code>
     */
    public static final DanceTracks DANCE_TRACKS = new DanceTracks();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.dance_tracks.id</code>.
     */
    public final TableField<Record, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.dance_tracks.dance_id</code>.
     */
    public final TableField<Record, UUID> DANCE_ID = createField(DSL.name("dance_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.dance_tracks.track_id</code>.
     */
    public final TableField<Record, UUID> TRACK_ID = createField(DSL.name("track_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.dance_tracks.added_by</code>.
     */
    public final TableField<Record, UUID> ADDED_BY = createField(DSL.name("added_by"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.dance_tracks.added_at</code>.
     */
    public final TableField<Record, OffsetDateTime> ADDED_AT = createField(DSL.name("added_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.dance_tracks.is_confirmed</code>.
     */
    public final TableField<Record, Boolean> IS_CONFIRMED = createField(DSL.name("is_confirmed"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.dance_tracks.confirmed_by</code>.
     */
    public final TableField<Record, UUID> CONFIRMED_BY = createField(DSL.name("confirmed_by"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.dance_tracks.confirmed_at</code>.
     */
    public final TableField<Record, OffsetDateTime> CONFIRMED_AT = createField(DSL.name("confirmed_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    private DanceTracks(Name alias, Table<Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private DanceTracks(Name alias, Table<Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.dance_tracks</code> table reference
     */
    public DanceTracks(String alias) {
        this(DSL.name(alias), DANCE_TRACKS);
    }

    /**
     * Create an aliased <code>public.dance_tracks</code> table reference
     */
    public DanceTracks(Name alias) {
        this(alias, DANCE_TRACKS);
    }

    /**
     * Create a <code>public.dance_tracks</code> table reference
     */
    public DanceTracks() {
        this(DSL.name("dance_tracks"), null);
    }

    public <O extends Record> DanceTracks(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
        super(path, childPath, parentPath, DANCE_TRACKS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class DanceTracksPath extends DanceTracks implements Path<Record> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> DanceTracksPath(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
            super(path, childPath, parentPath);
        }
        private DanceTracksPath(Name alias, Table<Record> aliased) {
            super(alias, aliased);
        }

        @Override
        public DanceTracksPath as(String alias) {
            return new DanceTracksPath(DSL.name(alias), this);
        }

        @Override
        public DanceTracksPath as(Name alias) {
            return new DanceTracksPath(alias, this);
        }

        @Override
        public DanceTracksPath as(Table<?> alias) {
            return new DanceTracksPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_DANCE_TRACKS_CONFIRMED, Indexes.IDX_DANCE_TRACKS_DANCE_ID, Indexes.IDX_DANCE_TRACKS_TRACK_ID);
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.DANCE_TRACKS_PKEY;
    }

    @Override
    public List<UniqueKey<Record>> getUniqueKeys() {
        return Arrays.asList(Keys.DANCE_TRACKS_DANCE_ID_TRACK_ID_KEY);
    }

    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.asList(Keys.DANCE_TRACKS__DANCE_TRACKS_DANCE_ID_FKEY, Keys.DANCE_TRACKS__DANCE_TRACKS_TRACK_ID_FKEY, Keys.DANCE_TRACKS__DANCE_TRACKS_ADDED_BY_FKEY, Keys.DANCE_TRACKS__DANCE_TRACKS_CONFIRMED_BY_FKEY);
    }

    private transient DancesPath _dances;

    /**
     * Get the implicit join path to the <code>public.dances</code> table.
     */
    public DancesPath dances() {
        if (_dances == null)
            _dances = new DancesPath(this, Keys.DANCE_TRACKS__DANCE_TRACKS_DANCE_ID_FKEY, null);

        return _dances;
    }

    private transient TracksPath _tracks;

    /**
     * Get the implicit join path to the <code>public.tracks</code> table.
     */
    public TracksPath tracks() {
        if (_tracks == null)
            _tracks = new TracksPath(this, Keys.DANCE_TRACKS__DANCE_TRACKS_TRACK_ID_FKEY, null);

        return _tracks;
    }

    private transient UsersPath _danceTracksAddedByFkey;

    /**
     * Get the implicit join path to the <code>public.users</code> table, via
     * the <code>dance_tracks_added_by_fkey</code> key.
     */
    public UsersPath danceTracksAddedByFkey() {
        if (_danceTracksAddedByFkey == null)
            _danceTracksAddedByFkey = new UsersPath(this, Keys.DANCE_TRACKS__DANCE_TRACKS_ADDED_BY_FKEY, null);

        return _danceTracksAddedByFkey;
    }

    private transient UsersPath _danceTracksConfirmedByFkey;

    /**
     * Get the implicit join path to the <code>public.users</code> table, via
     * the <code>dance_tracks_confirmed_by_fkey</code> key.
     */
    public UsersPath danceTracksConfirmedByFkey() {
        if (_danceTracksConfirmedByFkey == null)
            _danceTracksConfirmedByFkey = new UsersPath(this, Keys.DANCE_TRACKS__DANCE_TRACKS_CONFIRMED_BY_FKEY, null);

        return _danceTracksConfirmedByFkey;
    }

    @Override
    public DanceTracks as(String alias) {
        return new DanceTracks(DSL.name(alias), this);
    }

    @Override
    public DanceTracks as(Name alias) {
        return new DanceTracks(alias, this);
    }

    @Override
    public DanceTracks as(Table<?> alias) {
        return new DanceTracks(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public DanceTracks rename(String name) {
        return new DanceTracks(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DanceTracks rename(Name name) {
        return new DanceTracks(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public DanceTracks rename(Table<?> name) {
        return new DanceTracks(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DanceTracks where(Condition condition) {
        return new DanceTracks(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DanceTracks where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DanceTracks where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DanceTracks where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DanceTracks where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DanceTracks where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DanceTracks where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DanceTracks where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DanceTracks whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DanceTracks whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
