/*
 * This file is generated by jOOQ.
 */
package se.dansbart.jooq.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import se.dansbart.jooq.Indexes;
import se.dansbart.jooq.Keys;
import se.dansbart.jooq.Public;
import se.dansbart.jooq.tables.DanceLists.DanceListsPath;
import se.dansbart.jooq.tables.Users.UsersPath;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DanceListCollaborators extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.dance_list_collaborators</code>
     */
    public static final DanceListCollaborators DANCE_LIST_COLLABORATORS = new DanceListCollaborators();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.dance_list_collaborators.id</code>.
     */
    public final TableField<Record, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.dance_list_collaborators.dance_list_id</code>.
     */
    public final TableField<Record, UUID> DANCE_LIST_ID = createField(DSL.name("dance_list_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.dance_list_collaborators.user_id</code>.
     */
    public final TableField<Record, UUID> USER_ID = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.dance_list_collaborators.permission</code>.
     */
    public final TableField<Record, String> PERMISSION = createField(DSL.name("permission"), SQLDataType.VARCHAR(10).nullable(false), this, "");

    /**
     * The column <code>public.dance_list_collaborators.invited_by</code>.
     */
    public final TableField<Record, UUID> INVITED_BY = createField(DSL.name("invited_by"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.dance_list_collaborators.invited_at</code>.
     */
    public final TableField<Record, OffsetDateTime> INVITED_AT = createField(DSL.name("invited_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.dance_list_collaborators.status</code>.
     */
    public final TableField<Record, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(20).nullable(false).defaultValue(DSL.field(DSL.raw("'pending'::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.dance_list_collaborators.accepted_at</code>.
     */
    public final TableField<Record, OffsetDateTime> ACCEPTED_AT = createField(DSL.name("accepted_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    private DanceListCollaborators(Name alias, Table<Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private DanceListCollaborators(Name alias, Table<Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.dance_list_collaborators</code> table
     * reference
     */
    public DanceListCollaborators(String alias) {
        this(DSL.name(alias), DANCE_LIST_COLLABORATORS);
    }

    /**
     * Create an aliased <code>public.dance_list_collaborators</code> table
     * reference
     */
    public DanceListCollaborators(Name alias) {
        this(alias, DANCE_LIST_COLLABORATORS);
    }

    /**
     * Create a <code>public.dance_list_collaborators</code> table reference
     */
    public DanceListCollaborators() {
        this(DSL.name("dance_list_collaborators"), null);
    }

    public <O extends Record> DanceListCollaborators(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
        super(path, childPath, parentPath, DANCE_LIST_COLLABORATORS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class DanceListCollaboratorsPath extends DanceListCollaborators implements Path<Record> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> DanceListCollaboratorsPath(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
            super(path, childPath, parentPath);
        }
        private DanceListCollaboratorsPath(Name alias, Table<Record> aliased) {
            super(alias, aliased);
        }

        @Override
        public DanceListCollaboratorsPath as(String alias) {
            return new DanceListCollaboratorsPath(DSL.name(alias), this);
        }

        @Override
        public DanceListCollaboratorsPath as(Name alias) {
            return new DanceListCollaboratorsPath(alias, this);
        }

        @Override
        public DanceListCollaboratorsPath as(Table<?> alias) {
            return new DanceListCollaboratorsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_DANCE_LIST_COLLABORATORS_DANCE_LIST, Indexes.IDX_DANCE_LIST_COLLABORATORS_STATUS, Indexes.IDX_DANCE_LIST_COLLABORATORS_USER);
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.DANCE_LIST_COLLABORATORS_PKEY;
    }

    @Override
    public List<UniqueKey<Record>> getUniqueKeys() {
        return Arrays.asList(Keys.UNIQUE_DANCE_LIST_USER_COLLABORATION);
    }

    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.asList(Keys.DANCE_LIST_COLLABORATORS__DANCE_LIST_COLLABORATORS_DANCE_LIST_ID_FKEY, Keys.DANCE_LIST_COLLABORATORS__DANCE_LIST_COLLABORATORS_USER_ID_FKEY, Keys.DANCE_LIST_COLLABORATORS__DANCE_LIST_COLLABORATORS_INVITED_BY_FKEY);
    }

    private transient DanceListsPath _danceLists;

    /**
     * Get the implicit join path to the <code>public.dance_lists</code> table.
     */
    public DanceListsPath danceLists() {
        if (_danceLists == null)
            _danceLists = new DanceListsPath(this, Keys.DANCE_LIST_COLLABORATORS__DANCE_LIST_COLLABORATORS_DANCE_LIST_ID_FKEY, null);

        return _danceLists;
    }

    private transient UsersPath _danceListCollaboratorsUserIdFkey;

    /**
     * Get the implicit join path to the <code>public.users</code> table, via
     * the <code>dance_list_collaborators_user_id_fkey</code> key.
     */
    public UsersPath danceListCollaboratorsUserIdFkey() {
        if (_danceListCollaboratorsUserIdFkey == null)
            _danceListCollaboratorsUserIdFkey = new UsersPath(this, Keys.DANCE_LIST_COLLABORATORS__DANCE_LIST_COLLABORATORS_USER_ID_FKEY, null);

        return _danceListCollaboratorsUserIdFkey;
    }

    private transient UsersPath _danceListCollaboratorsInvitedByFkey;

    /**
     * Get the implicit join path to the <code>public.users</code> table, via
     * the <code>dance_list_collaborators_invited_by_fkey</code> key.
     */
    public UsersPath danceListCollaboratorsInvitedByFkey() {
        if (_danceListCollaboratorsInvitedByFkey == null)
            _danceListCollaboratorsInvitedByFkey = new UsersPath(this, Keys.DANCE_LIST_COLLABORATORS__DANCE_LIST_COLLABORATORS_INVITED_BY_FKEY, null);

        return _danceListCollaboratorsInvitedByFkey;
    }

    @Override
    public DanceListCollaborators as(String alias) {
        return new DanceListCollaborators(DSL.name(alias), this);
    }

    @Override
    public DanceListCollaborators as(Name alias) {
        return new DanceListCollaborators(alias, this);
    }

    @Override
    public DanceListCollaborators as(Table<?> alias) {
        return new DanceListCollaborators(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public DanceListCollaborators rename(String name) {
        return new DanceListCollaborators(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DanceListCollaborators rename(Name name) {
        return new DanceListCollaborators(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public DanceListCollaborators rename(Table<?> name) {
        return new DanceListCollaborators(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DanceListCollaborators where(Condition condition) {
        return new DanceListCollaborators(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DanceListCollaborators where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DanceListCollaborators where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DanceListCollaborators where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DanceListCollaborators where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DanceListCollaborators where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DanceListCollaborators where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DanceListCollaborators where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DanceListCollaborators whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DanceListCollaborators whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
