/*
 * This file is generated by jOOQ.
 */
package se.dansbart.jooq.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import se.dansbart.jooq.Indexes;
import se.dansbart.jooq.Keys;
import se.dansbart.jooq.Public;
import se.dansbart.jooq.tables.TrackFolkwikiMatches.TrackFolkwikiMatchesPath;
import se.dansbart.jooq.tables.Tracks.TracksPath;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FolkwikiTunes extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.folkwiki_tunes</code>
     */
    public static final FolkwikiTunes FOLKWIKI_TUNES = new FolkwikiTunes();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.folkwiki_tunes.id</code>.
     */
    public final TableField<Record, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.folkwiki_tunes.folkwiki_id</code>.
     */
    public final TableField<Record, String> FOLKWIKI_ID = createField(DSL.name("folkwiki_id"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.folkwiki_tunes.title</code>.
     */
    public final TableField<Record, String> TITLE = createField(DSL.name("title"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.folkwiki_tunes.normalized_title</code>.
     */
    public final TableField<Record, String> NORMALIZED_TITLE = createField(DSL.name("normalized_title"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.folkwiki_tunes.style</code>.
     */
    public final TableField<Record, String> STYLE = createField(DSL.name("style"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.folkwiki_tunes.meter</code>.
     */
    public final TableField<Record, String> METER = createField(DSL.name("meter"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.folkwiki_tunes.beats_per_bar</code>.
     */
    public final TableField<Record, Integer> BEATS_PER_BAR = createField(DSL.name("beats_per_bar"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.folkwiki_tunes.folkwiki_url</code>.
     */
    public final TableField<Record, String> FOLKWIKI_URL = createField(DSL.name("folkwiki_url"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.folkwiki_tunes.created_at</code>.
     */
    public final TableField<Record, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.folkwiki_tunes.updated_at</code>.
     */
    public final TableField<Record, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private FolkwikiTunes(Name alias, Table<Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private FolkwikiTunes(Name alias, Table<Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.folkwiki_tunes</code> table reference
     */
    public FolkwikiTunes(String alias) {
        this(DSL.name(alias), FOLKWIKI_TUNES);
    }

    /**
     * Create an aliased <code>public.folkwiki_tunes</code> table reference
     */
    public FolkwikiTunes(Name alias) {
        this(alias, FOLKWIKI_TUNES);
    }

    /**
     * Create a <code>public.folkwiki_tunes</code> table reference
     */
    public FolkwikiTunes() {
        this(DSL.name("folkwiki_tunes"), null);
    }

    public <O extends Record> FolkwikiTunes(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
        super(path, childPath, parentPath, FOLKWIKI_TUNES);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class FolkwikiTunesPath extends FolkwikiTunes implements Path<Record> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> FolkwikiTunesPath(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
            super(path, childPath, parentPath);
        }
        private FolkwikiTunesPath(Name alias, Table<Record> aliased) {
            super(alias, aliased);
        }

        @Override
        public FolkwikiTunesPath as(String alias) {
            return new FolkwikiTunesPath(DSL.name(alias), this);
        }

        @Override
        public FolkwikiTunesPath as(Name alias) {
            return new FolkwikiTunesPath(alias, this);
        }

        @Override
        public FolkwikiTunesPath as(Table<?> alias) {
            return new FolkwikiTunesPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_FOLKWIKI_TUNES_NORMALIZED_TITLE, Indexes.IDX_FOLKWIKI_TUNES_STYLE);
    }

    @Override
    public Identity<Record, Integer> getIdentity() {
        return (Identity<Record, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.FOLKWIKI_TUNES_PKEY;
    }

    @Override
    public List<UniqueKey<Record>> getUniqueKeys() {
        return Arrays.asList(Keys.FOLKWIKI_TUNES_FOLKWIKI_ID_KEY);
    }

    private transient TrackFolkwikiMatchesPath _trackFolkwikiMatches;

    /**
     * Get the implicit to-many join path to the
     * <code>public.track_folkwiki_matches</code> table
     */
    public TrackFolkwikiMatchesPath trackFolkwikiMatches() {
        if (_trackFolkwikiMatches == null)
            _trackFolkwikiMatches = new TrackFolkwikiMatchesPath(this, null, Keys.TRACK_FOLKWIKI_MATCHES__TRACK_FOLKWIKI_MATCHES_FOLKWIKI_TUNE_ID_FKEY.getInverseKey());

        return _trackFolkwikiMatches;
    }

    /**
     * Get the implicit many-to-many join path to the <code>public.tracks</code>
     * table
     */
    public TracksPath tracks() {
        return trackFolkwikiMatches().tracks();
    }

    @Override
    public FolkwikiTunes as(String alias) {
        return new FolkwikiTunes(DSL.name(alias), this);
    }

    @Override
    public FolkwikiTunes as(Name alias) {
        return new FolkwikiTunes(alias, this);
    }

    @Override
    public FolkwikiTunes as(Table<?> alias) {
        return new FolkwikiTunes(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public FolkwikiTunes rename(String name) {
        return new FolkwikiTunes(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FolkwikiTunes rename(Name name) {
        return new FolkwikiTunes(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public FolkwikiTunes rename(Table<?> name) {
        return new FolkwikiTunes(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FolkwikiTunes where(Condition condition) {
        return new FolkwikiTunes(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FolkwikiTunes where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FolkwikiTunes where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FolkwikiTunes where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FolkwikiTunes where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FolkwikiTunes where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FolkwikiTunes where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FolkwikiTunes where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FolkwikiTunes whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FolkwikiTunes whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
