/*
 * This file is generated by jOOQ.
 */
package se.dansbart.jooq.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import se.dansbart.jooq.Indexes;
import se.dansbart.jooq.Keys;
import se.dansbart.jooq.Public;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PendingArtistApprovals extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.pending_artist_approvals</code>
     */
    public static final PendingArtistApprovals PENDING_ARTIST_APPROVALS = new PendingArtistApprovals();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.pending_artist_approvals.id</code>.
     */
    public final TableField<Record, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.pending_artist_approvals.spotify_id</code>.
     */
    public final TableField<Record, String> SPOTIFY_ID = createField(DSL.name("spotify_id"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.pending_artist_approvals.name</code>.
     */
    public final TableField<Record, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.pending_artist_approvals.image_url</code>.
     */
    public final TableField<Record, String> IMAGE_URL = createField(DSL.name("image_url"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.pending_artist_approvals.discovered_at</code>.
     */
    public final TableField<Record, OffsetDateTime> DISCOVERED_AT = createField(DSL.name("discovered_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.pending_artist_approvals.discovery_source</code>.
     */
    public final TableField<Record, String> DISCOVERY_SOURCE = createField(DSL.name("discovery_source"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.pending_artist_approvals.detected_genres</code>.
     */
    public final TableField<Record, JSONB> DETECTED_GENRES = createField(DSL.name("detected_genres"), SQLDataType.JSONB, this, "");

    /**
     * The column
     * <code>public.pending_artist_approvals.music_genre_classification</code>.
     */
    public final TableField<Record, String> MUSIC_GENRE_CLASSIFICATION = createField(DSL.name("music_genre_classification"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.pending_artist_approvals.genre_confidence</code>.
     */
    public final TableField<Record, Double> GENRE_CONFIDENCE = createField(DSL.name("genre_confidence"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.pending_artist_approvals.status</code>.
     */
    public final TableField<Record, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.pending_artist_approvals.reviewed_at</code>.
     */
    public final TableField<Record, OffsetDateTime> REVIEWED_AT = createField(DSL.name("reviewed_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.pending_artist_approvals.additional_data</code>.
     */
    public final TableField<Record, JSONB> ADDITIONAL_DATA = createField(DSL.name("additional_data"), SQLDataType.JSONB, this, "");

    private PendingArtistApprovals(Name alias, Table<Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PendingArtistApprovals(Name alias, Table<Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.pending_artist_approvals</code> table
     * reference
     */
    public PendingArtistApprovals(String alias) {
        this(DSL.name(alias), PENDING_ARTIST_APPROVALS);
    }

    /**
     * Create an aliased <code>public.pending_artist_approvals</code> table
     * reference
     */
    public PendingArtistApprovals(Name alias) {
        this(alias, PENDING_ARTIST_APPROVALS);
    }

    /**
     * Create a <code>public.pending_artist_approvals</code> table reference
     */
    public PendingArtistApprovals() {
        this(DSL.name("pending_artist_approvals"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IX_PENDING_ARTIST_APPROVALS_SPOTIFY_ID, Indexes.IX_PENDING_ARTIST_APPROVALS_STATUS);
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.PENDING_ARTIST_APPROVALS_PKEY;
    }

    @Override
    public List<UniqueKey<Record>> getUniqueKeys() {
        return Arrays.asList(Keys.UNIQUE_PENDING_ARTIST);
    }

    @Override
    public PendingArtistApprovals as(String alias) {
        return new PendingArtistApprovals(DSL.name(alias), this);
    }

    @Override
    public PendingArtistApprovals as(Name alias) {
        return new PendingArtistApprovals(alias, this);
    }

    @Override
    public PendingArtistApprovals as(Table<?> alias) {
        return new PendingArtistApprovals(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PendingArtistApprovals rename(String name) {
        return new PendingArtistApprovals(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PendingArtistApprovals rename(Name name) {
        return new PendingArtistApprovals(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PendingArtistApprovals rename(Table<?> name) {
        return new PendingArtistApprovals(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PendingArtistApprovals where(Condition condition) {
        return new PendingArtistApprovals(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PendingArtistApprovals where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PendingArtistApprovals where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PendingArtistApprovals where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PendingArtistApprovals where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PendingArtistApprovals where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PendingArtistApprovals where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PendingArtistApprovals where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PendingArtistApprovals whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PendingArtistApprovals whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
