/*
 * This file is generated by jOOQ.
 */
package se.dansbart.jooq.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import se.dansbart.jooq.Indexes;
import se.dansbart.jooq.Keys;
import se.dansbart.jooq.Public;
import se.dansbart.jooq.tables.Playlists.PlaylistsPath;
import se.dansbart.jooq.tables.Users.UsersPath;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PlaylistCollaborators extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.playlist_collaborators</code>
     */
    public static final PlaylistCollaborators PLAYLIST_COLLABORATORS = new PlaylistCollaborators();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.playlist_collaborators.id</code>.
     */
    public final TableField<Record, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("uuid_generate_v4()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.playlist_collaborators.playlist_id</code>.
     */
    public final TableField<Record, UUID> PLAYLIST_ID = createField(DSL.name("playlist_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.playlist_collaborators.permission</code>.
     */
    public final TableField<Record, String> PERMISSION = createField(DSL.name("permission"), SQLDataType.VARCHAR(10).nullable(false), this, "");

    /**
     * The column <code>public.playlist_collaborators.invited_at</code>.
     */
    public final TableField<Record, OffsetDateTime> INVITED_AT = createField(DSL.name("invited_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.playlist_collaborators.status</code>.
     */
    public final TableField<Record, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(20).nullable(false).defaultValue(DSL.field(DSL.raw("'pending'::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.playlist_collaborators.accepted_at</code>.
     */
    public final TableField<Record, OffsetDateTime> ACCEPTED_AT = createField(DSL.name("accepted_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.playlist_collaborators.user_id</code>.
     */
    public final TableField<Record, UUID> USER_ID = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.playlist_collaborators.invited_by</code>.
     */
    public final TableField<Record, UUID> INVITED_BY = createField(DSL.name("invited_by"), SQLDataType.UUID, this, "");

    private PlaylistCollaborators(Name alias, Table<Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PlaylistCollaborators(Name alias, Table<Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.playlist_collaborators</code> table
     * reference
     */
    public PlaylistCollaborators(String alias) {
        this(DSL.name(alias), PLAYLIST_COLLABORATORS);
    }

    /**
     * Create an aliased <code>public.playlist_collaborators</code> table
     * reference
     */
    public PlaylistCollaborators(Name alias) {
        this(alias, PLAYLIST_COLLABORATORS);
    }

    /**
     * Create a <code>public.playlist_collaborators</code> table reference
     */
    public PlaylistCollaborators() {
        this(DSL.name("playlist_collaborators"), null);
    }

    public <O extends Record> PlaylistCollaborators(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
        super(path, childPath, parentPath, PLAYLIST_COLLABORATORS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class PlaylistCollaboratorsPath extends PlaylistCollaborators implements Path<Record> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> PlaylistCollaboratorsPath(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
            super(path, childPath, parentPath);
        }
        private PlaylistCollaboratorsPath(Name alias, Table<Record> aliased) {
            super(alias, aliased);
        }

        @Override
        public PlaylistCollaboratorsPath as(String alias) {
            return new PlaylistCollaboratorsPath(DSL.name(alias), this);
        }

        @Override
        public PlaylistCollaboratorsPath as(Name alias) {
            return new PlaylistCollaboratorsPath(alias, this);
        }

        @Override
        public PlaylistCollaboratorsPath as(Table<?> alias) {
            return new PlaylistCollaboratorsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_PLAYLIST_COLLABORATORS_PLAYLIST, Indexes.IDX_PLAYLIST_COLLABORATORS_STATUS, Indexes.IDX_PLAYLIST_COLLABORATORS_USER);
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.PLAYLIST_COLLABORATORS_PKEY;
    }

    @Override
    public List<UniqueKey<Record>> getUniqueKeys() {
        return Arrays.asList(Keys.UNIQUE_PLAYLIST_USER_COLLABORATION);
    }

    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.asList(Keys.PLAYLIST_COLLABORATORS__PLAYLIST_COLLABORATORS_PLAYLIST_ID_FKEY, Keys.PLAYLIST_COLLABORATORS__PLAYLIST_COLLABORATORS_USER_ID_FKEY, Keys.PLAYLIST_COLLABORATORS__PLAYLIST_COLLABORATORS_INVITED_BY_FKEY);
    }

    private transient PlaylistsPath _playlists;

    /**
     * Get the implicit join path to the <code>public.playlists</code> table.
     */
    public PlaylistsPath playlists() {
        if (_playlists == null)
            _playlists = new PlaylistsPath(this, Keys.PLAYLIST_COLLABORATORS__PLAYLIST_COLLABORATORS_PLAYLIST_ID_FKEY, null);

        return _playlists;
    }

    private transient UsersPath _playlistCollaboratorsUserIdFkey;

    /**
     * Get the implicit join path to the <code>public.users</code> table, via
     * the <code>playlist_collaborators_user_id_fkey</code> key.
     */
    public UsersPath playlistCollaboratorsUserIdFkey() {
        if (_playlistCollaboratorsUserIdFkey == null)
            _playlistCollaboratorsUserIdFkey = new UsersPath(this, Keys.PLAYLIST_COLLABORATORS__PLAYLIST_COLLABORATORS_USER_ID_FKEY, null);

        return _playlistCollaboratorsUserIdFkey;
    }

    private transient UsersPath _playlistCollaboratorsInvitedByFkey;

    /**
     * Get the implicit join path to the <code>public.users</code> table, via
     * the <code>playlist_collaborators_invited_by_fkey</code> key.
     */
    public UsersPath playlistCollaboratorsInvitedByFkey() {
        if (_playlistCollaboratorsInvitedByFkey == null)
            _playlistCollaboratorsInvitedByFkey = new UsersPath(this, Keys.PLAYLIST_COLLABORATORS__PLAYLIST_COLLABORATORS_INVITED_BY_FKEY, null);

        return _playlistCollaboratorsInvitedByFkey;
    }

    @Override
    public PlaylistCollaborators as(String alias) {
        return new PlaylistCollaborators(DSL.name(alias), this);
    }

    @Override
    public PlaylistCollaborators as(Name alias) {
        return new PlaylistCollaborators(alias, this);
    }

    @Override
    public PlaylistCollaborators as(Table<?> alias) {
        return new PlaylistCollaborators(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PlaylistCollaborators rename(String name) {
        return new PlaylistCollaborators(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PlaylistCollaborators rename(Name name) {
        return new PlaylistCollaborators(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PlaylistCollaborators rename(Table<?> name) {
        return new PlaylistCollaborators(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlaylistCollaborators where(Condition condition) {
        return new PlaylistCollaborators(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlaylistCollaborators where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlaylistCollaborators where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlaylistCollaborators where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PlaylistCollaborators where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PlaylistCollaborators where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PlaylistCollaborators where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PlaylistCollaborators where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlaylistCollaborators whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlaylistCollaborators whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
