/*
 * This file is generated by jOOQ.
 */
package se.dansbart.jooq.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import se.dansbart.jooq.Keys;
import se.dansbart.jooq.Public;
import se.dansbart.jooq.tables.UserTrackSources.UserTrackSourcesPath;
import se.dansbart.jooq.tables.Users.UsersPath;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProviderConnections extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.provider_connections</code>
     */
    public static final ProviderConnections PROVIDER_CONNECTIONS = new ProviderConnections();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.provider_connections.id</code>.
     */
    public final TableField<Record, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.provider_connections.user_id</code>.
     */
    public final TableField<Record, UUID> USER_ID = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.provider_connections.provider</code>.
     */
    public final TableField<Record, String> PROVIDER = createField(DSL.name("provider"), SQLDataType.VARCHAR(16).nullable(false), this, "");

    /**
     * The column <code>public.provider_connections.status</code>.
     */
    public final TableField<Record, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(16).nullable(false), this, "");

    /**
     * The column
     * <code>public.provider_connections.encrypted_refresh_token</code>.
     */
    public final TableField<Record, byte[]> ENCRYPTED_REFRESH_TOKEN = createField(DSL.name("encrypted_refresh_token"), SQLDataType.BLOB.nullable(false), this, "");

    /**
     * The column
     * <code>public.provider_connections.refresh_token_expires_at</code>.
     */
    public final TableField<Record, OffsetDateTime> REFRESH_TOKEN_EXPIRES_AT = createField(DSL.name("refresh_token_expires_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.provider_connections.last_refreshed_at</code>.
     */
    public final TableField<Record, OffsetDateTime> LAST_REFRESHED_AT = createField(DSL.name("last_refreshed_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.provider_connections.created_at</code>.
     */
    public final TableField<Record, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.provider_connections.updated_at</code>.
     */
    public final TableField<Record, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private ProviderConnections(Name alias, Table<Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ProviderConnections(Name alias, Table<Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.provider_connections</code> table
     * reference
     */
    public ProviderConnections(String alias) {
        this(DSL.name(alias), PROVIDER_CONNECTIONS);
    }

    /**
     * Create an aliased <code>public.provider_connections</code> table
     * reference
     */
    public ProviderConnections(Name alias) {
        this(alias, PROVIDER_CONNECTIONS);
    }

    /**
     * Create a <code>public.provider_connections</code> table reference
     */
    public ProviderConnections() {
        this(DSL.name("provider_connections"), null);
    }

    public <O extends Record> ProviderConnections(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
        super(path, childPath, parentPath, PROVIDER_CONNECTIONS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ProviderConnectionsPath extends ProviderConnections implements Path<Record> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ProviderConnectionsPath(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
            super(path, childPath, parentPath);
        }
        private ProviderConnectionsPath(Name alias, Table<Record> aliased) {
            super(alias, aliased);
        }

        @Override
        public ProviderConnectionsPath as(String alias) {
            return new ProviderConnectionsPath(DSL.name(alias), this);
        }

        @Override
        public ProviderConnectionsPath as(Name alias) {
            return new ProviderConnectionsPath(alias, this);
        }

        @Override
        public ProviderConnectionsPath as(Table<?> alias) {
            return new ProviderConnectionsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.PROVIDER_CONNECTIONS_PKEY;
    }

    @Override
    public List<UniqueKey<Record>> getUniqueKeys() {
        return Arrays.asList(Keys.PROVIDER_CONNECTIONS_USER_ID_PROVIDER_KEY);
    }

    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.asList(Keys.PROVIDER_CONNECTIONS__PROVIDER_CONNECTIONS_USER_ID_FKEY);
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.PROVIDER_CONNECTIONS__PROVIDER_CONNECTIONS_USER_ID_FKEY, null);

        return _users;
    }

    private transient UserTrackSourcesPath _userTrackSources;

    /**
     * Get the implicit to-many join path to the
     * <code>public.user_track_sources</code> table
     */
    public UserTrackSourcesPath userTrackSources() {
        if (_userTrackSources == null)
            _userTrackSources = new UserTrackSourcesPath(this, null, Keys.USER_TRACK_SOURCES__FK_USER_TRACK_SOURCES_CONNECTION.getInverseKey());

        return _userTrackSources;
    }

    @Override
    public List<Check<Record>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("provider_connections_provider_check"), "(((provider)::text = ANY ((ARRAY['GDRIVE'::character varying, 'HIDRIVE'::character varying])::text[])))", true),
            Internal.createCheck(this, DSL.name("provider_connections_status_check"), "(((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'NEEDS_RECONNECT'::character varying])::text[])))", true)
        );
    }

    @Override
    public ProviderConnections as(String alias) {
        return new ProviderConnections(DSL.name(alias), this);
    }

    @Override
    public ProviderConnections as(Name alias) {
        return new ProviderConnections(alias, this);
    }

    @Override
    public ProviderConnections as(Table<?> alias) {
        return new ProviderConnections(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProviderConnections rename(String name) {
        return new ProviderConnections(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProviderConnections rename(Name name) {
        return new ProviderConnections(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProviderConnections rename(Table<?> name) {
        return new ProviderConnections(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProviderConnections where(Condition condition) {
        return new ProviderConnections(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProviderConnections where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProviderConnections where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProviderConnections where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProviderConnections where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProviderConnections where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProviderConnections where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProviderConnections where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProviderConnections whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProviderConnections whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
