/*
 * This file is generated by jOOQ.
 */
package se.dansbart.jooq.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import se.dansbart.jooq.Indexes;
import se.dansbart.jooq.Keys;
import se.dansbart.jooq.Public;
import se.dansbart.jooq.tables.FolkwikiTunes.FolkwikiTunesPath;
import se.dansbart.jooq.tables.Tracks.TracksPath;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TrackFolkwikiMatches extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.track_folkwiki_matches</code>
     */
    public static final TrackFolkwikiMatches TRACK_FOLKWIKI_MATCHES = new TrackFolkwikiMatches();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.track_folkwiki_matches.track_id</code>.
     */
    public final TableField<Record, UUID> TRACK_ID = createField(DSL.name("track_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.track_folkwiki_matches.folkwiki_tune_id</code>.
     */
    public final TableField<Record, Integer> FOLKWIKI_TUNE_ID = createField(DSL.name("folkwiki_tune_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.track_folkwiki_matches.match_type</code>.
     */
    public final TableField<Record, String> MATCH_TYPE = createField(DSL.name("match_type"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.track_folkwiki_matches.match_status</code>.
     */
    public final TableField<Record, String> MATCH_STATUS = createField(DSL.name("match_status"), SQLDataType.CLOB.nullable(false).defaultValue(DSL.field(DSL.raw("'pending'::text"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>public.track_folkwiki_matches.confirmed_by</code>.
     */
    public final TableField<Record, String> CONFIRMED_BY = createField(DSL.name("confirmed_by"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.track_folkwiki_matches.confirmed_at</code>.
     */
    public final TableField<Record, OffsetDateTime> CONFIRMED_AT = createField(DSL.name("confirmed_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.track_folkwiki_matches.created_at</code>.
     */
    public final TableField<Record, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private TrackFolkwikiMatches(Name alias, Table<Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TrackFolkwikiMatches(Name alias, Table<Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.track_folkwiki_matches</code> table
     * reference
     */
    public TrackFolkwikiMatches(String alias) {
        this(DSL.name(alias), TRACK_FOLKWIKI_MATCHES);
    }

    /**
     * Create an aliased <code>public.track_folkwiki_matches</code> table
     * reference
     */
    public TrackFolkwikiMatches(Name alias) {
        this(alias, TRACK_FOLKWIKI_MATCHES);
    }

    /**
     * Create a <code>public.track_folkwiki_matches</code> table reference
     */
    public TrackFolkwikiMatches() {
        this(DSL.name("track_folkwiki_matches"), null);
    }

    public <O extends Record> TrackFolkwikiMatches(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
        super(path, childPath, parentPath, TRACK_FOLKWIKI_MATCHES);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TrackFolkwikiMatchesPath extends TrackFolkwikiMatches implements Path<Record> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TrackFolkwikiMatchesPath(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
            super(path, childPath, parentPath);
        }
        private TrackFolkwikiMatchesPath(Name alias, Table<Record> aliased) {
            super(alias, aliased);
        }

        @Override
        public TrackFolkwikiMatchesPath as(String alias) {
            return new TrackFolkwikiMatchesPath(DSL.name(alias), this);
        }

        @Override
        public TrackFolkwikiMatchesPath as(Name alias) {
            return new TrackFolkwikiMatchesPath(alias, this);
        }

        @Override
        public TrackFolkwikiMatchesPath as(Table<?> alias) {
            return new TrackFolkwikiMatchesPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_TRACK_FOLKWIKI_MATCHES_FOLKWIKI_TUNE_ID, Indexes.IDX_TRACK_FOLKWIKI_MATCHES_STATUS);
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.TRACK_FOLKWIKI_MATCHES_PKEY;
    }

    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.asList(Keys.TRACK_FOLKWIKI_MATCHES__TRACK_FOLKWIKI_MATCHES_TRACK_ID_FKEY, Keys.TRACK_FOLKWIKI_MATCHES__TRACK_FOLKWIKI_MATCHES_FOLKWIKI_TUNE_ID_FKEY);
    }

    private transient TracksPath _tracks;

    /**
     * Get the implicit join path to the <code>public.tracks</code> table.
     */
    public TracksPath tracks() {
        if (_tracks == null)
            _tracks = new TracksPath(this, Keys.TRACK_FOLKWIKI_MATCHES__TRACK_FOLKWIKI_MATCHES_TRACK_ID_FKEY, null);

        return _tracks;
    }

    private transient FolkwikiTunesPath _folkwikiTunes;

    /**
     * Get the implicit join path to the <code>public.folkwiki_tunes</code>
     * table.
     */
    public FolkwikiTunesPath folkwikiTunes() {
        if (_folkwikiTunes == null)
            _folkwikiTunes = new FolkwikiTunesPath(this, Keys.TRACK_FOLKWIKI_MATCHES__TRACK_FOLKWIKI_MATCHES_FOLKWIKI_TUNE_ID_FKEY, null);

        return _folkwikiTunes;
    }

    @Override
    public List<Check<Record>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("track_folkwiki_matches_match_status_check"), "((match_status = ANY (ARRAY['pending'::text, 'confirmed'::text, 'rejected'::text])))", true),
            Internal.createCheck(this, DSL.name("track_folkwiki_matches_match_type_check"), "((match_type = ANY (ARRAY['exact'::text, 'contains'::text])))", true)
        );
    }

    @Override
    public TrackFolkwikiMatches as(String alias) {
        return new TrackFolkwikiMatches(DSL.name(alias), this);
    }

    @Override
    public TrackFolkwikiMatches as(Name alias) {
        return new TrackFolkwikiMatches(alias, this);
    }

    @Override
    public TrackFolkwikiMatches as(Table<?> alias) {
        return new TrackFolkwikiMatches(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TrackFolkwikiMatches rename(String name) {
        return new TrackFolkwikiMatches(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TrackFolkwikiMatches rename(Name name) {
        return new TrackFolkwikiMatches(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TrackFolkwikiMatches rename(Table<?> name) {
        return new TrackFolkwikiMatches(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TrackFolkwikiMatches where(Condition condition) {
        return new TrackFolkwikiMatches(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TrackFolkwikiMatches where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TrackFolkwikiMatches where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TrackFolkwikiMatches where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TrackFolkwikiMatches where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TrackFolkwikiMatches where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TrackFolkwikiMatches where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TrackFolkwikiMatches where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TrackFolkwikiMatches whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TrackFolkwikiMatches whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
