/*
 * This file is generated by jOOQ.
 */
package se.dansbart.jooq.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import se.dansbart.jooq.Keys;
import se.dansbart.jooq.Public;
import se.dansbart.jooq.tables.Tracks.TracksPath;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TrackStructureVersions extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.track_structure_versions</code>
     */
    public static final TrackStructureVersions TRACK_STRUCTURE_VERSIONS = new TrackStructureVersions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.track_structure_versions.id</code>.
     */
    public final TableField<Record, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.track_structure_versions.track_id</code>.
     */
    public final TableField<Record, UUID> TRACK_ID = createField(DSL.name("track_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.track_structure_versions.created_at</code>.
     */
    public final TableField<Record, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.track_structure_versions.description</code>.
     */
    public final TableField<Record, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.track_structure_versions.structure_data</code>.
     */
    public final TableField<Record, JSONB> STRUCTURE_DATA = createField(DSL.name("structure_data"), SQLDataType.JSONB.nullable(false), this, "");

    /**
     * The column <code>public.track_structure_versions.vote_count</code>.
     */
    public final TableField<Record, Integer> VOTE_COUNT = createField(DSL.name("vote_count"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.track_structure_versions.report_count</code>.
     */
    public final TableField<Record, Integer> REPORT_COUNT = createField(DSL.name("report_count"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.track_structure_versions.is_active</code>.
     */
    public final TableField<Record, Boolean> IS_ACTIVE = createField(DSL.name("is_active"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.track_structure_versions.is_hidden</code>.
     */
    public final TableField<Record, Boolean> IS_HIDDEN = createField(DSL.name("is_hidden"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.track_structure_versions.author_alias</code>.
     */
    public final TableField<Record, String> AUTHOR_ALIAS = createField(DSL.name("author_alias"), SQLDataType.VARCHAR, this, "");

    private TrackStructureVersions(Name alias, Table<Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TrackStructureVersions(Name alias, Table<Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.track_structure_versions</code> table
     * reference
     */
    public TrackStructureVersions(String alias) {
        this(DSL.name(alias), TRACK_STRUCTURE_VERSIONS);
    }

    /**
     * Create an aliased <code>public.track_structure_versions</code> table
     * reference
     */
    public TrackStructureVersions(Name alias) {
        this(alias, TRACK_STRUCTURE_VERSIONS);
    }

    /**
     * Create a <code>public.track_structure_versions</code> table reference
     */
    public TrackStructureVersions() {
        this(DSL.name("track_structure_versions"), null);
    }

    public <O extends Record> TrackStructureVersions(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
        super(path, childPath, parentPath, TRACK_STRUCTURE_VERSIONS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TrackStructureVersionsPath extends TrackStructureVersions implements Path<Record> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TrackStructureVersionsPath(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
            super(path, childPath, parentPath);
        }
        private TrackStructureVersionsPath(Name alias, Table<Record> aliased) {
            super(alias, aliased);
        }

        @Override
        public TrackStructureVersionsPath as(String alias) {
            return new TrackStructureVersionsPath(DSL.name(alias), this);
        }

        @Override
        public TrackStructureVersionsPath as(Name alias) {
            return new TrackStructureVersionsPath(alias, this);
        }

        @Override
        public TrackStructureVersionsPath as(Table<?> alias) {
            return new TrackStructureVersionsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.TRACK_STRUCTURE_VERSIONS_PKEY;
    }

    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.asList(Keys.TRACK_STRUCTURE_VERSIONS__TRACK_STRUCTURE_VERSIONS_TRACK_ID_FKEY);
    }

    private transient TracksPath _tracks;

    /**
     * Get the implicit join path to the <code>public.tracks</code> table.
     */
    public TracksPath tracks() {
        if (_tracks == null)
            _tracks = new TracksPath(this, Keys.TRACK_STRUCTURE_VERSIONS__TRACK_STRUCTURE_VERSIONS_TRACK_ID_FKEY, null);

        return _tracks;
    }

    @Override
    public TrackStructureVersions as(String alias) {
        return new TrackStructureVersions(DSL.name(alias), this);
    }

    @Override
    public TrackStructureVersions as(Name alias) {
        return new TrackStructureVersions(alias, this);
    }

    @Override
    public TrackStructureVersions as(Table<?> alias) {
        return new TrackStructureVersions(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TrackStructureVersions rename(String name) {
        return new TrackStructureVersions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TrackStructureVersions rename(Name name) {
        return new TrackStructureVersions(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TrackStructureVersions rename(Table<?> name) {
        return new TrackStructureVersions(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TrackStructureVersions where(Condition condition) {
        return new TrackStructureVersions(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TrackStructureVersions where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TrackStructureVersions where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TrackStructureVersions where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TrackStructureVersions where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TrackStructureVersions where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TrackStructureVersions where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TrackStructureVersions where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TrackStructureVersions whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TrackStructureVersions whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
