/*
 * This file is generated by jOOQ.
 */
package se.dansbart.jooq.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import se.dansbart.jooq.Indexes;
import se.dansbart.jooq.Keys;
import se.dansbart.jooq.Public;
import se.dansbart.jooq.tables.Tracks.TracksPath;
import se.dansbart.jooq.tables.Users.UsersPath;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserTrackFavorites extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.user_track_favorites</code>
     */
    public static final UserTrackFavorites USER_TRACK_FAVORITES = new UserTrackFavorites();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.user_track_favorites.user_id</code>.
     */
    public final TableField<Record, UUID> USER_ID = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.user_track_favorites.track_id</code>.
     */
    public final TableField<Record, UUID> TRACK_ID = createField(DSL.name("track_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.user_track_favorites.created_at</code>.
     */
    public final TableField<Record, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private UserTrackFavorites(Name alias, Table<Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private UserTrackFavorites(Name alias, Table<Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.user_track_favorites</code> table
     * reference
     */
    public UserTrackFavorites(String alias) {
        this(DSL.name(alias), USER_TRACK_FAVORITES);
    }

    /**
     * Create an aliased <code>public.user_track_favorites</code> table
     * reference
     */
    public UserTrackFavorites(Name alias) {
        this(alias, USER_TRACK_FAVORITES);
    }

    /**
     * Create a <code>public.user_track_favorites</code> table reference
     */
    public UserTrackFavorites() {
        this(DSL.name("user_track_favorites"), null);
    }

    public <O extends Record> UserTrackFavorites(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
        super(path, childPath, parentPath, USER_TRACK_FAVORITES);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class UserTrackFavoritesPath extends UserTrackFavorites implements Path<Record> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> UserTrackFavoritesPath(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
            super(path, childPath, parentPath);
        }
        private UserTrackFavoritesPath(Name alias, Table<Record> aliased) {
            super(alias, aliased);
        }

        @Override
        public UserTrackFavoritesPath as(String alias) {
            return new UserTrackFavoritesPath(DSL.name(alias), this);
        }

        @Override
        public UserTrackFavoritesPath as(Name alias) {
            return new UserTrackFavoritesPath(alias, this);
        }

        @Override
        public UserTrackFavoritesPath as(Table<?> alias) {
            return new UserTrackFavoritesPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_USER_TRACK_FAVORITES_USER_ID);
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.USER_TRACK_FAVORITES_PKEY;
    }

    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.asList(Keys.USER_TRACK_FAVORITES__FK_FAVORITES_USER, Keys.USER_TRACK_FAVORITES__FK_FAVORITES_TRACK);
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.USER_TRACK_FAVORITES__FK_FAVORITES_USER, null);

        return _users;
    }

    private transient TracksPath _tracks;

    /**
     * Get the implicit join path to the <code>public.tracks</code> table.
     */
    public TracksPath tracks() {
        if (_tracks == null)
            _tracks = new TracksPath(this, Keys.USER_TRACK_FAVORITES__FK_FAVORITES_TRACK, null);

        return _tracks;
    }

    @Override
    public UserTrackFavorites as(String alias) {
        return new UserTrackFavorites(DSL.name(alias), this);
    }

    @Override
    public UserTrackFavorites as(Name alias) {
        return new UserTrackFavorites(alias, this);
    }

    @Override
    public UserTrackFavorites as(Table<?> alias) {
        return new UserTrackFavorites(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserTrackFavorites rename(String name) {
        return new UserTrackFavorites(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserTrackFavorites rename(Name name) {
        return new UserTrackFavorites(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserTrackFavorites rename(Table<?> name) {
        return new UserTrackFavorites(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserTrackFavorites where(Condition condition) {
        return new UserTrackFavorites(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserTrackFavorites where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserTrackFavorites where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserTrackFavorites where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserTrackFavorites where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserTrackFavorites where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserTrackFavorites where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserTrackFavorites where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserTrackFavorites whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserTrackFavorites whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
