/*
 * This file is generated by jOOQ.
 */
package se.dansbart.jooq.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import se.dansbart.jooq.Indexes;
import se.dansbart.jooq.Keys;
import se.dansbart.jooq.Public;
import se.dansbart.jooq.tables.Dances.DancesPath;
import se.dansbart.jooq.tables.Tracks.TracksPath;
import se.dansbart.jooq.tables.Users.UsersPath;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserDancePrimaryTracks extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.user_dance_primary_tracks</code>
     */
    public static final UserDancePrimaryTracks USER_DANCE_PRIMARY_TRACKS = new UserDancePrimaryTracks();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.user_dance_primary_tracks.user_id</code>.
     */
    public final TableField<Record, UUID> USER_ID = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.user_dance_primary_tracks.dance_id</code>.
     */
    public final TableField<Record, UUID> DANCE_ID = createField(DSL.name("dance_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.user_dance_primary_tracks.track_id</code>.
     */
    public final TableField<Record, UUID> TRACK_ID = createField(DSL.name("track_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.user_dance_primary_tracks.created_at</code>.
     */
    public final TableField<Record, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private UserDancePrimaryTracks(Name alias, Table<Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private UserDancePrimaryTracks(Name alias, Table<Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.user_dance_primary_tracks</code> table
     * reference
     */
    public UserDancePrimaryTracks(String alias) {
        this(DSL.name(alias), USER_DANCE_PRIMARY_TRACKS);
    }

    /**
     * Create an aliased <code>public.user_dance_primary_tracks</code> table
     * reference
     */
    public UserDancePrimaryTracks(Name alias) {
        this(alias, USER_DANCE_PRIMARY_TRACKS);
    }

    /**
     * Create a <code>public.user_dance_primary_tracks</code> table reference
     */
    public UserDancePrimaryTracks() {
        this(DSL.name("user_dance_primary_tracks"), null);
    }

    public <O extends Record> UserDancePrimaryTracks(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
        super(path, childPath, parentPath, USER_DANCE_PRIMARY_TRACKS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class UserDancePrimaryTracksPath extends UserDancePrimaryTracks implements Path<Record> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> UserDancePrimaryTracksPath(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
            super(path, childPath, parentPath);
        }
        private UserDancePrimaryTracksPath(Name alias, Table<Record> aliased) {
            super(alias, aliased);
        }

        @Override
        public UserDancePrimaryTracksPath as(String alias) {
            return new UserDancePrimaryTracksPath(DSL.name(alias), this);
        }

        @Override
        public UserDancePrimaryTracksPath as(Name alias) {
            return new UserDancePrimaryTracksPath(alias, this);
        }

        @Override
        public UserDancePrimaryTracksPath as(Table<?> alias) {
            return new UserDancePrimaryTracksPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_UDPT_USER);
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.USER_DANCE_PRIMARY_TRACKS_PKEY;
    }

    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.asList(Keys.USER_DANCE_PRIMARY_TRACKS__FK_UDPT_USER, Keys.USER_DANCE_PRIMARY_TRACKS__FK_UDPT_DANCE, Keys.USER_DANCE_PRIMARY_TRACKS__FK_UDPT_TRACK);
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.USER_DANCE_PRIMARY_TRACKS__FK_UDPT_USER, null);

        return _users;
    }

    private transient DancesPath _dances;

    /**
     * Get the implicit join path to the <code>public.dances</code> table.
     */
    public DancesPath dances() {
        if (_dances == null)
            _dances = new DancesPath(this, Keys.USER_DANCE_PRIMARY_TRACKS__FK_UDPT_DANCE, null);

        return _dances;
    }

    private transient TracksPath _tracks;

    /**
     * Get the implicit join path to the <code>public.tracks</code> table.
     */
    public TracksPath tracks() {
        if (_tracks == null)
            _tracks = new TracksPath(this, Keys.USER_DANCE_PRIMARY_TRACKS__FK_UDPT_TRACK, null);

        return _tracks;
    }

    @Override
    public UserDancePrimaryTracks as(String alias) {
        return new UserDancePrimaryTracks(DSL.name(alias), this);
    }

    @Override
    public UserDancePrimaryTracks as(Name alias) {
        return new UserDancePrimaryTracks(alias, this);
    }

    @Override
    public UserDancePrimaryTracks as(Table<?> alias) {
        return new UserDancePrimaryTracks(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserDancePrimaryTracks rename(String name) {
        return new UserDancePrimaryTracks(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserDancePrimaryTracks rename(Name name) {
        return new UserDancePrimaryTracks(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserDancePrimaryTracks rename(Table<?> name) {
        return new UserDancePrimaryTracks(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserDancePrimaryTracks where(Condition condition) {
        return new UserDancePrimaryTracks(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserDancePrimaryTracks where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserDancePrimaryTracks where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserDancePrimaryTracks where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserDancePrimaryTracks where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserDancePrimaryTracks where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserDancePrimaryTracks where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserDancePrimaryTracks where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserDancePrimaryTracks whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserDancePrimaryTracks whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
