/*
 * This file is generated by jOOQ.
 */
package se.dansbart.jooq.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import se.dansbart.jooq.Indexes;
import se.dansbart.jooq.Keys;
import se.dansbart.jooq.Public;
import se.dansbart.jooq.tables.Tracks.TracksPath;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserInteractions extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.user_interactions</code>
     */
    public static final UserInteractions USER_INTERACTIONS = new UserInteractions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.user_interactions.id</code>.
     */
    public final TableField<Record, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.user_interactions.track_id</code>.
     */
    public final TableField<Record, UUID> TRACK_ID = createField(DSL.name("track_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.user_interactions.event_type</code>.
     */
    public final TableField<Record, String> EVENT_TYPE = createField(DSL.name("event_type"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.user_interactions.event_data</code>.
     */
    public final TableField<Record, JSONB> EVENT_DATA = createField(DSL.name("event_data"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>public.user_interactions.created_at</code>.
     */
    public final TableField<Record, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.user_interactions.session_id</code>.
     */
    public final TableField<Record, String> SESSION_ID = createField(DSL.name("session_id"), SQLDataType.VARCHAR, this, "");

    private UserInteractions(Name alias, Table<Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private UserInteractions(Name alias, Table<Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.user_interactions</code> table reference
     */
    public UserInteractions(String alias) {
        this(DSL.name(alias), USER_INTERACTIONS);
    }

    /**
     * Create an aliased <code>public.user_interactions</code> table reference
     */
    public UserInteractions(Name alias) {
        this(alias, USER_INTERACTIONS);
    }

    /**
     * Create a <code>public.user_interactions</code> table reference
     */
    public UserInteractions() {
        this(DSL.name("user_interactions"), null);
    }

    public <O extends Record> UserInteractions(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
        super(path, childPath, parentPath, USER_INTERACTIONS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class UserInteractionsPath extends UserInteractions implements Path<Record> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> UserInteractionsPath(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
            super(path, childPath, parentPath);
        }
        private UserInteractionsPath(Name alias, Table<Record> aliased) {
            super(alias, aliased);
        }

        @Override
        public UserInteractionsPath as(String alias) {
            return new UserInteractionsPath(DSL.name(alias), this);
        }

        @Override
        public UserInteractionsPath as(Name alias) {
            return new UserInteractionsPath(alias, this);
        }

        @Override
        public UserInteractionsPath as(Table<?> alias) {
            return new UserInteractionsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IX_USER_INTERACTIONS_CREATED_AT, Indexes.IX_USER_INTERACTIONS_EVENT_TYPE, Indexes.IX_USER_INTERACTIONS_SESSION_ID, Indexes.IX_USER_INTERACTIONS_TRACK_ID);
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.USER_INTERACTIONS_PKEY;
    }

    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.asList(Keys.USER_INTERACTIONS__USER_INTERACTIONS_TRACK_ID_FKEY);
    }

    private transient TracksPath _tracks;

    /**
     * Get the implicit join path to the <code>public.tracks</code> table.
     */
    public TracksPath tracks() {
        if (_tracks == null)
            _tracks = new TracksPath(this, Keys.USER_INTERACTIONS__USER_INTERACTIONS_TRACK_ID_FKEY, null);

        return _tracks;
    }

    @Override
    public UserInteractions as(String alias) {
        return new UserInteractions(DSL.name(alias), this);
    }

    @Override
    public UserInteractions as(Name alias) {
        return new UserInteractions(alias, this);
    }

    @Override
    public UserInteractions as(Table<?> alias) {
        return new UserInteractions(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserInteractions rename(String name) {
        return new UserInteractions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserInteractions rename(Name name) {
        return new UserInteractions(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserInteractions rename(Table<?> name) {
        return new UserInteractions(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserInteractions where(Condition condition) {
        return new UserInteractions(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserInteractions where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserInteractions where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserInteractions where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserInteractions where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserInteractions where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserInteractions where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserInteractions where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserInteractions whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserInteractions whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
