/*
 * This file is generated by jOOQ.
 */
package se.dansbart.jooq.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import se.dansbart.jooq.Indexes;
import se.dansbart.jooq.Keys;
import se.dansbart.jooq.Public;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VisitorSessions extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.visitor_sessions</code>
     */
    public static final VisitorSessions VISITOR_SESSIONS = new VisitorSessions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.visitor_sessions.id</code>.
     */
    public final TableField<Record, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.visitor_sessions.session_id</code>.
     */
    public final TableField<Record, String> SESSION_ID = createField(DSL.name("session_id"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.visitor_sessions.first_seen</code>.
     */
    public final TableField<Record, OffsetDateTime> FIRST_SEEN = createField(DSL.name("first_seen"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.visitor_sessions.last_seen</code>.
     */
    public final TableField<Record, OffsetDateTime> LAST_SEEN = createField(DSL.name("last_seen"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.visitor_sessions.user_agent</code>.
     */
    public final TableField<Record, String> USER_AGENT = createField(DSL.name("user_agent"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.visitor_sessions.is_returning</code>.
     */
    public final TableField<Record, Boolean> IS_RETURNING = createField(DSL.name("is_returning"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.visitor_sessions.page_views</code>.
     */
    public final TableField<Record, Integer> PAGE_VIEWS = createField(DSL.name("page_views"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.visitor_sessions.is_authenticated</code>.
     */
    public final TableField<Record, Boolean> IS_AUTHENTICATED = createField(DSL.name("is_authenticated"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.visitor_sessions.device_type</code>.
     */
    public final TableField<Record, String> DEVICE_TYPE = createField(DSL.name("device_type"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.visitor_sessions.used_search</code>.
     */
    public final TableField<Record, Boolean> USED_SEARCH = createField(DSL.name("used_search"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.visitor_sessions.used_playlists</code>.
     */
    public final TableField<Record, Boolean> USED_PLAYLISTS = createField(DSL.name("used_playlists"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.visitor_sessions.used_library</code>.
     */
    public final TableField<Record, Boolean> USED_LIBRARY = createField(DSL.name("used_library"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.visitor_sessions.used_discovery</code>.
     */
    public final TableField<Record, Boolean> USED_DISCOVERY = createField(DSL.name("used_discovery"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    private VisitorSessions(Name alias, Table<Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private VisitorSessions(Name alias, Table<Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.visitor_sessions</code> table reference
     */
    public VisitorSessions(String alias) {
        this(DSL.name(alias), VISITOR_SESSIONS);
    }

    /**
     * Create an aliased <code>public.visitor_sessions</code> table reference
     */
    public VisitorSessions(Name alias) {
        this(alias, VISITOR_SESSIONS);
    }

    /**
     * Create a <code>public.visitor_sessions</code> table reference
     */
    public VisitorSessions() {
        this(DSL.name("visitor_sessions"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IX_VISITOR_SESSIONS_FIRST_SEEN, Indexes.IX_VISITOR_SESSIONS_LAST_SEEN, Indexes.IX_VISITOR_SESSIONS_SESSION_ID);
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.VISITOR_SESSIONS_PKEY;
    }

    @Override
    public VisitorSessions as(String alias) {
        return new VisitorSessions(DSL.name(alias), this);
    }

    @Override
    public VisitorSessions as(Name alias) {
        return new VisitorSessions(alias, this);
    }

    @Override
    public VisitorSessions as(Table<?> alias) {
        return new VisitorSessions(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public VisitorSessions rename(String name) {
        return new VisitorSessions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VisitorSessions rename(Name name) {
        return new VisitorSessions(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public VisitorSessions rename(Table<?> name) {
        return new VisitorSessions(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VisitorSessions where(Condition condition) {
        return new VisitorSessions(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VisitorSessions where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VisitorSessions where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VisitorSessions where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VisitorSessions where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VisitorSessions where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VisitorSessions where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VisitorSessions where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VisitorSessions whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VisitorSessions whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
