/*
 * This file is generated by jOOQ.
 */
package se.dansbart.jooq;


import se.dansbart.jooq.tables.Albums;
import se.dansbart.jooq.tables.AnalysisSources;
import se.dansbart.jooq.tables.ArtistCrawlLogs;
import se.dansbart.jooq.tables.Artists;
import se.dansbart.jooq.tables.DanceMovementFeedback;
import se.dansbart.jooq.tables.GenreProfiles;
import se.dansbart.jooq.tables.PendingArtistApprovals;
import se.dansbart.jooq.tables.PlaybackLinks;
import se.dansbart.jooq.tables.PlaylistCollaborators;
import se.dansbart.jooq.tables.PlaylistTracks;
import se.dansbart.jooq.tables.Playlists;
import se.dansbart.jooq.tables.RejectionLogs;
import se.dansbart.jooq.tables.StyleKeywords;
import se.dansbart.jooq.tables.TrackAlbums;
import se.dansbart.jooq.tables.TrackArtists;
import se.dansbart.jooq.tables.TrackDanceStyles;
import se.dansbart.jooq.tables.TrackFeelVotes;
import se.dansbart.jooq.tables.TrackPlaybacks;
import se.dansbart.jooq.tables.TrackStructureVersions;
import se.dansbart.jooq.tables.TrackStyleVotes;
import se.dansbart.jooq.tables.Tracks;
import se.dansbart.jooq.tables.UserInteractions;
import se.dansbart.jooq.tables.Users;
import se.dansbart.jooq.tables.VisitorSessions;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>ALBUMS</code>.
     */
    public static final Albums ALBUMS = Albums.ALBUMS;

    /**
     * The table <code>ANALYSIS_SOURCES</code>.
     */
    public static final AnalysisSources ANALYSIS_SOURCES = AnalysisSources.ANALYSIS_SOURCES;

    /**
     * The table <code>ARTIST_CRAWL_LOGS</code>.
     */
    public static final ArtistCrawlLogs ARTIST_CRAWL_LOGS = ArtistCrawlLogs.ARTIST_CRAWL_LOGS;

    /**
     * The table <code>ARTISTS</code>.
     */
    public static final Artists ARTISTS = Artists.ARTISTS;

    /**
     * The table <code>DANCE_MOVEMENT_FEEDBACK</code>.
     */
    public static final DanceMovementFeedback DANCE_MOVEMENT_FEEDBACK = DanceMovementFeedback.DANCE_MOVEMENT_FEEDBACK;

    /**
     * The table <code>GENRE_PROFILES</code>.
     */
    public static final GenreProfiles GENRE_PROFILES = GenreProfiles.GENRE_PROFILES;

    /**
     * The table <code>PENDING_ARTIST_APPROVALS</code>.
     */
    public static final PendingArtistApprovals PENDING_ARTIST_APPROVALS = PendingArtistApprovals.PENDING_ARTIST_APPROVALS;

    /**
     * The table <code>PLAYBACK_LINKS</code>.
     */
    public static final PlaybackLinks PLAYBACK_LINKS = PlaybackLinks.PLAYBACK_LINKS;

    /**
     * The table <code>PLAYLIST_COLLABORATORS</code>.
     */
    public static final PlaylistCollaborators PLAYLIST_COLLABORATORS = PlaylistCollaborators.PLAYLIST_COLLABORATORS;

    /**
     * The table <code>PLAYLIST_TRACKS</code>.
     */
    public static final PlaylistTracks PLAYLIST_TRACKS = PlaylistTracks.PLAYLIST_TRACKS;

    /**
     * The table <code>PLAYLISTS</code>.
     */
    public static final Playlists PLAYLISTS = Playlists.PLAYLISTS;

    /**
     * The table <code>REJECTION_LOGS</code>.
     */
    public static final RejectionLogs REJECTION_LOGS = RejectionLogs.REJECTION_LOGS;

    /**
     * The table <code>STYLE_KEYWORDS</code>.
     */
    public static final StyleKeywords STYLE_KEYWORDS = StyleKeywords.STYLE_KEYWORDS;

    /**
     * The table <code>TRACK_ALBUMS</code>.
     */
    public static final TrackAlbums TRACK_ALBUMS = TrackAlbums.TRACK_ALBUMS;

    /**
     * The table <code>TRACK_ARTISTS</code>.
     */
    public static final TrackArtists TRACK_ARTISTS = TrackArtists.TRACK_ARTISTS;

    /**
     * The table <code>TRACK_DANCE_STYLES</code>.
     */
    public static final TrackDanceStyles TRACK_DANCE_STYLES = TrackDanceStyles.TRACK_DANCE_STYLES;

    /**
     * The table <code>TRACK_FEEL_VOTES</code>.
     */
    public static final TrackFeelVotes TRACK_FEEL_VOTES = TrackFeelVotes.TRACK_FEEL_VOTES;

    /**
     * The table <code>TRACK_PLAYBACKS</code>.
     */
    public static final TrackPlaybacks TRACK_PLAYBACKS = TrackPlaybacks.TRACK_PLAYBACKS;

    /**
     * The table <code>TRACK_STRUCTURE_VERSIONS</code>.
     */
    public static final TrackStructureVersions TRACK_STRUCTURE_VERSIONS = TrackStructureVersions.TRACK_STRUCTURE_VERSIONS;

    /**
     * The table <code>TRACK_STYLE_VOTES</code>.
     */
    public static final TrackStyleVotes TRACK_STYLE_VOTES = TrackStyleVotes.TRACK_STYLE_VOTES;

    /**
     * The table <code>TRACKS</code>.
     */
    public static final Tracks TRACKS = Tracks.TRACKS;

    /**
     * The table <code>USER_INTERACTIONS</code>.
     */
    public static final UserInteractions USER_INTERACTIONS = UserInteractions.USER_INTERACTIONS;

    /**
     * The table <code>USERS</code>.
     */
    public static final Users USERS = Users.USERS;

    /**
     * The table <code>VISITOR_SESSIONS</code>.
     */
    public static final VisitorSessions VISITOR_SESSIONS = VisitorSessions.VISITOR_SESSIONS;
}
