/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TrackListDto } from './trackListDto';

export interface CuratedPlaylistDto {
  id?: string;
  name?: string;
  description?: string;
  trackCount?: number;
  tracks?: TrackListDto[];
}
