/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ExportDatasetParams = {
  /**
   * Limit number of tracks (omit for full export)
   */
  limit?: number;
  /**
   * Offset for pagination
   */
  offset?: number;
};
