/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type GetPopularTracksParams = {
  /**
   * Number of tracks to return (1-20)
   */
  limit?: number;
  /**
   * Days to look back for popularity (1-90)
   */
  days?: number;
};
