/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Track } from './track';
import type { Artist } from './artist';

export interface TrackArtist {
  id?: string;
  trackId?: string;
  artistId?: string;
  role?: string;
  track?: Track;
  artist?: Artist;
}
