/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Track } from './track';

export interface TrackStyleVote {
  id?: string;
  trackId?: string;
  track?: Track;
  voterId?: string;
  suggestedStyle?: string;
  tempoCorrection?: string;
  createdAt?: string;
}
