/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Albums linked to this artist
 */
export interface AlbumSummaryDto {
  id?: string;
  title?: string;
  coverImageUrl?: string;
  releaseDate?: string;
  trackCount?: number;
}
