/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface BlockSpotifyRequest {
  spotifyId?: string;
  artistName?: string;
  reason?: string;
}
