/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface CollaboratorDto {
  id?: string;
  userId?: string;
  username?: string;
  displayName?: string;
  permission?: string;
  status?: string;
  invitedAt?: string;
  acceptedAt?: string;
}
