/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Dance entry with link to description and track count
 */
export interface Dance {
  /** Unique identifier */
  id?: string;
  /** Display name of the dance */
  name?: string;
  /** URL-safe slug derived from the name */
  slug?: string;
  /** Link to the external dance description page */
  danceDescriptionUrl?: string;
  /** Dance category from (e.g. Hambo, Vals, Polka) */
  danceType?: string;
  /** Tune/track name description (e.g. Lugn hambo) */
  music?: string;
  /** Number of confirmed tracks linked to this dance */
  confirmedTrackCount?: number;
}
