/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PlaylistTrackDto } from './playlistTrackDto';

export interface DanceListEntryDto {
  id?: string;
  danceId?: string;
  danceName?: string;
  freeTextName?: string;
  playMode?: string;
  position?: number;
  tracks?: PlaylistTrackDto[];
}
