/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CollaboratorDto } from './collaboratorDto';
import type { DanceListEntryDto } from './danceListEntryDto';
import type { GroupSummaryDto } from './groupSummaryDto';
import type { UserSummaryDto } from './userSummaryDto';

export interface DanceListDto {
  id?: string;
  name?: string;
  description?: string;
  isPublic?: boolean;
  shareToken?: string;
  createdAt?: string;
  updatedAt?: string;
  owner?: UserSummaryDto;
  ownerGroup?: GroupSummaryDto;
  viewerCanManage?: boolean;
  entries?: DanceListEntryDto[];
  collaborators?: CollaboratorDto[];
}
