/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ExportDatasetParams = {
/**
 * Limit number of tracks (omit for full export)
 */
limit?: number;
/**
 * Offset for pagination
 */
offset?: number;
};
