/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type GetAlbums1Params = {
search?: string;
artistId?: string;
limit?: number;
offset?: number;
};
