/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type GetKeywords1Params = {
search?: string;
mainStyle?: string;
isActive?: boolean;
limit?: number;
offset?: number;
};
