/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type GetPopularTracksParams = {
/**
 * Number of tracks to return (1-20)
 */
limit?: number;
/**
 * Days to look back for popularity (1-90)
 */
days?: number;
};
