/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface GroupSummaryDto {
  id?: string;
  name?: string;
  isPublic?: boolean;
  memberCount?: number;
}
