/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface ImportTrackRequest {
  /** @pattern ^[0-9a-f]{64}$ */
  contentHash?: string;
  /** @pattern ^(LOCAL|GDRIVE|HIDRIVE)$ */
  provider?: string;
  providerFileId?: string;
  /** @minLength 1 */
  title: string;
  artist?: string;
  album?: string;
  durationMs?: number;
  isrc?: string;
}
