/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { LibrarySourceRefDto } from './librarySourceRefDto';
import type { TrackListDto } from './trackListDto';

export interface LibraryTrackDto {
  track?: TrackListDto;
  linkedToCatalog?: boolean;
  sources?: LibrarySourceRefDto[];
}
