/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Album } from './album';

export interface PageResponseAlbum {
  items?: Album[];
  total?: number;
  page?: number;
  size?: number;
  hasMore?: boolean;
}
