/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Artist } from './artist';

export interface PageResponseArtist {
  items?: Artist[];
  total?: number;
  page?: number;
  size?: number;
  hasMore?: boolean;
}
