/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { DanceTrack } from './danceTrack';

export interface PageResponseDanceTrack {
  items?: DanceTrack[];
  total?: number;
  page?: number;
  size?: number;
  hasMore?: boolean;
}
