/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { GroupSummaryDto } from './groupSummaryDto';

export interface PlaylistListItemDto {
  id?: string;
  name?: string;
  description?: string;
  isPublic?: boolean;
  danceStyle?: string;
  subStyle?: string;
  tempoCategory?: string;
  trackCount?: number;
  ownerGroup?: GroupSummaryDto;
}
