/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Track } from './track';

export interface PlaybackLink {
  id?: string;
  trackId?: string;
  track?: Track;
  platform?: string;
  deepLink?: string;
  isWorking?: boolean;
}
