/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PlaylistCollaborator } from './playlistCollaborator';
import type { PlaylistTrack } from './playlistTrack';
import type { User } from './user';

export interface Playlist {
  id?: string;
  name?: string;
  description?: string;
  userId?: string;
  user?: User;
  isPublic?: boolean;
  shareToken?: string;
  danceStyle?: string;
  subStyle?: string;
  tempoCategory?: string;
  createdAt?: string;
  updatedAt?: string;
  tracks?: PlaylistTrack[];
  collaborators?: PlaylistCollaborator[];
}
