/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PlaylistTrackDto } from './playlistTrackDto';
import type { UserSummaryDto } from './userSummaryDto';

export interface PlaylistDto {
  id?: string;
  name?: string;
  description?: string;
  isPublic?: boolean;
  shareToken?: string;
  danceStyle?: string;
  subStyle?: string;
  tempoCategory?: string;
  createdAt?: string;
  updatedAt?: string;
  owner?: UserSummaryDto;
  trackCount?: number;
  tracks?: PlaylistTrackDto[];
  collaborators?: UserSummaryDto[];
}
