/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TrackListDto } from './trackListDto';

export interface PlaylistTrackDto {
  id?: string;
  position?: number;
  addedAt?: string;
  addedByUserId?: string;
  track?: TrackListDto;
}
