/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { RecordInteractionRequestEventData } from './recordInteractionRequestEventData';

export interface RecordInteractionRequest {
  trackId?: string;
  eventType?: string;
  eventData?: RecordInteractionRequestEventData;
  sessionId?: string;
}
