/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface RecordPlaybackRequest {
  platform?: string;
  durationSeconds?: number;
  completed?: boolean;
  sessionId?: string;
}
