/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface StructureRequest {
  bars?: number[];
  sections?: number[];
  sectionLabels?: string[];
  authorAlias?: string;
}
