/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface StyleKeyword {
  id?: string;
  keyword?: string;
  mainStyle?: string;
  subStyle?: string;
  isActive?: boolean;
  createdAt?: string;
  updatedAt?: string;
}
