/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { SuggestionDtoPayload } from './suggestionDtoPayload';

export interface SuggestionDto {
  id?: string;
  kind?: string;
  payload?: SuggestionDtoPayload;
  note?: string;
  voterId?: string;
  status?: string;
  reviewedBy?: string;
  reviewedAt?: string;
  reviewNote?: string;
  resolvedRefId?: string;
  activatedAt?: string;
  createdAt?: string;
}
