/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface Track {
  id?: string;
  title?: string;
  isrc?: string;
  durationMs?: number;
  tempoBpm?: number;
  createdAt?: string;
  hasVocals?: boolean;
  swingRatio?: number;
  articulation?: number;
  bounciness?: number;
  loudness?: number;
  punchiness?: number;
  voiceProbability?: number;
  polskaScore?: number;
  hamboScore?: number;
  bpmStability?: number;
  isInstrumental?: boolean;
  analysisVersion?: string;
  musicGenre?: string;
  genreConfidence?: number;
  isFlagged?: boolean;
  flaggedAt?: string;
  flagReason?: string;
  uploaderId?: string;
  processingStatus?: string;
  bars?: number[];
  sections?: number[];
  sectionLabels?: string[];
}
