/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type TrackStructureVersionStructureData = {[key: string]: { [key: string]: unknown }};
