/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PlaybackLinkDto } from './playbackLinkDto';

export interface TrackListDto {
  id?: string;
  title?: string;
  durationMs?: number;
  danceStyle?: string;
  subStyle?: string;
  matchedStyle?: string;
  effectiveBpm?: number;
  tempoCategory?: string;
  confidence?: number;
  hasVocals?: boolean;
  artistName?: string;
  playbackLinks?: PlaybackLinkDto[];
}
