/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Playlist } from './playlist';
import type { PlaylistCollaborator } from './playlistCollaborator';

export interface User {
  id?: string;
  username?: string;
  displayName?: string;
  avatarUrl?: string;
  createdAt?: string;
  lastLoginAt?: string;
  playlists?: Playlist[];
  collaborations?: PlaylistCollaborator[];
}
