/*
 * This file is generated by jOOQ.
 */
package se.dansbart.jooq;


import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import se.dansbart.jooq.tables.Albums;
import se.dansbart.jooq.tables.ArtistCrawlLogs;
import se.dansbart.jooq.tables.Artists;
import se.dansbart.jooq.tables.DanceMovementFeedback;
import se.dansbart.jooq.tables.DanceStyleConfig;
import se.dansbart.jooq.tables.DanceTrackVotes;
import se.dansbart.jooq.tables.DanceTracks;
import se.dansbart.jooq.tables.FolkwikiTunes;
import se.dansbart.jooq.tables.GenreProfiles;
import se.dansbart.jooq.tables.PathCounts;
import se.dansbart.jooq.tables.PendingArtistApprovals;
import se.dansbart.jooq.tables.PlaybackLinks;
import se.dansbart.jooq.tables.PlaylistCollaborators;
import se.dansbart.jooq.tables.PlaylistTracks;
import se.dansbart.jooq.tables.Playlists;
import se.dansbart.jooq.tables.RejectionLogs;
import se.dansbart.jooq.tables.StyleKeywords;
import se.dansbart.jooq.tables.TrackDanceStyles;
import se.dansbart.jooq.tables.TrackFeelVotes;
import se.dansbart.jooq.tables.TrackFolkwikiMatches;
import se.dansbart.jooq.tables.TrackPlaybacks;
import se.dansbart.jooq.tables.TrackStyleVotes;
import se.dansbart.jooq.tables.Tracks;
import se.dansbart.jooq.tables.UserInteractions;
import se.dansbart.jooq.tables.Users;
import se.dansbart.jooq.tables.VisitorSessions;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX_DANCE_STYLE_CONFIG_MAIN_STYLE = Internal.createIndex(DSL.name("idx_dance_style_config_main_style"), DanceStyleConfig.DANCE_STYLE_CONFIG, new OrderField[] { DanceStyleConfig.DANCE_STYLE_CONFIG.MAIN_STYLE }, false);
    public static final Index IDX_DANCE_TRACKS_CONFIRMED = Internal.createIndex(DSL.name("idx_dance_tracks_confirmed"), DanceTracks.DANCE_TRACKS, new OrderField[] { DanceTracks.DANCE_TRACKS.IS_CONFIRMED }, false);
    public static final Index IDX_DANCE_TRACKS_DANCE_ID = Internal.createIndex(DSL.name("idx_dance_tracks_dance_id"), DanceTracks.DANCE_TRACKS, new OrderField[] { DanceTracks.DANCE_TRACKS.DANCE_ID }, false);
    public static final Index IDX_DANCE_TRACKS_TRACK_ID = Internal.createIndex(DSL.name("idx_dance_tracks_track_id"), DanceTracks.DANCE_TRACKS, new OrderField[] { DanceTracks.DANCE_TRACKS.TRACK_ID }, false);
    public static final Index IDX_FOLKWIKI_TUNES_NORMALIZED_TITLE = Internal.createIndex(DSL.name("idx_folkwiki_tunes_normalized_title"), FolkwikiTunes.FOLKWIKI_TUNES, new OrderField[] { FolkwikiTunes.FOLKWIKI_TUNES.NORMALIZED_TITLE }, false);
    public static final Index IDX_FOLKWIKI_TUNES_STYLE = Internal.createIndex(DSL.name("idx_folkwiki_tunes_style"), FolkwikiTunes.FOLKWIKI_TUNES, new OrderField[] { FolkwikiTunes.FOLKWIKI_TUNES.STYLE }, false);
    public static final Index IDX_PLAYLIST_COLLABORATORS_PLAYLIST = Internal.createIndex(DSL.name("idx_playlist_collaborators_playlist"), PlaylistCollaborators.PLAYLIST_COLLABORATORS, new OrderField[] { PlaylistCollaborators.PLAYLIST_COLLABORATORS.PLAYLIST_ID }, false);
    public static final Index IDX_PLAYLIST_COLLABORATORS_STATUS = Internal.createIndex(DSL.name("idx_playlist_collaborators_status"), PlaylistCollaborators.PLAYLIST_COLLABORATORS, new OrderField[] { PlaylistCollaborators.PLAYLIST_COLLABORATORS.STATUS }, false);
    public static final Index IDX_PLAYLIST_COLLABORATORS_USER = Internal.createIndex(DSL.name("idx_playlist_collaborators_user"), PlaylistCollaborators.PLAYLIST_COLLABORATORS, new OrderField[] { PlaylistCollaborators.PLAYLIST_COLLABORATORS.USER_ID }, false);
    public static final Index IDX_TRACK_FOLKWIKI_MATCHES_FOLKWIKI_TUNE_ID = Internal.createIndex(DSL.name("idx_track_folkwiki_matches_folkwiki_tune_id"), TrackFolkwikiMatches.TRACK_FOLKWIKI_MATCHES, new OrderField[] { TrackFolkwikiMatches.TRACK_FOLKWIKI_MATCHES.FOLKWIKI_TUNE_ID }, false);
    public static final Index IDX_TRACK_FOLKWIKI_MATCHES_STATUS = Internal.createIndex(DSL.name("idx_track_folkwiki_matches_status"), TrackFolkwikiMatches.TRACK_FOLKWIKI_MATCHES, new OrderField[] { TrackFolkwikiMatches.TRACK_FOLKWIKI_MATCHES.MATCH_STATUS }, false);
    public static final Index IDX_TRACKS_ASYMMETRY_SCORE = Internal.createIndex(DSL.name("idx_tracks_asymmetry_score"), Tracks.TRACKS, new OrderField[] { Tracks.TRACKS.ASYMMETRY_SCORE }, false);
    public static final Index IDX_TRACKS_ISRC_NON_UNIQUE = Internal.createIndex(DSL.name("idx_tracks_isrc_non_unique"), Tracks.TRACKS, new OrderField[] { Tracks.TRACKS.ISRC }, false);
    public static final Index IDX_TRACKS_LILT_SCORE = Internal.createIndex(DSL.name("idx_tracks_lilt_score"), Tracks.TRACKS, new OrderField[] { Tracks.TRACKS.LILT_SCORE }, false);
    public static final Index IDX_TRACKS_PATTERN_TYPE = Internal.createIndex(DSL.name("idx_tracks_pattern_type"), Tracks.TRACKS, new OrderField[] { Tracks.TRACKS.PATTERN_TYPE }, false);
    public static final Index IDX_TRACKS_PROCESSING_STATUS = Internal.createIndex(DSL.name("idx_tracks_processing_status"), Tracks.TRACKS, new OrderField[] { Tracks.TRACKS.PROCESSING_STATUS }, false);
    public static final Index IDX_USERS_DISCOURSE_ID = Internal.createIndex(DSL.name("idx_users_discourse_id"), Users.USERS, new OrderField[] { Users.USERS.DISCOURSE_ID }, false);
    public static final Index IX_ALBUMS_SPOTIFY_ID = Internal.createIndex(DSL.name("ix_albums_spotify_id"), Albums.ALBUMS, new OrderField[] { Albums.ALBUMS.SPOTIFY_ID }, true);
    public static final Index IX_ALBUMS_TITLE = Internal.createIndex(DSL.name("ix_albums_title"), Albums.ALBUMS, new OrderField[] { Albums.ALBUMS.TITLE }, false);
    public static final Index IX_ALBUMS_TITLE_TRGM = Internal.createIndex(DSL.name("ix_albums_title_trgm"), Albums.ALBUMS, new OrderField[] { Albums.ALBUMS.TITLE }, false);
    public static final Index IX_ARTIST_CRAWL_LOGS_SPOTIFY_ARTIST_ID = Internal.createIndex(DSL.name("ix_artist_crawl_logs_spotify_artist_id"), ArtistCrawlLogs.ARTIST_CRAWL_LOGS, new OrderField[] { ArtistCrawlLogs.ARTIST_CRAWL_LOGS.SPOTIFY_ARTIST_ID }, false);
    public static final Index IX_ARTISTS_NAME = Internal.createIndex(DSL.name("ix_artists_name"), Artists.ARTISTS, new OrderField[] { Artists.ARTISTS.NAME }, false);
    public static final Index IX_ARTISTS_NAME_TRGM = Internal.createIndex(DSL.name("ix_artists_name_trgm"), Artists.ARTISTS, new OrderField[] { Artists.ARTISTS.NAME }, false);
    public static final Index IX_DANCE_MOVEMENT_FEEDBACK_DANCE_STYLE = Internal.createIndex(DSL.name("ix_dance_movement_feedback_dance_style"), DanceMovementFeedback.DANCE_MOVEMENT_FEEDBACK, new OrderField[] { DanceMovementFeedback.DANCE_MOVEMENT_FEEDBACK.DANCE_STYLE }, false);
    public static final Index IX_DANCE_MOVEMENT_FEEDBACK_MOVEMENT_TAG = Internal.createIndex(DSL.name("ix_dance_movement_feedback_movement_tag"), DanceMovementFeedback.DANCE_MOVEMENT_FEEDBACK, new OrderField[] { DanceMovementFeedback.DANCE_MOVEMENT_FEEDBACK.MOVEMENT_TAG }, false);
    public static final Index IX_DANCE_TRACK_VOTES_DANCE_ID = Internal.createIndex(DSL.name("ix_dance_track_votes_dance_id"), DanceTrackVotes.DANCE_TRACK_VOTES, new OrderField[] { DanceTrackVotes.DANCE_TRACK_VOTES.DANCE_ID }, false);
    public static final Index IX_DANCE_TRACK_VOTES_TRACK_ID = Internal.createIndex(DSL.name("ix_dance_track_votes_track_id"), DanceTrackVotes.DANCE_TRACK_VOTES, new OrderField[] { DanceTrackVotes.DANCE_TRACK_VOTES.TRACK_ID }, false);
    public static final Index IX_GENRE_PROFILES_GENRE_NAME = Internal.createIndex(DSL.name("ix_genre_profiles_genre_name"), GenreProfiles.GENRE_PROFILES, new OrderField[] { GenreProfiles.GENRE_PROFILES.GENRE_NAME }, true);
    public static final Index IX_PENDING_ARTIST_APPROVALS_SPOTIFY_ID = Internal.createIndex(DSL.name("ix_pending_artist_approvals_spotify_id"), PendingArtistApprovals.PENDING_ARTIST_APPROVALS, new OrderField[] { PendingArtistApprovals.PENDING_ARTIST_APPROVALS.SPOTIFY_ID }, false);
    public static final Index IX_PENDING_ARTIST_APPROVALS_STATUS = Internal.createIndex(DSL.name("ix_pending_artist_approvals_status"), PendingArtistApprovals.PENDING_ARTIST_APPROVALS, new OrderField[] { PendingArtistApprovals.PENDING_ARTIST_APPROVALS.STATUS }, false);
    public static final Index IX_PLAYBACK_LINKS_TRACK_PLATFORM_WORKING = Internal.createIndex(DSL.name("ix_playback_links_track_platform_working"), PlaybackLinks.PLAYBACK_LINKS, new OrderField[] { PlaybackLinks.PLAYBACK_LINKS.TRACK_ID, PlaybackLinks.PLAYBACK_LINKS.PLATFORM, PlaybackLinks.PLAYBACK_LINKS.IS_WORKING }, false);
    public static final Index IX_PLAYLIST_TRACKS_PLAYLIST_ID = Internal.createIndex(DSL.name("ix_playlist_tracks_playlist_id"), PlaylistTracks.PLAYLIST_TRACKS, new OrderField[] { PlaylistTracks.PLAYLIST_TRACKS.PLAYLIST_ID }, false);
    public static final Index IX_PLAYLIST_TRACKS_TRACK_ID = Internal.createIndex(DSL.name("ix_playlist_tracks_track_id"), PlaylistTracks.PLAYLIST_TRACKS, new OrderField[] { PlaylistTracks.PLAYLIST_TRACKS.TRACK_ID }, false);
    public static final Index IX_PLAYLISTS_SHARE_TOKEN = Internal.createIndex(DSL.name("ix_playlists_share_token"), Playlists.PLAYLISTS, new OrderField[] { Playlists.PLAYLISTS.SHARE_TOKEN }, true);
    public static final Index IX_PLAYLISTS_USER_ID = Internal.createIndex(DSL.name("ix_playlists_user_id"), Playlists.PLAYLISTS, new OrderField[] { Playlists.PLAYLISTS.USER_ID }, false);
    public static final Index IX_REJECTION_LOGS_ENTITY_TYPE = Internal.createIndex(DSL.name("ix_rejection_logs_entity_type"), RejectionLogs.REJECTION_LOGS, new OrderField[] { RejectionLogs.REJECTION_LOGS.ENTITY_TYPE }, false);
    public static final Index IX_REJECTION_LOGS_SPOTIFY_ID = Internal.createIndex(DSL.name("ix_rejection_logs_spotify_id"), RejectionLogs.REJECTION_LOGS, new OrderField[] { RejectionLogs.REJECTION_LOGS.SPOTIFY_ID }, false);
    public static final Index IX_STYLE_KEYWORDS_KEYWORD = Internal.createIndex(DSL.name("ix_style_keywords_keyword"), StyleKeywords.STYLE_KEYWORDS, new OrderField[] { StyleKeywords.STYLE_KEYWORDS.KEYWORD }, false);
    public static final Index IX_STYLE_KEYWORDS_MAIN_STYLE = Internal.createIndex(DSL.name("ix_style_keywords_main_style"), StyleKeywords.STYLE_KEYWORDS, new OrderField[] { StyleKeywords.STYLE_KEYWORDS.MAIN_STYLE }, false);
    public static final Index IX_TRACK_DANCE_STYLES_CONFIDENCE = Internal.createIndex(DSL.name("ix_track_dance_styles_confidence"), TrackDanceStyles.TRACK_DANCE_STYLES, new OrderField[] { TrackDanceStyles.TRACK_DANCE_STYLES.TRACK_ID, TrackDanceStyles.TRACK_DANCE_STYLES.CONFIDENCE }, false);
    public static final Index IX_TRACK_DANCE_STYLES_DANCE_STYLE = Internal.createIndex(DSL.name("ix_track_dance_styles_dance_style"), TrackDanceStyles.TRACK_DANCE_STYLES, new OrderField[] { TrackDanceStyles.TRACK_DANCE_STYLES.DANCE_STYLE }, false);
    public static final Index IX_TRACK_DANCE_STYLES_SUB_STYLE = Internal.createIndex(DSL.name("ix_track_dance_styles_sub_style"), TrackDanceStyles.TRACK_DANCE_STYLES, new OrderField[] { TrackDanceStyles.TRACK_DANCE_STYLES.SUB_STYLE }, false);
    public static final Index IX_TRACK_FEEL_VOTES_FEEL_TAG = Internal.createIndex(DSL.name("ix_track_feel_votes_feel_tag"), TrackFeelVotes.TRACK_FEEL_VOTES, new OrderField[] { TrackFeelVotes.TRACK_FEEL_VOTES.FEEL_TAG }, false);
    public static final Index IX_TRACK_PLAYBACKS_PLAYED_AT = Internal.createIndex(DSL.name("ix_track_playbacks_played_at"), TrackPlaybacks.TRACK_PLAYBACKS, new OrderField[] { TrackPlaybacks.TRACK_PLAYBACKS.PLAYED_AT }, false);
    public static final Index IX_TRACK_PLAYBACKS_SESSION_ID = Internal.createIndex(DSL.name("ix_track_playbacks_session_id"), TrackPlaybacks.TRACK_PLAYBACKS, new OrderField[] { TrackPlaybacks.TRACK_PLAYBACKS.SESSION_ID }, false);
    public static final Index IX_TRACK_PLAYBACKS_TRACK_ID = Internal.createIndex(DSL.name("ix_track_playbacks_track_id"), TrackPlaybacks.TRACK_PLAYBACKS, new OrderField[] { TrackPlaybacks.TRACK_PLAYBACKS.TRACK_ID }, false);
    public static final Index IX_TRACK_STYLE_VOTES_VOTER_ID = Internal.createIndex(DSL.name("ix_track_style_votes_voter_id"), TrackStyleVotes.TRACK_STYLE_VOTES, new OrderField[] { TrackStyleVotes.TRACK_STYLE_VOTES.VOTER_ID }, false);
    public static final Index IX_TRACKS_ANALYSIS_VERSION = Internal.createIndex(DSL.name("ix_tracks_analysis_version"), Tracks.TRACKS, new OrderField[] { Tracks.TRACKS.ANALYSIS_VERSION }, false);
    public static final Index IX_TRACKS_IS_DANCEABLE = Internal.createIndex(DSL.name("ix_tracks_is_danceable"), Tracks.TRACKS, new OrderField[] { Tracks.TRACKS.IS_DANCEABLE }, false);
    public static final Index IX_TRACKS_IS_FLAGGED = Internal.createIndex(DSL.name("ix_tracks_is_flagged"), Tracks.TRACKS, new OrderField[] { Tracks.TRACKS.IS_FLAGGED }, false);
    public static final Index IX_TRACKS_MUSIC_GENRE = Internal.createIndex(DSL.name("ix_tracks_music_genre"), Tracks.TRACKS, new OrderField[] { Tracks.TRACKS.MUSIC_GENRE }, false);
    public static final Index IX_TRACKS_TITLE = Internal.createIndex(DSL.name("ix_tracks_title"), Tracks.TRACKS, new OrderField[] { Tracks.TRACKS.TITLE }, false);
    public static final Index IX_TRACKS_TITLE_TRGM = Internal.createIndex(DSL.name("ix_tracks_title_trgm"), Tracks.TRACKS, new OrderField[] { Tracks.TRACKS.TITLE }, false);
    public static final Index IX_TRACKS_UPLOADER_ID = Internal.createIndex(DSL.name("ix_tracks_uploader_id"), Tracks.TRACKS, new OrderField[] { Tracks.TRACKS.UPLOADER_ID }, false);
    public static final Index IX_USER_INTERACTIONS_CREATED_AT = Internal.createIndex(DSL.name("ix_user_interactions_created_at"), UserInteractions.USER_INTERACTIONS, new OrderField[] { UserInteractions.USER_INTERACTIONS.CREATED_AT }, false);
    public static final Index IX_USER_INTERACTIONS_EVENT_TYPE = Internal.createIndex(DSL.name("ix_user_interactions_event_type"), UserInteractions.USER_INTERACTIONS, new OrderField[] { UserInteractions.USER_INTERACTIONS.EVENT_TYPE }, false);
    public static final Index IX_USER_INTERACTIONS_SESSION_ID = Internal.createIndex(DSL.name("ix_user_interactions_session_id"), UserInteractions.USER_INTERACTIONS, new OrderField[] { UserInteractions.USER_INTERACTIONS.SESSION_ID }, false);
    public static final Index IX_USER_INTERACTIONS_TRACK_ID = Internal.createIndex(DSL.name("ix_user_interactions_track_id"), UserInteractions.USER_INTERACTIONS, new OrderField[] { UserInteractions.USER_INTERACTIONS.TRACK_ID }, false);
    public static final Index IX_VISITOR_SESSIONS_FIRST_SEEN = Internal.createIndex(DSL.name("ix_visitor_sessions_first_seen"), VisitorSessions.VISITOR_SESSIONS, new OrderField[] { VisitorSessions.VISITOR_SESSIONS.FIRST_SEEN }, false);
    public static final Index IX_VISITOR_SESSIONS_LAST_SEEN = Internal.createIndex(DSL.name("ix_visitor_sessions_last_seen"), VisitorSessions.VISITOR_SESSIONS, new OrderField[] { VisitorSessions.VISITOR_SESSIONS.LAST_SEEN }, false);
    public static final Index IX_VISITOR_SESSIONS_SESSION_ID = Internal.createIndex(DSL.name("ix_visitor_sessions_session_id"), VisitorSessions.VISITOR_SESSIONS, new OrderField[] { VisitorSessions.VISITOR_SESSIONS.SESSION_ID }, true);
    public static final Index PATH_COUNTS_DATE_IDX = Internal.createIndex(DSL.name("path_counts_date_idx"), PathCounts.PATH_COUNTS, new OrderField[] { PathCounts.PATH_COUNTS.DATE }, false);
}
