/*
 * This file is generated by jOOQ.
 */
package se.dansbart.jooq;


import org.jooq.ForeignKey;
import org.jooq.Record;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import se.dansbart.jooq.tables.Albums;
import se.dansbart.jooq.tables.AnalysisSources;
import se.dansbart.jooq.tables.ArtistCrawlLogs;
import se.dansbart.jooq.tables.Artists;
import se.dansbart.jooq.tables.DanceMovementFeedback;
import se.dansbart.jooq.tables.DanceStyleConfig;
import se.dansbart.jooq.tables.FolkwikiTunes;
import se.dansbart.jooq.tables.GenreProfiles;
import se.dansbart.jooq.tables.PendingArtistApprovals;
import se.dansbart.jooq.tables.PlaybackLinks;
import se.dansbart.jooq.tables.PlaylistCollaborators;
import se.dansbart.jooq.tables.PlaylistTracks;
import se.dansbart.jooq.tables.Playlists;
import se.dansbart.jooq.tables.RejectionLogs;
import se.dansbart.jooq.tables.StyleKeywords;
import se.dansbart.jooq.tables.TrackAlbums;
import se.dansbart.jooq.tables.TrackArtists;
import se.dansbart.jooq.tables.TrackDanceStyles;
import se.dansbart.jooq.tables.TrackFeelVotes;
import se.dansbart.jooq.tables.TrackFolkwikiMatches;
import se.dansbart.jooq.tables.TrackPlaybacks;
import se.dansbart.jooq.tables.TrackStructureVersions;
import se.dansbart.jooq.tables.TrackStyleVotes;
import se.dansbart.jooq.tables.Tracks;
import se.dansbart.jooq.tables.UserInteractions;
import se.dansbart.jooq.tables.Users;
import se.dansbart.jooq.tables.VisitorSessions;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<Record> ALBUMS_PKEY = Internal.createUniqueKey(Albums.ALBUMS, DSL.name("albums_pkey"), new TableField[] { Albums.ALBUMS.ID }, true);
    public static final UniqueKey<Record> ANALYSIS_SOURCES_PKEY = Internal.createUniqueKey(AnalysisSources.ANALYSIS_SOURCES, DSL.name("analysis_sources_pkey"), new TableField[] { AnalysisSources.ANALYSIS_SOURCES.ID }, true);
    public static final UniqueKey<Record> ARTIST_CRAWL_LOGS_PKEY = Internal.createUniqueKey(ArtistCrawlLogs.ARTIST_CRAWL_LOGS, DSL.name("artist_crawl_logs_pkey"), new TableField[] { ArtistCrawlLogs.ARTIST_CRAWL_LOGS.ID }, true);
    public static final UniqueKey<Record> UNIQUE_SPOTIFY_ARTIST_CRAWL = Internal.createUniqueKey(ArtistCrawlLogs.ARTIST_CRAWL_LOGS, DSL.name("unique_spotify_artist_crawl"), new TableField[] { ArtistCrawlLogs.ARTIST_CRAWL_LOGS.SPOTIFY_ARTIST_ID }, true);
    public static final UniqueKey<Record> ARTISTS_PKEY = Internal.createUniqueKey(Artists.ARTISTS, DSL.name("artists_pkey"), new TableField[] { Artists.ARTISTS.ID }, true);
    public static final UniqueKey<Record> ARTISTS_SPOTIFY_ID_KEY = Internal.createUniqueKey(Artists.ARTISTS, DSL.name("artists_spotify_id_key"), new TableField[] { Artists.ARTISTS.SPOTIFY_ID }, true);
    public static final UniqueKey<Record> _DANCE_MOVE_UC = Internal.createUniqueKey(DanceMovementFeedback.DANCE_MOVEMENT_FEEDBACK, DSL.name("_dance_move_uc"), new TableField[] { DanceMovementFeedback.DANCE_MOVEMENT_FEEDBACK.DANCE_STYLE, DanceMovementFeedback.DANCE_MOVEMENT_FEEDBACK.MOVEMENT_TAG }, true);
    public static final UniqueKey<Record> DANCE_MOVEMENT_FEEDBACK_PKEY = Internal.createUniqueKey(DanceMovementFeedback.DANCE_MOVEMENT_FEEDBACK, DSL.name("dance_movement_feedback_pkey"), new TableField[] { DanceMovementFeedback.DANCE_MOVEMENT_FEEDBACK.ID }, true);
    public static final UniqueKey<Record> DANCE_STYLE_CONFIG_PKEY = Internal.createUniqueKey(DanceStyleConfig.DANCE_STYLE_CONFIG, DSL.name("dance_style_config_pkey"), new TableField[] { DanceStyleConfig.DANCE_STYLE_CONFIG.ID }, true);
    public static final UniqueKey<Record> FOLKWIKI_TUNES_FOLKWIKI_ID_KEY = Internal.createUniqueKey(FolkwikiTunes.FOLKWIKI_TUNES, DSL.name("folkwiki_tunes_folkwiki_id_key"), new TableField[] { FolkwikiTunes.FOLKWIKI_TUNES.FOLKWIKI_ID }, true);
    public static final UniqueKey<Record> FOLKWIKI_TUNES_PKEY = Internal.createUniqueKey(FolkwikiTunes.FOLKWIKI_TUNES, DSL.name("folkwiki_tunes_pkey"), new TableField[] { FolkwikiTunes.FOLKWIKI_TUNES.ID }, true);
    public static final UniqueKey<Record> GENRE_PROFILES_PKEY = Internal.createUniqueKey(GenreProfiles.GENRE_PROFILES, DSL.name("genre_profiles_pkey"), new TableField[] { GenreProfiles.GENRE_PROFILES.ID }, true);
    public static final UniqueKey<Record> PENDING_ARTIST_APPROVALS_PKEY = Internal.createUniqueKey(PendingArtistApprovals.PENDING_ARTIST_APPROVALS, DSL.name("pending_artist_approvals_pkey"), new TableField[] { PendingArtistApprovals.PENDING_ARTIST_APPROVALS.ID }, true);
    public static final UniqueKey<Record> UNIQUE_PENDING_ARTIST = Internal.createUniqueKey(PendingArtistApprovals.PENDING_ARTIST_APPROVALS, DSL.name("unique_pending_artist"), new TableField[] { PendingArtistApprovals.PENDING_ARTIST_APPROVALS.SPOTIFY_ID }, true);
    public static final UniqueKey<Record> PLAYBACK_LINKS_PKEY = Internal.createUniqueKey(PlaybackLinks.PLAYBACK_LINKS, DSL.name("playback_links_pkey"), new TableField[] { PlaybackLinks.PLAYBACK_LINKS.ID }, true);
    public static final UniqueKey<Record> PLAYLIST_COLLABORATORS_PKEY = Internal.createUniqueKey(PlaylistCollaborators.PLAYLIST_COLLABORATORS, DSL.name("playlist_collaborators_pkey"), new TableField[] { PlaylistCollaborators.PLAYLIST_COLLABORATORS.ID }, true);
    public static final UniqueKey<Record> UNIQUE_PLAYLIST_USER_COLLABORATION = Internal.createUniqueKey(PlaylistCollaborators.PLAYLIST_COLLABORATORS, DSL.name("unique_playlist_user_collaboration"), new TableField[] { PlaylistCollaborators.PLAYLIST_COLLABORATORS.PLAYLIST_ID, PlaylistCollaborators.PLAYLIST_COLLABORATORS.USER_ID }, true);
    public static final UniqueKey<Record> PLAYLIST_TRACKS_PKEY = Internal.createUniqueKey(PlaylistTracks.PLAYLIST_TRACKS, DSL.name("playlist_tracks_pkey"), new TableField[] { PlaylistTracks.PLAYLIST_TRACKS.ID }, true);
    public static final UniqueKey<Record> UQ_PLAYLIST_TRACK = Internal.createUniqueKey(PlaylistTracks.PLAYLIST_TRACKS, DSL.name("uq_playlist_track"), new TableField[] { PlaylistTracks.PLAYLIST_TRACKS.PLAYLIST_ID, PlaylistTracks.PLAYLIST_TRACKS.TRACK_ID }, true);
    public static final UniqueKey<Record> PLAYLISTS_PKEY = Internal.createUniqueKey(Playlists.PLAYLISTS, DSL.name("playlists_pkey"), new TableField[] { Playlists.PLAYLISTS.ID }, true);
    public static final UniqueKey<Record> REJECTION_LOGS_PKEY = Internal.createUniqueKey(RejectionLogs.REJECTION_LOGS, DSL.name("rejection_logs_pkey"), new TableField[] { RejectionLogs.REJECTION_LOGS.ID }, true);
    public static final UniqueKey<Record> UNIQUE_REJECTION = Internal.createUniqueKey(RejectionLogs.REJECTION_LOGS, DSL.name("unique_rejection"), new TableField[] { RejectionLogs.REJECTION_LOGS.SPOTIFY_ID, RejectionLogs.REJECTION_LOGS.ENTITY_TYPE }, true);
    public static final UniqueKey<Record> STYLE_KEYWORDS_PKEY = Internal.createUniqueKey(StyleKeywords.STYLE_KEYWORDS, DSL.name("style_keywords_pkey"), new TableField[] { StyleKeywords.STYLE_KEYWORDS.ID }, true);
    public static final UniqueKey<Record> UNIQUE_KEYWORD = Internal.createUniqueKey(StyleKeywords.STYLE_KEYWORDS, DSL.name("unique_keyword"), new TableField[] { StyleKeywords.STYLE_KEYWORDS.KEYWORD }, true);
    public static final UniqueKey<Record> TRACK_ALBUMS_PKEY = Internal.createUniqueKey(TrackAlbums.TRACK_ALBUMS, DSL.name("track_albums_pkey"), new TableField[] { TrackAlbums.TRACK_ALBUMS.ID }, true);
    public static final UniqueKey<Record> UNIQUE_TRACK_ALBUM = Internal.createUniqueKey(TrackAlbums.TRACK_ALBUMS, DSL.name("unique_track_album"), new TableField[] { TrackAlbums.TRACK_ALBUMS.TRACK_ID, TrackAlbums.TRACK_ALBUMS.ALBUM_ID }, true);
    public static final UniqueKey<Record> TRACK_ARTISTS_PKEY = Internal.createUniqueKey(TrackArtists.TRACK_ARTISTS, DSL.name("track_artists_pkey"), new TableField[] { TrackArtists.TRACK_ARTISTS.ID }, true);
    public static final UniqueKey<Record> UNIQUE_TRACK_ARTIST = Internal.createUniqueKey(TrackArtists.TRACK_ARTISTS, DSL.name("unique_track_artist"), new TableField[] { TrackArtists.TRACK_ARTISTS.TRACK_ID, TrackArtists.TRACK_ARTISTS.ARTIST_ID }, true);
    public static final UniqueKey<Record> TRACK_DANCE_STYLES_PKEY = Internal.createUniqueKey(TrackDanceStyles.TRACK_DANCE_STYLES, DSL.name("track_dance_styles_pkey"), new TableField[] { TrackDanceStyles.TRACK_DANCE_STYLES.ID }, true);
    public static final UniqueKey<Record> TRACK_FEEL_VOTES_PKEY = Internal.createUniqueKey(TrackFeelVotes.TRACK_FEEL_VOTES, DSL.name("track_feel_votes_pkey"), new TableField[] { TrackFeelVotes.TRACK_FEEL_VOTES.ID }, true);
    public static final UniqueKey<Record> TRACK_FOLKWIKI_MATCHES_PKEY = Internal.createUniqueKey(TrackFolkwikiMatches.TRACK_FOLKWIKI_MATCHES, DSL.name("track_folkwiki_matches_pkey"), new TableField[] { TrackFolkwikiMatches.TRACK_FOLKWIKI_MATCHES.TRACK_ID, TrackFolkwikiMatches.TRACK_FOLKWIKI_MATCHES.FOLKWIKI_TUNE_ID }, true);
    public static final UniqueKey<Record> TRACK_PLAYBACKS_PKEY = Internal.createUniqueKey(TrackPlaybacks.TRACK_PLAYBACKS, DSL.name("track_playbacks_pkey"), new TableField[] { TrackPlaybacks.TRACK_PLAYBACKS.ID }, true);
    public static final UniqueKey<Record> TRACK_STRUCTURE_VERSIONS_PKEY = Internal.createUniqueKey(TrackStructureVersions.TRACK_STRUCTURE_VERSIONS, DSL.name("track_structure_versions_pkey"), new TableField[] { TrackStructureVersions.TRACK_STRUCTURE_VERSIONS.ID }, true);
    public static final UniqueKey<Record> TRACK_STYLE_VOTES_PKEY = Internal.createUniqueKey(TrackStyleVotes.TRACK_STYLE_VOTES, DSL.name("track_style_votes_pkey"), new TableField[] { TrackStyleVotes.TRACK_STYLE_VOTES.ID }, true);
    public static final UniqueKey<Record> TRACKS_PKEY = Internal.createUniqueKey(Tracks.TRACKS, DSL.name("tracks_pkey"), new TableField[] { Tracks.TRACKS.ID }, true);
    public static final UniqueKey<Record> USER_INTERACTIONS_PKEY = Internal.createUniqueKey(UserInteractions.USER_INTERACTIONS, DSL.name("user_interactions_pkey"), new TableField[] { UserInteractions.USER_INTERACTIONS.ID }, true);
    public static final UniqueKey<Record> USERS_DISCOURSE_ID_KEY = Internal.createUniqueKey(Users.USERS, DSL.name("users_discourse_id_key"), new TableField[] { Users.USERS.DISCOURSE_ID }, true);
    public static final UniqueKey<Record> USERS_PKEY = Internal.createUniqueKey(Users.USERS, DSL.name("users_pkey"), new TableField[] { Users.USERS.ID }, true);
    public static final UniqueKey<Record> VISITOR_SESSIONS_PKEY = Internal.createUniqueKey(VisitorSessions.VISITOR_SESSIONS, DSL.name("visitor_sessions_pkey"), new TableField[] { VisitorSessions.VISITOR_SESSIONS.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<Record, Record> ALBUMS__ALBUMS_ARTIST_ID_FKEY = Internal.createForeignKey(Albums.ALBUMS, DSL.name("albums_artist_id_fkey"), new TableField[] { Albums.ALBUMS.ARTIST_ID }, Keys.ARTISTS_PKEY, new TableField[] { Artists.ARTISTS.ID }, true);
    public static final ForeignKey<Record, Record> ANALYSIS_SOURCES__ANALYSIS_SOURCES_TRACK_ID_FKEY = Internal.createForeignKey(AnalysisSources.ANALYSIS_SOURCES, DSL.name("analysis_sources_track_id_fkey"), new TableField[] { AnalysisSources.ANALYSIS_SOURCES.TRACK_ID }, Keys.TRACKS_PKEY, new TableField[] { Tracks.TRACKS.ID }, true);
    public static final ForeignKey<Record, Record> PLAYBACK_LINKS__PLAYBACK_LINKS_TRACK_ID_FKEY = Internal.createForeignKey(PlaybackLinks.PLAYBACK_LINKS, DSL.name("playback_links_track_id_fkey"), new TableField[] { PlaybackLinks.PLAYBACK_LINKS.TRACK_ID }, Keys.TRACKS_PKEY, new TableField[] { Tracks.TRACKS.ID }, true);
    public static final ForeignKey<Record, Record> PLAYLIST_COLLABORATORS__PLAYLIST_COLLABORATORS_INVITED_BY_FKEY = Internal.createForeignKey(PlaylistCollaborators.PLAYLIST_COLLABORATORS, DSL.name("playlist_collaborators_invited_by_fkey"), new TableField[] { PlaylistCollaborators.PLAYLIST_COLLABORATORS.INVITED_BY }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<Record, Record> PLAYLIST_COLLABORATORS__PLAYLIST_COLLABORATORS_PLAYLIST_ID_FKEY = Internal.createForeignKey(PlaylistCollaborators.PLAYLIST_COLLABORATORS, DSL.name("playlist_collaborators_playlist_id_fkey"), new TableField[] { PlaylistCollaborators.PLAYLIST_COLLABORATORS.PLAYLIST_ID }, Keys.PLAYLISTS_PKEY, new TableField[] { Playlists.PLAYLISTS.ID }, true);
    public static final ForeignKey<Record, Record> PLAYLIST_COLLABORATORS__PLAYLIST_COLLABORATORS_USER_ID_FKEY = Internal.createForeignKey(PlaylistCollaborators.PLAYLIST_COLLABORATORS, DSL.name("playlist_collaborators_user_id_fkey"), new TableField[] { PlaylistCollaborators.PLAYLIST_COLLABORATORS.USER_ID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<Record, Record> PLAYLIST_TRACKS__PLAYLIST_TRACKS_PLAYLIST_ID_FKEY = Internal.createForeignKey(PlaylistTracks.PLAYLIST_TRACKS, DSL.name("playlist_tracks_playlist_id_fkey"), new TableField[] { PlaylistTracks.PLAYLIST_TRACKS.PLAYLIST_ID }, Keys.PLAYLISTS_PKEY, new TableField[] { Playlists.PLAYLISTS.ID }, true);
    public static final ForeignKey<Record, Record> PLAYLIST_TRACKS__PLAYLIST_TRACKS_TRACK_ID_FKEY = Internal.createForeignKey(PlaylistTracks.PLAYLIST_TRACKS, DSL.name("playlist_tracks_track_id_fkey"), new TableField[] { PlaylistTracks.PLAYLIST_TRACKS.TRACK_ID }, Keys.TRACKS_PKEY, new TableField[] { Tracks.TRACKS.ID }, true);
    public static final ForeignKey<Record, Record> PLAYLISTS__PLAYLISTS_USER_ID_FKEY = Internal.createForeignKey(Playlists.PLAYLISTS, DSL.name("playlists_user_id_fkey"), new TableField[] { Playlists.PLAYLISTS.USER_ID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<Record, Record> TRACK_ALBUMS__TRACK_ALBUMS_ALBUM_ID_FKEY = Internal.createForeignKey(TrackAlbums.TRACK_ALBUMS, DSL.name("track_albums_album_id_fkey"), new TableField[] { TrackAlbums.TRACK_ALBUMS.ALBUM_ID }, Keys.ALBUMS_PKEY, new TableField[] { Albums.ALBUMS.ID }, true);
    public static final ForeignKey<Record, Record> TRACK_ALBUMS__TRACK_ALBUMS_TRACK_ID_FKEY = Internal.createForeignKey(TrackAlbums.TRACK_ALBUMS, DSL.name("track_albums_track_id_fkey"), new TableField[] { TrackAlbums.TRACK_ALBUMS.TRACK_ID }, Keys.TRACKS_PKEY, new TableField[] { Tracks.TRACKS.ID }, true);
    public static final ForeignKey<Record, Record> TRACK_ARTISTS__TRACK_ARTISTS_ARTIST_ID_FKEY = Internal.createForeignKey(TrackArtists.TRACK_ARTISTS, DSL.name("track_artists_artist_id_fkey"), new TableField[] { TrackArtists.TRACK_ARTISTS.ARTIST_ID }, Keys.ARTISTS_PKEY, new TableField[] { Artists.ARTISTS.ID }, true);
    public static final ForeignKey<Record, Record> TRACK_ARTISTS__TRACK_ARTISTS_TRACK_ID_FKEY = Internal.createForeignKey(TrackArtists.TRACK_ARTISTS, DSL.name("track_artists_track_id_fkey"), new TableField[] { TrackArtists.TRACK_ARTISTS.TRACK_ID }, Keys.TRACKS_PKEY, new TableField[] { Tracks.TRACKS.ID }, true);
    public static final ForeignKey<Record, Record> TRACK_DANCE_STYLES__TRACK_DANCE_STYLES_TRACK_ID_FKEY = Internal.createForeignKey(TrackDanceStyles.TRACK_DANCE_STYLES, DSL.name("track_dance_styles_track_id_fkey"), new TableField[] { TrackDanceStyles.TRACK_DANCE_STYLES.TRACK_ID }, Keys.TRACKS_PKEY, new TableField[] { Tracks.TRACKS.ID }, true);
    public static final ForeignKey<Record, Record> TRACK_FEEL_VOTES__TRACK_FEEL_VOTES_TRACK_ID_FKEY = Internal.createForeignKey(TrackFeelVotes.TRACK_FEEL_VOTES, DSL.name("track_feel_votes_track_id_fkey"), new TableField[] { TrackFeelVotes.TRACK_FEEL_VOTES.TRACK_ID }, Keys.TRACKS_PKEY, new TableField[] { Tracks.TRACKS.ID }, true);
    public static final ForeignKey<Record, Record> TRACK_FOLKWIKI_MATCHES__TRACK_FOLKWIKI_MATCHES_FOLKWIKI_TUNE_ID_FKEY = Internal.createForeignKey(TrackFolkwikiMatches.TRACK_FOLKWIKI_MATCHES, DSL.name("track_folkwiki_matches_folkwiki_tune_id_fkey"), new TableField[] { TrackFolkwikiMatches.TRACK_FOLKWIKI_MATCHES.FOLKWIKI_TUNE_ID }, Keys.FOLKWIKI_TUNES_PKEY, new TableField[] { FolkwikiTunes.FOLKWIKI_TUNES.ID }, true);
    public static final ForeignKey<Record, Record> TRACK_FOLKWIKI_MATCHES__TRACK_FOLKWIKI_MATCHES_TRACK_ID_FKEY = Internal.createForeignKey(TrackFolkwikiMatches.TRACK_FOLKWIKI_MATCHES, DSL.name("track_folkwiki_matches_track_id_fkey"), new TableField[] { TrackFolkwikiMatches.TRACK_FOLKWIKI_MATCHES.TRACK_ID }, Keys.TRACKS_PKEY, new TableField[] { Tracks.TRACKS.ID }, true);
    public static final ForeignKey<Record, Record> TRACK_PLAYBACKS__TRACK_PLAYBACKS_TRACK_ID_FKEY = Internal.createForeignKey(TrackPlaybacks.TRACK_PLAYBACKS, DSL.name("track_playbacks_track_id_fkey"), new TableField[] { TrackPlaybacks.TRACK_PLAYBACKS.TRACK_ID }, Keys.TRACKS_PKEY, new TableField[] { Tracks.TRACKS.ID }, true);
    public static final ForeignKey<Record, Record> TRACK_STRUCTURE_VERSIONS__TRACK_STRUCTURE_VERSIONS_TRACK_ID_FKEY = Internal.createForeignKey(TrackStructureVersions.TRACK_STRUCTURE_VERSIONS, DSL.name("track_structure_versions_track_id_fkey"), new TableField[] { TrackStructureVersions.TRACK_STRUCTURE_VERSIONS.TRACK_ID }, Keys.TRACKS_PKEY, new TableField[] { Tracks.TRACKS.ID }, true);
    public static final ForeignKey<Record, Record> TRACK_STYLE_VOTES__TRACK_STYLE_VOTES_TRACK_ID_FKEY = Internal.createForeignKey(TrackStyleVotes.TRACK_STYLE_VOTES, DSL.name("track_style_votes_track_id_fkey"), new TableField[] { TrackStyleVotes.TRACK_STYLE_VOTES.TRACK_ID }, Keys.TRACKS_PKEY, new TableField[] { Tracks.TRACKS.ID }, true);
    public static final ForeignKey<Record, Record> TRACKS__TRACKS_UPLOADER_ID_FKEY = Internal.createForeignKey(Tracks.TRACKS, DSL.name("tracks_uploader_id_fkey"), new TableField[] { Tracks.TRACKS.UPLOADER_ID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<Record, Record> USER_INTERACTIONS__USER_INTERACTIONS_TRACK_ID_FKEY = Internal.createForeignKey(UserInteractions.USER_INTERACTIONS, DSL.name("user_interactions_track_id_fkey"), new TableField[] { UserInteractions.USER_INTERACTIONS.TRACK_ID }, Keys.TRACKS_PKEY, new TableField[] { Tracks.TRACKS.ID }, true);
    public static final ForeignKey<Record, Record> VISITOR_SESSIONS__VISITOR_SESSIONS_USER_ID_FKEY = Internal.createForeignKey(VisitorSessions.VISITOR_SESSIONS, DSL.name("visitor_sessions_user_id_fkey"), new TableField[] { VisitorSessions.VISITOR_SESSIONS.USER_ID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
}
