/*
 * This file is generated by jOOQ.
 */
package se.dansbart.jooq;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import se.dansbart.jooq.tables.Albums;
import se.dansbart.jooq.tables.AnalysisSources;
import se.dansbart.jooq.tables.ArtistCrawlLogs;
import se.dansbart.jooq.tables.Artists;
import se.dansbart.jooq.tables.DanceMovementFeedback;
import se.dansbart.jooq.tables.DanceStyleConfig;
import se.dansbart.jooq.tables.DanceTrackVotes;
import se.dansbart.jooq.tables.DanceTracks;
import se.dansbart.jooq.tables.Dances;
import se.dansbart.jooq.tables.FolkwikiTunes;
import se.dansbart.jooq.tables.GenreProfiles;
import se.dansbart.jooq.tables.PathCounts;
import se.dansbart.jooq.tables.PendingArtistApprovals;
import se.dansbart.jooq.tables.PlaybackLinks;
import se.dansbart.jooq.tables.PlaylistCollaborators;
import se.dansbart.jooq.tables.PlaylistTracks;
import se.dansbart.jooq.tables.Playlists;
import se.dansbart.jooq.tables.RejectionLogs;
import se.dansbart.jooq.tables.StyleKeywords;
import se.dansbart.jooq.tables.TrackAlbums;
import se.dansbart.jooq.tables.TrackArtists;
import se.dansbart.jooq.tables.TrackDanceStyles;
import se.dansbart.jooq.tables.TrackFeelVotes;
import se.dansbart.jooq.tables.TrackFolkwikiMatches;
import se.dansbart.jooq.tables.TrackPlaybacks;
import se.dansbart.jooq.tables.TrackStructureVersions;
import se.dansbart.jooq.tables.TrackStyleVotes;
import se.dansbart.jooq.tables.Tracks;
import se.dansbart.jooq.tables.UserInteractions;
import se.dansbart.jooq.tables.Users;
import se.dansbart.jooq.tables.VisitorSessions;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.albums</code>.
     */
    public final Albums ALBUMS = Albums.ALBUMS;

    /**
     * The table <code>public.analysis_sources</code>.
     */
    public final AnalysisSources ANALYSIS_SOURCES = AnalysisSources.ANALYSIS_SOURCES;

    /**
     * The table <code>public.artist_crawl_logs</code>.
     */
    public final ArtistCrawlLogs ARTIST_CRAWL_LOGS = ArtistCrawlLogs.ARTIST_CRAWL_LOGS;

    /**
     * The table <code>public.artists</code>.
     */
    public final Artists ARTISTS = Artists.ARTISTS;

    /**
     * The table <code>public.dance_movement_feedback</code>.
     */
    public final DanceMovementFeedback DANCE_MOVEMENT_FEEDBACK = DanceMovementFeedback.DANCE_MOVEMENT_FEEDBACK;

    /**
     * The table <code>public.dance_style_config</code>.
     */
    public final DanceStyleConfig DANCE_STYLE_CONFIG = DanceStyleConfig.DANCE_STYLE_CONFIG;

    /**
     * The table <code>public.dance_track_votes</code>.
     */
    public final DanceTrackVotes DANCE_TRACK_VOTES = DanceTrackVotes.DANCE_TRACK_VOTES;

    /**
     * The table <code>public.dance_tracks</code>.
     */
    public final DanceTracks DANCE_TRACKS = DanceTracks.DANCE_TRACKS;

    /**
     * The table <code>public.dances</code>.
     */
    public final Dances DANCES = Dances.DANCES;

    /**
     * The table <code>public.folkwiki_tunes</code>.
     */
    public final FolkwikiTunes FOLKWIKI_TUNES = FolkwikiTunes.FOLKWIKI_TUNES;

    /**
     * The table <code>public.genre_profiles</code>.
     */
    public final GenreProfiles GENRE_PROFILES = GenreProfiles.GENRE_PROFILES;

    /**
     * The table <code>public.path_counts</code>.
     */
    public final PathCounts PATH_COUNTS = PathCounts.PATH_COUNTS;

    /**
     * The table <code>public.pending_artist_approvals</code>.
     */
    public final PendingArtistApprovals PENDING_ARTIST_APPROVALS = PendingArtistApprovals.PENDING_ARTIST_APPROVALS;

    /**
     * The table <code>public.playback_links</code>.
     */
    public final PlaybackLinks PLAYBACK_LINKS = PlaybackLinks.PLAYBACK_LINKS;

    /**
     * The table <code>public.playlist_collaborators</code>.
     */
    public final PlaylistCollaborators PLAYLIST_COLLABORATORS = PlaylistCollaborators.PLAYLIST_COLLABORATORS;

    /**
     * The table <code>public.playlist_tracks</code>.
     */
    public final PlaylistTracks PLAYLIST_TRACKS = PlaylistTracks.PLAYLIST_TRACKS;

    /**
     * The table <code>public.playlists</code>.
     */
    public final Playlists PLAYLISTS = Playlists.PLAYLISTS;

    /**
     * The table <code>public.rejection_logs</code>.
     */
    public final RejectionLogs REJECTION_LOGS = RejectionLogs.REJECTION_LOGS;

    /**
     * The table <code>public.style_keywords</code>.
     */
    public final StyleKeywords STYLE_KEYWORDS = StyleKeywords.STYLE_KEYWORDS;

    /**
     * The table <code>public.track_albums</code>.
     */
    public final TrackAlbums TRACK_ALBUMS = TrackAlbums.TRACK_ALBUMS;

    /**
     * The table <code>public.track_artists</code>.
     */
    public final TrackArtists TRACK_ARTISTS = TrackArtists.TRACK_ARTISTS;

    /**
     * The table <code>public.track_dance_styles</code>.
     */
    public final TrackDanceStyles TRACK_DANCE_STYLES = TrackDanceStyles.TRACK_DANCE_STYLES;

    /**
     * The table <code>public.track_feel_votes</code>.
     */
    public final TrackFeelVotes TRACK_FEEL_VOTES = TrackFeelVotes.TRACK_FEEL_VOTES;

    /**
     * The table <code>public.track_folkwiki_matches</code>.
     */
    public final TrackFolkwikiMatches TRACK_FOLKWIKI_MATCHES = TrackFolkwikiMatches.TRACK_FOLKWIKI_MATCHES;

    /**
     * The table <code>public.track_playbacks</code>.
     */
    public final TrackPlaybacks TRACK_PLAYBACKS = TrackPlaybacks.TRACK_PLAYBACKS;

    /**
     * The table <code>public.track_structure_versions</code>.
     */
    public final TrackStructureVersions TRACK_STRUCTURE_VERSIONS = TrackStructureVersions.TRACK_STRUCTURE_VERSIONS;

    /**
     * The table <code>public.track_style_votes</code>.
     */
    public final TrackStyleVotes TRACK_STYLE_VOTES = TrackStyleVotes.TRACK_STYLE_VOTES;

    /**
     * The table <code>public.tracks</code>.
     */
    public final Tracks TRACKS = Tracks.TRACKS;

    /**
     * The table <code>public.user_interactions</code>.
     */
    public final UserInteractions USER_INTERACTIONS = UserInteractions.USER_INTERACTIONS;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * The table <code>public.visitor_sessions</code>.
     */
    public final VisitorSessions VISITOR_SESSIONS = VisitorSessions.VISITOR_SESSIONS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Albums.ALBUMS,
            AnalysisSources.ANALYSIS_SOURCES,
            ArtistCrawlLogs.ARTIST_CRAWL_LOGS,
            Artists.ARTISTS,
            DanceMovementFeedback.DANCE_MOVEMENT_FEEDBACK,
            DanceStyleConfig.DANCE_STYLE_CONFIG,
            DanceTrackVotes.DANCE_TRACK_VOTES,
            DanceTracks.DANCE_TRACKS,
            Dances.DANCES,
            FolkwikiTunes.FOLKWIKI_TUNES,
            GenreProfiles.GENRE_PROFILES,
            PathCounts.PATH_COUNTS,
            PendingArtistApprovals.PENDING_ARTIST_APPROVALS,
            PlaybackLinks.PLAYBACK_LINKS,
            PlaylistCollaborators.PLAYLIST_COLLABORATORS,
            PlaylistTracks.PLAYLIST_TRACKS,
            Playlists.PLAYLISTS,
            RejectionLogs.REJECTION_LOGS,
            StyleKeywords.STYLE_KEYWORDS,
            TrackAlbums.TRACK_ALBUMS,
            TrackArtists.TRACK_ARTISTS,
            TrackDanceStyles.TRACK_DANCE_STYLES,
            TrackFeelVotes.TRACK_FEEL_VOTES,
            TrackFolkwikiMatches.TRACK_FOLKWIKI_MATCHES,
            TrackPlaybacks.TRACK_PLAYBACKS,
            TrackStructureVersions.TRACK_STRUCTURE_VERSIONS,
            TrackStyleVotes.TRACK_STYLE_VOTES,
            Tracks.TRACKS,
            UserInteractions.USER_INTERACTIONS,
            Users.USERS,
            VisitorSessions.VISITOR_SESSIONS
        );
    }
}
