/*
 * This file is generated by jOOQ.
 */
package se.dansbart.jooq;


import se.dansbart.jooq.tables.Albums;
import se.dansbart.jooq.tables.AnalysisSources;
import se.dansbart.jooq.tables.ArtistCrawlLogs;
import se.dansbart.jooq.tables.Artists;
import se.dansbart.jooq.tables.DanceMovementFeedback;
import se.dansbart.jooq.tables.DanceStyleConfig;
import se.dansbart.jooq.tables.DanceTracks;
import se.dansbart.jooq.tables.Dances;
import se.dansbart.jooq.tables.FolkwikiTunes;
import se.dansbart.jooq.tables.GenreProfiles;
import se.dansbart.jooq.tables.PathCounts;
import se.dansbart.jooq.tables.PendingArtistApprovals;
import se.dansbart.jooq.tables.PlaybackLinks;
import se.dansbart.jooq.tables.PlaylistCollaborators;
import se.dansbart.jooq.tables.PlaylistTracks;
import se.dansbart.jooq.tables.Playlists;
import se.dansbart.jooq.tables.RejectionLogs;
import se.dansbart.jooq.tables.StyleKeywords;
import se.dansbart.jooq.tables.TrackAlbums;
import se.dansbart.jooq.tables.TrackArtists;
import se.dansbart.jooq.tables.TrackDanceStyles;
import se.dansbart.jooq.tables.TrackFeelVotes;
import se.dansbart.jooq.tables.TrackFolkwikiMatches;
import se.dansbart.jooq.tables.TrackPlaybacks;
import se.dansbart.jooq.tables.TrackStructureVersions;
import se.dansbart.jooq.tables.TrackStyleVotes;
import se.dansbart.jooq.tables.Tracks;
import se.dansbart.jooq.tables.UserInteractions;
import se.dansbart.jooq.tables.Users;
import se.dansbart.jooq.tables.VisitorSessions;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.albums</code>.
     */
    public static final Albums ALBUMS = Albums.ALBUMS;

    /**
     * The table <code>public.analysis_sources</code>.
     */
    public static final AnalysisSources ANALYSIS_SOURCES = AnalysisSources.ANALYSIS_SOURCES;

    /**
     * The table <code>public.artist_crawl_logs</code>.
     */
    public static final ArtistCrawlLogs ARTIST_CRAWL_LOGS = ArtistCrawlLogs.ARTIST_CRAWL_LOGS;

    /**
     * The table <code>public.artists</code>.
     */
    public static final Artists ARTISTS = Artists.ARTISTS;

    /**
     * The table <code>public.dance_movement_feedback</code>.
     */
    public static final DanceMovementFeedback DANCE_MOVEMENT_FEEDBACK = DanceMovementFeedback.DANCE_MOVEMENT_FEEDBACK;

    /**
     * The table <code>public.dance_style_config</code>.
     */
    public static final DanceStyleConfig DANCE_STYLE_CONFIG = DanceStyleConfig.DANCE_STYLE_CONFIG;

    /**
     * The table <code>public.dance_tracks</code>.
     */
    public static final DanceTracks DANCE_TRACKS = DanceTracks.DANCE_TRACKS;

    /**
     * The table <code>public.dances</code>.
     */
    public static final Dances DANCES = Dances.DANCES;

    /**
     * The table <code>public.folkwiki_tunes</code>.
     */
    public static final FolkwikiTunes FOLKWIKI_TUNES = FolkwikiTunes.FOLKWIKI_TUNES;

    /**
     * The table <code>public.genre_profiles</code>.
     */
    public static final GenreProfiles GENRE_PROFILES = GenreProfiles.GENRE_PROFILES;

    /**
     * The table <code>public.path_counts</code>.
     */
    public static final PathCounts PATH_COUNTS = PathCounts.PATH_COUNTS;

    /**
     * The table <code>public.pending_artist_approvals</code>.
     */
    public static final PendingArtistApprovals PENDING_ARTIST_APPROVALS = PendingArtistApprovals.PENDING_ARTIST_APPROVALS;

    /**
     * The table <code>public.playback_links</code>.
     */
    public static final PlaybackLinks PLAYBACK_LINKS = PlaybackLinks.PLAYBACK_LINKS;

    /**
     * The table <code>public.playlist_collaborators</code>.
     */
    public static final PlaylistCollaborators PLAYLIST_COLLABORATORS = PlaylistCollaborators.PLAYLIST_COLLABORATORS;

    /**
     * The table <code>public.playlist_tracks</code>.
     */
    public static final PlaylistTracks PLAYLIST_TRACKS = PlaylistTracks.PLAYLIST_TRACKS;

    /**
     * The table <code>public.playlists</code>.
     */
    public static final Playlists PLAYLISTS = Playlists.PLAYLISTS;

    /**
     * The table <code>public.rejection_logs</code>.
     */
    public static final RejectionLogs REJECTION_LOGS = RejectionLogs.REJECTION_LOGS;

    /**
     * The table <code>public.style_keywords</code>.
     */
    public static final StyleKeywords STYLE_KEYWORDS = StyleKeywords.STYLE_KEYWORDS;

    /**
     * The table <code>public.track_albums</code>.
     */
    public static final TrackAlbums TRACK_ALBUMS = TrackAlbums.TRACK_ALBUMS;

    /**
     * The table <code>public.track_artists</code>.
     */
    public static final TrackArtists TRACK_ARTISTS = TrackArtists.TRACK_ARTISTS;

    /**
     * The table <code>public.track_dance_styles</code>.
     */
    public static final TrackDanceStyles TRACK_DANCE_STYLES = TrackDanceStyles.TRACK_DANCE_STYLES;

    /**
     * The table <code>public.track_feel_votes</code>.
     */
    public static final TrackFeelVotes TRACK_FEEL_VOTES = TrackFeelVotes.TRACK_FEEL_VOTES;

    /**
     * The table <code>public.track_folkwiki_matches</code>.
     */
    public static final TrackFolkwikiMatches TRACK_FOLKWIKI_MATCHES = TrackFolkwikiMatches.TRACK_FOLKWIKI_MATCHES;

    /**
     * The table <code>public.track_playbacks</code>.
     */
    public static final TrackPlaybacks TRACK_PLAYBACKS = TrackPlaybacks.TRACK_PLAYBACKS;

    /**
     * The table <code>public.track_structure_versions</code>.
     */
    public static final TrackStructureVersions TRACK_STRUCTURE_VERSIONS = TrackStructureVersions.TRACK_STRUCTURE_VERSIONS;

    /**
     * The table <code>public.track_style_votes</code>.
     */
    public static final TrackStyleVotes TRACK_STYLE_VOTES = TrackStyleVotes.TRACK_STYLE_VOTES;

    /**
     * The table <code>public.tracks</code>.
     */
    public static final Tracks TRACKS = Tracks.TRACKS;

    /**
     * The table <code>public.user_interactions</code>.
     */
    public static final UserInteractions USER_INTERACTIONS = UserInteractions.USER_INTERACTIONS;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;

    /**
     * The table <code>public.visitor_sessions</code>.
     */
    public static final VisitorSessions VISITOR_SESSIONS = VisitorSessions.VISITOR_SESSIONS;
}
