import { ref, onMounted, computed } from 'vue';
import { useAuth } from '../hooks/useAuth';
import { showError, showToast } from '../hooks/useToast';
import type { UserPublicProfile } from '../api/models/userPublicProfile';

export default {
  name: 'ProfilePage',

  setup() {
    const { user, fetchWithAuth } = useAuth();
    const username = ref('');
    const displayName = ref('');
    const usernameError = ref('');
    const isCheckingUsername = ref(false);
    const isSaving = ref(false);
    const usernameAvailable = ref(null);

    // Backend may return username/display_name; generated type has displayName only
    const profile = computed(() => {
      const u = user.value;
      if (!u) return null;
      const uu = u as UserPublicProfile & { username?: string; display_name?: string };
      return {
        username: uu.username ?? '',
        displayName: uu.displayName ?? uu.display_name ?? '',
      };
    });

    // Check if username is auto-generated
    const isAutoGeneratedUsername = computed(() => {
      return profile.value?.username?.startsWith('user_');
    });

    onMounted(() => {
      if (profile.value) {
        username.value = profile.value.username || '';
        displayName.value = profile.value.displayName || '';
      }
    });

    // Validate username format
    function validateUsernameFormat(value) {
      if (!value) {
        return 'Användarnamn krävs';
      }

      if (value.length < 3) {
        return 'Användarnamn måste vara minst 3 tecken';
      }

      if (value.length > 50) {
        return 'Användarnamn får vara max 50 tecken';
      }

      if (!/^[a-zA-Z0-9_]+$/.test(value)) {
        return 'Endast bokstäver, siffror och _ tillåts';
      }

      return null;
    }

    // Check username availability
    let checkTimeout;
    async function checkUsernameAvailability() {
      const formatError = validateUsernameFormat(username.value);
      if (formatError) {
        usernameError.value = formatError;
        usernameAvailable.value = false;
        return;
      }

      // Don't check if it's the same as current username
      if (username.value === profile.value?.username) {
        usernameError.value = '';
        usernameAvailable.value = true;
        return;
      }

      // Debounce the API call
      clearTimeout(checkTimeout);
      checkTimeout = setTimeout(async () => {
        isCheckingUsername.value = true;
        usernameError.value = '';

        try {
          const response = await fetchWithAuth(
            `/api/users/username/available?username=${encodeURIComponent(username.value)}`
          );

          if (response.ok) {
            const data = await response.json();
            usernameAvailable.value = data.available;

            if (!data.available) {
              usernameError.value = `Användarnamnet "${username.value}" är redan taget`;
            }
          }
        } catch (error) {
          console.error('Error checking username:', error);
        } finally {
          isCheckingUsername.value = false;
        }
      }, 500);
    }

    // Save profile
    async function saveProfile() {
      const formatError = validateUsernameFormat(username.value);
      if (formatError) {
        usernameError.value = formatError;
        return;
      }

      if (usernameAvailable.value === false) {
        usernameError.value = 'Användarnamnet är inte tillgängligt';
        return;
      }

      isSaving.value = true;

      try {
        const response = await fetchWithAuth('/api/users/me', {
          method: 'PUT',
          body: JSON.stringify({
            username: username.value,
            display_name: displayName.value || null,
          }),
        });

        if (response.ok) {
          const updatedUser = await response.json();
          // Update the user object in useAuth
          user.value = updatedUser;
          showToast('Profil uppdaterad!', 'success');
        } else {
          const error = await response.json();
          showError(error.detail || 'Kunde inte uppdatera profil');
        }
      } catch (error) {
        console.error('Error saving profile:', error);
        showError('Kunde inte uppdatera profil');
      } finally {
        isSaving.value = false;
      }
    }

    return {
      user,
      username,
      displayName,
      usernameError,
      isCheckingUsername,
      isSaving,
      usernameAvailable,
      isAutoGeneratedUsername,
      checkUsernameAvailability,
      saveProfile,
    };
  },

  template: `
    <div class="max-w-2xl mx-auto p-6">
      <h1 class="text-3xl font-bold mb-6">Min Profil</h1>

      <!-- Auto-generated username notice -->
      <div v-if="isAutoGeneratedUsername" class="bg-yellow-50 border border-yellow-200 rounded-lg p-4 mb-6">
        <div class="flex items-start">
          <svg class="w-5 h-5 text-yellow-600 mt-0.5 mr-3 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20">
            <path fill-rule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clip-rule="evenodd"/>
          </svg>
          <div>
            <h3 class="text-sm font-medium text-yellow-800">Välj ditt användarnamn</h3>
            <p class="text-sm text-yellow-700 mt-1">
              Du har ett autogenererat användarnamn. Välj ett eget användarnamn för att dela spellistor med andra.
            </p>
          </div>
        </div>
      </div>

      <div class="bg-white rounded-lg shadow p-6 space-y-6">
        <!-- Email (read-only) -->
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-2">E-post</label>
          <input
            type="email"
            :value="user?.email"
            disabled
            class="w-full px-3 py-2 border border-gray-300 rounded-lg bg-gray-50 text-gray-500 cursor-not-allowed"
          />
          <p class="text-xs text-gray-500 mt-1">E-postadressen hanteras av Authentik</p>
        </div>

        <!-- Username -->
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-2">
            Användarnamn <span class="text-red-500">*</span>
          </label>
          <div class="relative">
            <input
              v-model="username"
              @input="checkUsernameAvailability"
              type="text"
              placeholder="mitt_användarnamn"
              class="w-full px-3 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-500"
              :class="{
                'border-red-300': usernameError,
                'border-green-300': usernameAvailable === true && username !== user?.username,
                'border-gray-300': !usernameError && usernameAvailable !== true
              }"
            />
            <div class="absolute inset-y-0 right-0 flex items-center pr-3">
              <!-- Checking spinner -->
              <svg v-if="isCheckingUsername" class="animate-spin h-5 w-5 text-gray-400" fill="none" viewBox="0 0 24 24">
                <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
              </svg>
              <!-- Available checkmark -->
              <svg v-else-if="usernameAvailable === true && username !== user?.username" class="h-5 w-5 text-green-500" fill="currentColor" viewBox="0 0 20 20">
                <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd"/>
              </svg>
              <!-- Error X -->
              <svg v-else-if="usernameError" class="h-5 w-5 text-red-500" fill="currentColor" viewBox="0 0 20 20">
                <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clip-rule="evenodd"/>
              </svg>
            </div>
          </div>
          <p v-if="usernameError" class="text-sm text-red-600 mt-1">{{ usernameError }}</p>
          <p v-else class="text-xs text-gray-500 mt-1">
            Endast bokstäver, siffror och _ (3-50 tecken)
          </p>
          <p class="text-xs text-gray-500 mt-1">
            <span class="font-medium">{{ username.length }}</span>/50 tecken
          </p>
        </div>

        <!-- Display Name -->
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-2">Visningsnamn</label>
          <input
            v-model="displayName"
            type="text"
            placeholder="Mitt Namn"
            class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-500"
          />
          <p class="text-xs text-gray-500 mt-1">Detta namn visas i gränssnittet (valfritt)</p>
        </div>

        <!-- Save Button -->
        <div class="flex justify-end">
          <button
            @click="saveProfile"
            :disabled="isSaving || usernameError || isCheckingUsername || usernameAvailable === false"
            class="bg-indigo-600 text-white px-6 py-2 rounded-lg hover:bg-indigo-500 disabled:opacity-50 disabled:cursor-not-allowed font-medium flex items-center gap-2"
          >
            <svg v-if="isSaving" class="animate-spin h-5 w-5" fill="none" viewBox="0 0 24 24">
              <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
              <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
            </svg>
            <span>{{ isSaving ? 'Sparar...' : 'Spara ändringar' }}</span>
          </button>
        </div>
      </div>
    </div>
  `,
};
