"""Adding author

Revision ID: 21c4ff857072
Revises: 939d93e3cf34
Create Date: 2025-12-05 08:54:56.434384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21c4ff857072'
down_revision: Union[str, Sequence[str], None] = '939d93e3cf34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track_structure_versions', sa.Column('author_alias', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track_structure_versions', 'author_alias')
    # ### end Alembic commands ###
