"""Adding crawler and genres

Revision ID: 267b6280082f
Revises: 39d2f92da6c4
Create Date: 2025-12-10 12:53:39.629333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '267b6280082f'
down_revision: Union[str, Sequence[str], None] = '39d2f92da6c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist_crawl_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('spotify_artist_id', sa.String(), nullable=False),
    sa.Column('artist_name', sa.String(), nullable=False),
    sa.Column('crawled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tracks_found', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('detected_genres', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('music_genre_classification', sa.String(), nullable=True),
    sa.Column('discovery_source', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spotify_artist_id', name='unique_spotify_artist_crawl')
    )
    op.create_index(op.f('ix_artist_crawl_logs_spotify_artist_id'), 'artist_crawl_logs', ['spotify_artist_id'], unique=False)
    op.add_column('tracks', sa.Column('music_genre', sa.String(), nullable=True))
    op.add_column('tracks', sa.Column('genre_confidence', sa.Float(), nullable=True))
    op.create_index(op.f('ix_tracks_music_genre'), 'tracks', ['music_genre'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracks_music_genre'), table_name='tracks')
    op.drop_column('tracks', 'genre_confidence')
    op.drop_column('tracks', 'music_genre')
    op.drop_index(op.f('ix_artist_crawl_logs_spotify_artist_id'), table_name='artist_crawl_logs')
    op.drop_table('artist_crawl_logs')
    # ### end Alembic commands ###
