"""Adding voting id

Revision ID: 468583ba7185
Revises: b7c8d9e0f1a2
Create Date: 2025-12-15 11:49:53.447013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '468583ba7185'
down_revision: Union[str, Sequence[str], None] = 'b7c8d9e0f1a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track_style_votes', sa.Column('voter_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_track_style_votes_voter_id'), 'track_style_votes', ['voter_id'], unique=False)
    op.drop_constraint(op.f('visitor_sessions_session_id_key'), 'visitor_sessions', type_='unique')
    op.drop_index(op.f('ix_visitor_sessions_session_id'), table_name='visitor_sessions')
    op.create_index(op.f('ix_visitor_sessions_session_id'), 'visitor_sessions', ['session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visitor_sessions_session_id'), table_name='visitor_sessions')
    op.create_index(op.f('ix_visitor_sessions_session_id'), 'visitor_sessions', ['session_id'], unique=False)
    op.create_unique_constraint(op.f('visitor_sessions_session_id_key'), 'visitor_sessions', ['session_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_track_style_votes_voter_id'), table_name='track_style_votes')
    op.drop_column('track_style_votes', 'voter_id')
    # ### end Alembic commands ###
