"""Add style confirmations

Revision ID: 64ebc972e372
Revises: 1e62e5cec2b3
Create Date: 2025-12-01 15:59:41.797648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64ebc972e372'
down_revision: Union[str, Sequence[str], None] = '1e62e5cec2b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track_dance_styles', sa.Column('confirmation_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track_dance_styles', 'confirmation_count')
    # ### end Alembic commands ###
