"""Adding verified to artists

Revision ID: 64f5af5ce616
Revises: 7d8ba26b4dd9
Create Date: 2025-12-12 16:10:27.837703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64f5af5ce616'
down_revision: Union[str, Sequence[str], None] = '7d8ba26b4dd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'is_verified')
    # ### end Alembic commands ###
