"""add_pending_artist_approval_table

Revision ID: 6876436080a7
Revises: a3f8d9e12b45
Create Date: 2025-12-12 06:18:01.644314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6876436080a7'
down_revision: Union[str, Sequence[str], None] = 'a3f8d9e12b45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_artist_approvals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('spotify_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('discovery_source', sa.String(), nullable=False),
    sa.Column('detected_genres', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('music_genre_classification', sa.String(), nullable=True),
    sa.Column('genre_confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('additional_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spotify_id', name='unique_pending_artist')
    )
    op.create_index(op.f('ix_pending_artist_approvals_spotify_id'), 'pending_artist_approvals', ['spotify_id'], unique=False)
    op.create_index(op.f('ix_pending_artist_approvals_status'), 'pending_artist_approvals', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_artist_approvals_status'), table_name='pending_artist_approvals')
    op.drop_index(op.f('ix_pending_artist_approvals_spotify_id'), table_name='pending_artist_approvals')
    op.drop_table('pending_artist_approvals')
    # ### end Alembic commands ###
