"""Add bars and sections to Track

Revision ID: c43b4984441e
Revises: 99bf2f4f9cf8
Create Date: 2025-12-03 06:41:46.283682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c43b4984441e'
down_revision: Union[str, Sequence[str], None] = '99bf2f4f9cf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track_feedback', sa.Column('corrected_bars', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('track_feedback', sa.Column('corrected_sections', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tracks', sa.Column('bars', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tracks', sa.Column('sections', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'sections')
    op.drop_column('tracks', 'bars')
    op.drop_column('track_feedback', 'corrected_sections')
    op.drop_column('track_feedback', 'corrected_bars')
    # ### end Alembic commands ###
