"""Adding bpm stability

Revision ID: c7a64fa45998
Revises: 89dd2423fa58
Create Date: 2025-12-16 07:58:23.755310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7a64fa45998'
down_revision: Union[str, Sequence[str], None] = '89dd2423fa58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('bpm_stability', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'bpm_stability')
    # ### end Alembic commands ###
