"""Adding artist and album

Revision ID: d70476af4a0c
Revises: 21c4ff857072
Create Date: 2025-12-06 12:35:03.277553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd70476af4a0c'
down_revision: Union[str, Sequence[str], None] = '21c4ff857072'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artists_name'), 'artists', ['name'], unique=False)
    op.create_table('albums',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('cover_image_url', sa.String(), nullable=True),
    sa.Column('release_date', sa.String(), nullable=True),
    sa.Column('artist_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_albums_title'), 'albums', ['title'], unique=False)
    op.create_table('track_artists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('track_id', sa.UUID(), nullable=False),
    sa.Column('artist_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track_id', 'artist_id', name='unique_track_artist')
    )
    op.add_column('tracks', sa.Column('album_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'tracks', 'albums', ['album_id'], ['id'])
    op.drop_column('tracks', 'album_name')
    op.drop_column('tracks', 'artist_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('artist_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('tracks', sa.Column('album_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tracks', type_='foreignkey')
    op.drop_column('tracks', 'album_id')
    op.drop_table('track_artists')
    op.drop_index(op.f('ix_albums_title'), table_name='albums')
    op.drop_table('albums')
    op.drop_index(op.f('ix_artists_name'), table_name='artists')
    op.drop_table('artists')
    # ### end Alembic commands ###
