"""Make feedback style optional

Revision ID: e2a2d2e2cfbc
Revises: e79e8ae0fb35
Create Date: 2025-12-05 05:43:25.513120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2a2d2e2cfbc'
down_revision: Union[str, Sequence[str], None] = 'e79e8ae0fb35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('track_feedback', 'suggested_style',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('track_feedback', 'tempo_correction',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('track_feedback', 'tempo_correction',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('track_feedback', 'suggested_style',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
