/*
 * This file is generated by jOOQ.
 */
package se.dansbart.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import se.dansbart.jooq.DefaultSchema;
import se.dansbart.jooq.Keys;
import se.dansbart.jooq.tables.Artists.ArtistsPath;
import se.dansbart.jooq.tables.TrackAlbums.TrackAlbumsPath;
import se.dansbart.jooq.tables.Tracks.TracksPath;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Albums extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ALBUMS</code>
     */
    public static final Albums ALBUMS = new Albums();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>ALBUMS.ID</code>.
     */
    public final TableField<Record, UUID> ID = createField(DSL.name("ID"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("RANDOM_UUID()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>ALBUMS.TITLE</code>.
     */
    public final TableField<Record, String> TITLE = createField(DSL.name("TITLE"), SQLDataType.VARCHAR(1000000000).nullable(false), this, "");

    /**
     * The column <code>ALBUMS.COVER_IMAGE_URL</code>.
     */
    public final TableField<Record, String> COVER_IMAGE_URL = createField(DSL.name("COVER_IMAGE_URL"), SQLDataType.VARCHAR(1000000000), this, "");

    /**
     * The column <code>ALBUMS.RELEASE_DATE</code>.
     */
    public final TableField<Record, String> RELEASE_DATE = createField(DSL.name("RELEASE_DATE"), SQLDataType.VARCHAR(1000000000), this, "");

    /**
     * The column <code>ALBUMS.SPOTIFY_ID</code>.
     */
    public final TableField<Record, String> SPOTIFY_ID = createField(DSL.name("SPOTIFY_ID"), SQLDataType.VARCHAR(1000000000), this, "");

    /**
     * The column <code>ALBUMS.ARTIST_ID</code>.
     */
    public final TableField<Record, UUID> ARTIST_ID = createField(DSL.name("ARTIST_ID"), SQLDataType.UUID, this, "");

    private Albums(Name alias, Table<Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Albums(Name alias, Table<Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>ALBUMS</code> table reference
     */
    public Albums(String alias) {
        this(DSL.name(alias), ALBUMS);
    }

    /**
     * Create an aliased <code>ALBUMS</code> table reference
     */
    public Albums(Name alias) {
        this(alias, ALBUMS);
    }

    /**
     * Create a <code>ALBUMS</code> table reference
     */
    public Albums() {
        this(DSL.name("ALBUMS"), null);
    }

    public <O extends Record> Albums(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
        super(path, childPath, parentPath, ALBUMS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AlbumsPath extends Albums implements Path<Record> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AlbumsPath(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
            super(path, childPath, parentPath);
        }
        private AlbumsPath(Name alias, Table<Record> aliased) {
            super(alias, aliased);
        }

        @Override
        public AlbumsPath as(String alias) {
            return new AlbumsPath(DSL.name(alias), this);
        }

        @Override
        public AlbumsPath as(Name alias) {
            return new AlbumsPath(alias, this);
        }

        @Override
        public AlbumsPath as(Table<?> alias) {
            return new AlbumsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.CONSTRAINT_7;
    }

    @Override
    public List<UniqueKey<Record>> getUniqueKeys() {
        return Arrays.asList(Keys.CONSTRAINT_73);
    }

    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_733);
    }

    private transient ArtistsPath _artists;

    /**
     * Get the implicit join path to the <code>PUBLIC.ARTISTS</code> table.
     */
    public ArtistsPath artists() {
        if (_artists == null)
            _artists = new ArtistsPath(this, Keys.CONSTRAINT_733, null);

        return _artists;
    }

    private transient TrackAlbumsPath _trackAlbums;

    /**
     * Get the implicit to-many join path to the
     * <code>PUBLIC.TRACK_ALBUMS</code> table
     */
    public TrackAlbumsPath trackAlbums() {
        if (_trackAlbums == null)
            _trackAlbums = new TrackAlbumsPath(this, null, Keys.CONSTRAINT_8FB.getInverseKey());

        return _trackAlbums;
    }

    /**
     * Get the implicit many-to-many join path to the <code>PUBLIC.TRACKS</code>
     * table
     */
    public TracksPath tracks() {
        return trackAlbums().tracks();
    }

    @Override
    public Albums as(String alias) {
        return new Albums(DSL.name(alias), this);
    }

    @Override
    public Albums as(Name alias) {
        return new Albums(alias, this);
    }

    @Override
    public Albums as(Table<?> alias) {
        return new Albums(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Albums rename(String name) {
        return new Albums(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Albums rename(Name name) {
        return new Albums(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Albums rename(Table<?> name) {
        return new Albums(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Albums where(Condition condition) {
        return new Albums(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Albums where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Albums where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Albums where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Albums where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Albums where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Albums where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Albums where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Albums whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Albums whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
