/*
 * This file is generated by jOOQ.
 */
package se.dansbart.jooq.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import se.dansbart.jooq.DefaultSchema;
import se.dansbart.jooq.Keys;
import se.dansbart.jooq.tables.Tracks.TracksPath;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AnalysisSources extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ANALYSIS_SOURCES</code>
     */
    public static final AnalysisSources ANALYSIS_SOURCES = new AnalysisSources();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>ANALYSIS_SOURCES.ID</code>.
     */
    public final TableField<Record, UUID> ID = createField(DSL.name("ID"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("RANDOM_UUID()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>ANALYSIS_SOURCES.TRACK_ID</code>.
     */
    public final TableField<Record, UUID> TRACK_ID = createField(DSL.name("TRACK_ID"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>ANALYSIS_SOURCES.SOURCE_TYPE</code>.
     */
    public final TableField<Record, String> SOURCE_TYPE = createField(DSL.name("SOURCE_TYPE"), SQLDataType.VARCHAR(1000000000).nullable(false), this, "");

    /**
     * The column <code>ANALYSIS_SOURCES.RAW_DATA</code>.
     */
    public final TableField<Record, String> RAW_DATA = createField(DSL.name("RAW_DATA"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>ANALYSIS_SOURCES.CONFIDENCE_SCORE</code>.
     */
    public final TableField<Record, Double> CONFIDENCE_SCORE = createField(DSL.name("CONFIDENCE_SCORE"), SQLDataType.DOUBLE.defaultValue(DSL.field(DSL.raw("1.0"), SQLDataType.DOUBLE)), this, "");

    /**
     * The column <code>ANALYSIS_SOURCES.ANALYZED_AT</code>.
     */
    public final TableField<Record, OffsetDateTime> ANALYZED_AT = createField(DSL.name("ANALYZED_AT"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private AnalysisSources(Name alias, Table<Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AnalysisSources(Name alias, Table<Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>ANALYSIS_SOURCES</code> table reference
     */
    public AnalysisSources(String alias) {
        this(DSL.name(alias), ANALYSIS_SOURCES);
    }

    /**
     * Create an aliased <code>ANALYSIS_SOURCES</code> table reference
     */
    public AnalysisSources(Name alias) {
        this(alias, ANALYSIS_SOURCES);
    }

    /**
     * Create a <code>ANALYSIS_SOURCES</code> table reference
     */
    public AnalysisSources() {
        this(DSL.name("ANALYSIS_SOURCES"), null);
    }

    public <O extends Record> AnalysisSources(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
        super(path, childPath, parentPath, ANALYSIS_SOURCES);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AnalysisSourcesPath extends AnalysisSources implements Path<Record> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AnalysisSourcesPath(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
            super(path, childPath, parentPath);
        }
        private AnalysisSourcesPath(Name alias, Table<Record> aliased) {
            super(alias, aliased);
        }

        @Override
        public AnalysisSourcesPath as(String alias) {
            return new AnalysisSourcesPath(DSL.name(alias), this);
        }

        @Override
        public AnalysisSourcesPath as(Name alias) {
            return new AnalysisSourcesPath(alias, this);
        }

        @Override
        public AnalysisSourcesPath as(Table<?> alias) {
            return new AnalysisSourcesPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.CONSTRAINT_B;
    }

    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_BB);
    }

    private transient TracksPath _tracks;

    /**
     * Get the implicit join path to the <code>PUBLIC.TRACKS</code> table.
     */
    public TracksPath tracks() {
        if (_tracks == null)
            _tracks = new TracksPath(this, Keys.CONSTRAINT_BB, null);

        return _tracks;
    }

    @Override
    public AnalysisSources as(String alias) {
        return new AnalysisSources(DSL.name(alias), this);
    }

    @Override
    public AnalysisSources as(Name alias) {
        return new AnalysisSources(alias, this);
    }

    @Override
    public AnalysisSources as(Table<?> alias) {
        return new AnalysisSources(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AnalysisSources rename(String name) {
        return new AnalysisSources(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AnalysisSources rename(Name name) {
        return new AnalysisSources(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AnalysisSources rename(Table<?> name) {
        return new AnalysisSources(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AnalysisSources where(Condition condition) {
        return new AnalysisSources(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AnalysisSources where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AnalysisSources where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AnalysisSources where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AnalysisSources where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AnalysisSources where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AnalysisSources where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AnalysisSources where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AnalysisSources whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AnalysisSources whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
