/*
 * This file is generated by jOOQ.
 */
package se.dansbart.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import se.dansbart.jooq.Indexes;
import se.dansbart.jooq.Keys;
import se.dansbart.jooq.Public;
import se.dansbart.jooq.tables.Albums.AlbumsPath;
import se.dansbart.jooq.tables.TrackArtists.TrackArtistsPath;
import se.dansbart.jooq.tables.Tracks.TracksPath;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Artists extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.artists</code>
     */
    public static final Artists ARTISTS = new Artists();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.artists.id</code>.
     */
    public final TableField<Record, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.artists.name</code>.
     */
    public final TableField<Record, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.artists.spotify_id</code>.
     */
    public final TableField<Record, String> SPOTIFY_ID = createField(DSL.name("spotify_id"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.artists.image_url</code>.
     */
    public final TableField<Record, String> IMAGE_URL = createField(DSL.name("image_url"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.artists.is_verified</code>.
     */
    public final TableField<Record, Boolean> IS_VERIFIED = createField(DSL.name("is_verified"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    private Artists(Name alias, Table<Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Artists(Name alias, Table<Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.artists</code> table reference
     */
    public Artists(String alias) {
        this(DSL.name(alias), ARTISTS);
    }

    /**
     * Create an aliased <code>public.artists</code> table reference
     */
    public Artists(Name alias) {
        this(alias, ARTISTS);
    }

    /**
     * Create a <code>public.artists</code> table reference
     */
    public Artists() {
        this(DSL.name("artists"), null);
    }

    public <O extends Record> Artists(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
        super(path, childPath, parentPath, ARTISTS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ArtistsPath extends Artists implements Path<Record> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ArtistsPath(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
            super(path, childPath, parentPath);
        }
        private ArtistsPath(Name alias, Table<Record> aliased) {
            super(alias, aliased);
        }

        @Override
        public ArtistsPath as(String alias) {
            return new ArtistsPath(DSL.name(alias), this);
        }

        @Override
        public ArtistsPath as(Name alias) {
            return new ArtistsPath(alias, this);
        }

        @Override
        public ArtistsPath as(Table<?> alias) {
            return new ArtistsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IX_ARTISTS_NAME);
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.ARTISTS_PKEY;
    }

    @Override
    public List<UniqueKey<Record>> getUniqueKeys() {
        return Arrays.asList(Keys.ARTISTS_SPOTIFY_ID_KEY);
    }

    private transient AlbumsPath _albums;

    /**
     * Get the implicit to-many join path to the <code>public.albums</code>
     * table
     */
    public AlbumsPath albums() {
        if (_albums == null)
            _albums = new AlbumsPath(this, null, Keys.ALBUMS__ALBUMS_ARTIST_ID_FKEY.getInverseKey());

        return _albums;
    }

    private transient TrackArtistsPath _trackArtists;

    /**
     * Get the implicit to-many join path to the
     * <code>public.track_artists</code> table
     */
    public TrackArtistsPath trackArtists() {
        if (_trackArtists == null)
            _trackArtists = new TrackArtistsPath(this, null, Keys.TRACK_ARTISTS__TRACK_ARTISTS_ARTIST_ID_FKEY.getInverseKey());

        return _trackArtists;
    }

    /**
     * Get the implicit many-to-many join path to the <code>public.tracks</code>
     * table
     */
    public TracksPath tracks() {
        return trackArtists().tracks();
    }

    @Override
    public Artists as(String alias) {
        return new Artists(DSL.name(alias), this);
    }

    @Override
    public Artists as(Name alias) {
        return new Artists(alias, this);
    }

    @Override
    public Artists as(Table<?> alias) {
        return new Artists(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Artists rename(String name) {
        return new Artists(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Artists rename(Name name) {
        return new Artists(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Artists rename(Table<?> name) {
        return new Artists(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Artists where(Condition condition) {
        return new Artists(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Artists where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Artists where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Artists where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Artists where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Artists where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Artists where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Artists where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Artists whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Artists whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
