/*
 * This file is generated by jOOQ.
 */
package se.dansbart.jooq.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import se.dansbart.jooq.DefaultSchema;
import se.dansbart.jooq.Keys;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ArtistCrawlLogs extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ARTIST_CRAWL_LOGS</code>
     */
    public static final ArtistCrawlLogs ARTIST_CRAWL_LOGS = new ArtistCrawlLogs();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>ARTIST_CRAWL_LOGS.ID</code>.
     */
    public final TableField<Record, UUID> ID = createField(DSL.name("ID"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("RANDOM_UUID()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>ARTIST_CRAWL_LOGS.SPOTIFY_ARTIST_ID</code>.
     */
    public final TableField<Record, String> SPOTIFY_ARTIST_ID = createField(DSL.name("SPOTIFY_ARTIST_ID"), SQLDataType.VARCHAR(1000000000).nullable(false), this, "");

    /**
     * The column <code>ARTIST_CRAWL_LOGS.ARTIST_NAME</code>.
     */
    public final TableField<Record, String> ARTIST_NAME = createField(DSL.name("ARTIST_NAME"), SQLDataType.VARCHAR(1000000000).nullable(false), this, "");

    /**
     * The column <code>ARTIST_CRAWL_LOGS.CRAWLED_AT</code>.
     */
    public final TableField<Record, OffsetDateTime> CRAWLED_AT = createField(DSL.name("CRAWLED_AT"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>ARTIST_CRAWL_LOGS.TRACKS_FOUND</code>.
     */
    public final TableField<Record, Integer> TRACKS_FOUND = createField(DSL.name("TRACKS_FOUND"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>ARTIST_CRAWL_LOGS.STATUS</code>.
     */
    public final TableField<Record, String> STATUS = createField(DSL.name("STATUS"), SQLDataType.VARCHAR(1000000000).defaultValue(DSL.field(DSL.raw("'success'"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>ARTIST_CRAWL_LOGS.DETECTED_GENRES</code>.
     */
    public final TableField<Record, String> DETECTED_GENRES = createField(DSL.name("DETECTED_GENRES"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>ARTIST_CRAWL_LOGS.MUSIC_GENRE_CLASSIFICATION</code>.
     */
    public final TableField<Record, String> MUSIC_GENRE_CLASSIFICATION = createField(DSL.name("MUSIC_GENRE_CLASSIFICATION"), SQLDataType.VARCHAR(1000000000), this, "");

    /**
     * The column <code>ARTIST_CRAWL_LOGS.DISCOVERY_SOURCE</code>.
     */
    public final TableField<Record, String> DISCOVERY_SOURCE = createField(DSL.name("DISCOVERY_SOURCE"), SQLDataType.VARCHAR(1000000000), this, "");

    private ArtistCrawlLogs(Name alias, Table<Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ArtistCrawlLogs(Name alias, Table<Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>ARTIST_CRAWL_LOGS</code> table reference
     */
    public ArtistCrawlLogs(String alias) {
        this(DSL.name(alias), ARTIST_CRAWL_LOGS);
    }

    /**
     * Create an aliased <code>ARTIST_CRAWL_LOGS</code> table reference
     */
    public ArtistCrawlLogs(Name alias) {
        this(alias, ARTIST_CRAWL_LOGS);
    }

    /**
     * Create a <code>ARTIST_CRAWL_LOGS</code> table reference
     */
    public ArtistCrawlLogs() {
        this(DSL.name("ARTIST_CRAWL_LOGS"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.CONSTRAINT_A;
    }

    @Override
    public List<UniqueKey<Record>> getUniqueKeys() {
        return Arrays.asList(Keys.CONSTRAINT_A5);
    }

    @Override
    public ArtistCrawlLogs as(String alias) {
        return new ArtistCrawlLogs(DSL.name(alias), this);
    }

    @Override
    public ArtistCrawlLogs as(Name alias) {
        return new ArtistCrawlLogs(alias, this);
    }

    @Override
    public ArtistCrawlLogs as(Table<?> alias) {
        return new ArtistCrawlLogs(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ArtistCrawlLogs rename(String name) {
        return new ArtistCrawlLogs(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ArtistCrawlLogs rename(Name name) {
        return new ArtistCrawlLogs(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ArtistCrawlLogs rename(Table<?> name) {
        return new ArtistCrawlLogs(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ArtistCrawlLogs where(Condition condition) {
        return new ArtistCrawlLogs(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ArtistCrawlLogs where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ArtistCrawlLogs where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ArtistCrawlLogs where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ArtistCrawlLogs where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ArtistCrawlLogs where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ArtistCrawlLogs where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ArtistCrawlLogs where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ArtistCrawlLogs whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ArtistCrawlLogs whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
