/*
 * This file is generated by jOOQ.
 */
package se.dansbart.jooq.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import se.dansbart.jooq.DefaultSchema;
import se.dansbart.jooq.Keys;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GenreProfiles extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>GENRE_PROFILES</code>
     */
    public static final GenreProfiles GENRE_PROFILES = new GenreProfiles();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>GENRE_PROFILES.ID</code>.
     */
    public final TableField<Record, UUID> ID = createField(DSL.name("ID"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("RANDOM_UUID()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>GENRE_PROFILES.GENRE_NAME</code>.
     */
    public final TableField<Record, String> GENRE_NAME = createField(DSL.name("GENRE_NAME"), SQLDataType.VARCHAR(1000000000).nullable(false), this, "");

    /**
     * The column <code>GENRE_PROFILES.AVG_NOTE_DENSITY</code>.
     */
    public final TableField<Record, Double> AVG_NOTE_DENSITY = createField(DSL.name("AVG_NOTE_DENSITY"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>GENRE_PROFILES.COMMON_METERS</code>.
     */
    public final TableField<Record, String> COMMON_METERS = createField(DSL.name("COMMON_METERS"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>GENRE_PROFILES.RHYTHM_PATTERNS</code>.
     */
    public final TableField<Record, String> RHYTHM_PATTERNS = createField(DSL.name("RHYTHM_PATTERNS"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>GENRE_PROFILES.SAMPLE_SIZE</code>.
     */
    public final TableField<Record, Integer> SAMPLE_SIZE = createField(DSL.name("SAMPLE_SIZE"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>GENRE_PROFILES.UPDATED_AT</code>.
     */
    public final TableField<Record, OffsetDateTime> UPDATED_AT = createField(DSL.name("UPDATED_AT"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private GenreProfiles(Name alias, Table<Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private GenreProfiles(Name alias, Table<Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>GENRE_PROFILES</code> table reference
     */
    public GenreProfiles(String alias) {
        this(DSL.name(alias), GENRE_PROFILES);
    }

    /**
     * Create an aliased <code>GENRE_PROFILES</code> table reference
     */
    public GenreProfiles(Name alias) {
        this(alias, GENRE_PROFILES);
    }

    /**
     * Create a <code>GENRE_PROFILES</code> table reference
     */
    public GenreProfiles() {
        this(DSL.name("GENRE_PROFILES"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.CONSTRAINT_C;
    }

    @Override
    public List<UniqueKey<Record>> getUniqueKeys() {
        return Arrays.asList(Keys.CONSTRAINT_C7);
    }

    @Override
    public GenreProfiles as(String alias) {
        return new GenreProfiles(DSL.name(alias), this);
    }

    @Override
    public GenreProfiles as(Name alias) {
        return new GenreProfiles(alias, this);
    }

    @Override
    public GenreProfiles as(Table<?> alias) {
        return new GenreProfiles(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public GenreProfiles rename(String name) {
        return new GenreProfiles(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GenreProfiles rename(Name name) {
        return new GenreProfiles(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public GenreProfiles rename(Table<?> name) {
        return new GenreProfiles(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GenreProfiles where(Condition condition) {
        return new GenreProfiles(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GenreProfiles where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GenreProfiles where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GenreProfiles where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GenreProfiles where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GenreProfiles where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GenreProfiles where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GenreProfiles where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GenreProfiles whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GenreProfiles whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
