/*
 * This file is generated by jOOQ.
 */
package se.dansbart.jooq.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import se.dansbart.jooq.DefaultSchema;
import se.dansbart.jooq.Keys;
import se.dansbart.jooq.tables.Playlists.PlaylistsPath;
import se.dansbart.jooq.tables.Tracks.TracksPath;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PlaylistTracks extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>PLAYLIST_TRACKS</code>
     */
    public static final PlaylistTracks PLAYLIST_TRACKS = new PlaylistTracks();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>PLAYLIST_TRACKS.ID</code>.
     */
    public final TableField<Record, UUID> ID = createField(DSL.name("ID"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("RANDOM_UUID()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>PLAYLIST_TRACKS.PLAYLIST_ID</code>.
     */
    public final TableField<Record, UUID> PLAYLIST_ID = createField(DSL.name("PLAYLIST_ID"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>PLAYLIST_TRACKS.TRACK_ID</code>.
     */
    public final TableField<Record, UUID> TRACK_ID = createField(DSL.name("TRACK_ID"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>PLAYLIST_TRACKS.POSITION</code>.
     */
    public final TableField<Record, Integer> POSITION = createField(DSL.name("POSITION"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>PLAYLIST_TRACKS.ADDED_AT</code>.
     */
    public final TableField<Record, OffsetDateTime> ADDED_AT = createField(DSL.name("ADDED_AT"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private PlaylistTracks(Name alias, Table<Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PlaylistTracks(Name alias, Table<Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>PLAYLIST_TRACKS</code> table reference
     */
    public PlaylistTracks(String alias) {
        this(DSL.name(alias), PLAYLIST_TRACKS);
    }

    /**
     * Create an aliased <code>PLAYLIST_TRACKS</code> table reference
     */
    public PlaylistTracks(Name alias) {
        this(alias, PLAYLIST_TRACKS);
    }

    /**
     * Create a <code>PLAYLIST_TRACKS</code> table reference
     */
    public PlaylistTracks() {
        this(DSL.name("PLAYLIST_TRACKS"), null);
    }

    public <O extends Record> PlaylistTracks(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
        super(path, childPath, parentPath, PLAYLIST_TRACKS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class PlaylistTracksPath extends PlaylistTracks implements Path<Record> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> PlaylistTracksPath(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
            super(path, childPath, parentPath);
        }
        private PlaylistTracksPath(Name alias, Table<Record> aliased) {
            super(alias, aliased);
        }

        @Override
        public PlaylistTracksPath as(String alias) {
            return new PlaylistTracksPath(DSL.name(alias), this);
        }

        @Override
        public PlaylistTracksPath as(Name alias) {
            return new PlaylistTracksPath(alias, this);
        }

        @Override
        public PlaylistTracksPath as(Table<?> alias) {
            return new PlaylistTracksPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.CONSTRAINT_98;
    }

    @Override
    public List<UniqueKey<Record>> getUniqueKeys() {
        return Arrays.asList(Keys.UNIQUE_PLAYLIST_TRACK);
    }

    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_98C, Keys.CONSTRAINT_98C2);
    }

    private transient PlaylistsPath _playlists;

    /**
     * Get the implicit join path to the <code>PUBLIC.PLAYLISTS</code> table.
     */
    public PlaylistsPath playlists() {
        if (_playlists == null)
            _playlists = new PlaylistsPath(this, Keys.CONSTRAINT_98C, null);

        return _playlists;
    }

    private transient TracksPath _tracks;

    /**
     * Get the implicit join path to the <code>PUBLIC.TRACKS</code> table.
     */
    public TracksPath tracks() {
        if (_tracks == null)
            _tracks = new TracksPath(this, Keys.CONSTRAINT_98C2, null);

        return _tracks;
    }

    @Override
    public PlaylistTracks as(String alias) {
        return new PlaylistTracks(DSL.name(alias), this);
    }

    @Override
    public PlaylistTracks as(Name alias) {
        return new PlaylistTracks(alias, this);
    }

    @Override
    public PlaylistTracks as(Table<?> alias) {
        return new PlaylistTracks(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PlaylistTracks rename(String name) {
        return new PlaylistTracks(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PlaylistTracks rename(Name name) {
        return new PlaylistTracks(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PlaylistTracks rename(Table<?> name) {
        return new PlaylistTracks(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlaylistTracks where(Condition condition) {
        return new PlaylistTracks(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlaylistTracks where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlaylistTracks where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlaylistTracks where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PlaylistTracks where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PlaylistTracks where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PlaylistTracks where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PlaylistTracks where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlaylistTracks whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlaylistTracks whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
