/*
 * This file is generated by jOOQ.
 */
package se.dansbart.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import se.dansbart.jooq.DefaultSchema;
import se.dansbart.jooq.Keys;
import se.dansbart.jooq.tables.Tracks.TracksPath;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PlaybackLinks extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>PLAYBACK_LINKS</code>
     */
    public static final PlaybackLinks PLAYBACK_LINKS = new PlaybackLinks();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>PLAYBACK_LINKS.ID</code>.
     */
    public final TableField<Record, UUID> ID = createField(DSL.name("ID"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("RANDOM_UUID()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>PLAYBACK_LINKS.TRACK_ID</code>.
     */
    public final TableField<Record, UUID> TRACK_ID = createField(DSL.name("TRACK_ID"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>PLAYBACK_LINKS.PLATFORM</code>.
     */
    public final TableField<Record, String> PLATFORM = createField(DSL.name("PLATFORM"), SQLDataType.VARCHAR(1000000000).nullable(false), this, "");

    /**
     * The column <code>PLAYBACK_LINKS.DEEP_LINK</code>.
     */
    public final TableField<Record, String> DEEP_LINK = createField(DSL.name("DEEP_LINK"), SQLDataType.VARCHAR(1000000000).nullable(false), this, "");

    /**
     * The column <code>PLAYBACK_LINKS.IS_WORKING</code>.
     */
    public final TableField<Record, Boolean> IS_WORKING = createField(DSL.name("IS_WORKING"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("TRUE"), SQLDataType.BOOLEAN)), this, "");

    private PlaybackLinks(Name alias, Table<Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PlaybackLinks(Name alias, Table<Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>PLAYBACK_LINKS</code> table reference
     */
    public PlaybackLinks(String alias) {
        this(DSL.name(alias), PLAYBACK_LINKS);
    }

    /**
     * Create an aliased <code>PLAYBACK_LINKS</code> table reference
     */
    public PlaybackLinks(Name alias) {
        this(alias, PLAYBACK_LINKS);
    }

    /**
     * Create a <code>PLAYBACK_LINKS</code> table reference
     */
    public PlaybackLinks() {
        this(DSL.name("PLAYBACK_LINKS"), null);
    }

    public <O extends Record> PlaybackLinks(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
        super(path, childPath, parentPath, PLAYBACK_LINKS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class PlaybackLinksPath extends PlaybackLinks implements Path<Record> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> PlaybackLinksPath(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
            super(path, childPath, parentPath);
        }
        private PlaybackLinksPath(Name alias, Table<Record> aliased) {
            super(alias, aliased);
        }

        @Override
        public PlaybackLinksPath as(String alias) {
            return new PlaybackLinksPath(DSL.name(alias), this);
        }

        @Override
        public PlaybackLinksPath as(Name alias) {
            return new PlaybackLinksPath(alias, this);
        }

        @Override
        public PlaybackLinksPath as(Table<?> alias) {
            return new PlaybackLinksPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.CONSTRAINT_11;
    }

    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_11F);
    }

    private transient TracksPath _tracks;

    /**
     * Get the implicit join path to the <code>PUBLIC.TRACKS</code> table.
     */
    public TracksPath tracks() {
        if (_tracks == null)
            _tracks = new TracksPath(this, Keys.CONSTRAINT_11F, null);

        return _tracks;
    }

    @Override
    public PlaybackLinks as(String alias) {
        return new PlaybackLinks(DSL.name(alias), this);
    }

    @Override
    public PlaybackLinks as(Name alias) {
        return new PlaybackLinks(alias, this);
    }

    @Override
    public PlaybackLinks as(Table<?> alias) {
        return new PlaybackLinks(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PlaybackLinks rename(String name) {
        return new PlaybackLinks(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PlaybackLinks rename(Name name) {
        return new PlaybackLinks(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PlaybackLinks rename(Table<?> name) {
        return new PlaybackLinks(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlaybackLinks where(Condition condition) {
        return new PlaybackLinks(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlaybackLinks where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlaybackLinks where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlaybackLinks where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PlaybackLinks where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PlaybackLinks where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PlaybackLinks where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PlaybackLinks where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlaybackLinks whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlaybackLinks whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
