/*
 * This file is generated by jOOQ.
 */
package se.dansbart.jooq.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import se.dansbart.jooq.DefaultSchema;
import se.dansbart.jooq.Keys;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RejectionLogs extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>REJECTION_LOGS</code>
     */
    public static final RejectionLogs REJECTION_LOGS = new RejectionLogs();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>REJECTION_LOGS.ID</code>.
     */
    public final TableField<Record, UUID> ID = createField(DSL.name("ID"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("RANDOM_UUID()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>REJECTION_LOGS.ENTITY_TYPE</code>.
     */
    public final TableField<Record, String> ENTITY_TYPE = createField(DSL.name("ENTITY_TYPE"), SQLDataType.VARCHAR(1000000000).nullable(false), this, "");

    /**
     * The column <code>REJECTION_LOGS.SPOTIFY_ID</code>.
     */
    public final TableField<Record, String> SPOTIFY_ID = createField(DSL.name("SPOTIFY_ID"), SQLDataType.VARCHAR(1000000000).nullable(false), this, "");

    /**
     * The column <code>REJECTION_LOGS.ENTITY_NAME</code>.
     */
    public final TableField<Record, String> ENTITY_NAME = createField(DSL.name("ENTITY_NAME"), SQLDataType.VARCHAR(1000000000).nullable(false), this, "");

    /**
     * The column <code>REJECTION_LOGS.REASON</code>.
     */
    public final TableField<Record, String> REASON = createField(DSL.name("REASON"), SQLDataType.VARCHAR(1000000000), this, "");

    /**
     * The column <code>REJECTION_LOGS.REJECTED_AT</code>.
     */
    public final TableField<Record, OffsetDateTime> REJECTED_AT = createField(DSL.name("REJECTED_AT"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>REJECTION_LOGS.DELETED_CONTENT</code>.
     */
    public final TableField<Record, Boolean> DELETED_CONTENT = createField(DSL.name("DELETED_CONTENT"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("TRUE"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>REJECTION_LOGS.ADDITIONAL_DATA</code>.
     */
    public final TableField<Record, String> ADDITIONAL_DATA = createField(DSL.name("ADDITIONAL_DATA"), SQLDataType.CLOB, this, "");

    private RejectionLogs(Name alias, Table<Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private RejectionLogs(Name alias, Table<Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>REJECTION_LOGS</code> table reference
     */
    public RejectionLogs(String alias) {
        this(DSL.name(alias), REJECTION_LOGS);
    }

    /**
     * Create an aliased <code>REJECTION_LOGS</code> table reference
     */
    public RejectionLogs(Name alias) {
        this(alias, REJECTION_LOGS);
    }

    /**
     * Create a <code>REJECTION_LOGS</code> table reference
     */
    public RejectionLogs() {
        this(DSL.name("REJECTION_LOGS"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.CONSTRAINT_FC;
    }

    @Override
    public List<UniqueKey<Record>> getUniqueKeys() {
        return Arrays.asList(Keys.UNIQUE_REJECTION);
    }

    @Override
    public RejectionLogs as(String alias) {
        return new RejectionLogs(DSL.name(alias), this);
    }

    @Override
    public RejectionLogs as(Name alias) {
        return new RejectionLogs(alias, this);
    }

    @Override
    public RejectionLogs as(Table<?> alias) {
        return new RejectionLogs(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public RejectionLogs rename(String name) {
        return new RejectionLogs(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RejectionLogs rename(Name name) {
        return new RejectionLogs(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public RejectionLogs rename(Table<?> name) {
        return new RejectionLogs(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RejectionLogs where(Condition condition) {
        return new RejectionLogs(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RejectionLogs where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RejectionLogs where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RejectionLogs where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RejectionLogs where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RejectionLogs where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RejectionLogs where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RejectionLogs where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RejectionLogs whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RejectionLogs whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
