/*
 * This file is generated by jOOQ.
 */
package se.dansbart.jooq.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import se.dansbart.jooq.DefaultSchema;
import se.dansbart.jooq.Keys;
import se.dansbart.jooq.tables.Tracks.TracksPath;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TrackStructureVersions extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>TRACK_STRUCTURE_VERSIONS</code>
     */
    public static final TrackStructureVersions TRACK_STRUCTURE_VERSIONS = new TrackStructureVersions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>TRACK_STRUCTURE_VERSIONS.ID</code>.
     */
    public final TableField<Record, UUID> ID = createField(DSL.name("ID"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("RANDOM_UUID()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>TRACK_STRUCTURE_VERSIONS.TRACK_ID</code>.
     */
    public final TableField<Record, UUID> TRACK_ID = createField(DSL.name("TRACK_ID"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>TRACK_STRUCTURE_VERSIONS.CREATED_AT</code>.
     */
    public final TableField<Record, OffsetDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>TRACK_STRUCTURE_VERSIONS.DESCRIPTION</code>.
     */
    public final TableField<Record, String> DESCRIPTION = createField(DSL.name("DESCRIPTION"), SQLDataType.VARCHAR(1000000000), this, "");

    /**
     * The column <code>TRACK_STRUCTURE_VERSIONS.STRUCTURE_DATA</code>.
     */
    public final TableField<Record, String> STRUCTURE_DATA = createField(DSL.name("STRUCTURE_DATA"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>TRACK_STRUCTURE_VERSIONS.VOTE_COUNT</code>.
     */
    public final TableField<Record, Integer> VOTE_COUNT = createField(DSL.name("VOTE_COUNT"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("1"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>TRACK_STRUCTURE_VERSIONS.REPORT_COUNT</code>.
     */
    public final TableField<Record, Integer> REPORT_COUNT = createField(DSL.name("REPORT_COUNT"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>TRACK_STRUCTURE_VERSIONS.IS_ACTIVE</code>.
     */
    public final TableField<Record, Boolean> IS_ACTIVE = createField(DSL.name("IS_ACTIVE"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("FALSE"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>TRACK_STRUCTURE_VERSIONS.IS_HIDDEN</code>.
     */
    public final TableField<Record, Boolean> IS_HIDDEN = createField(DSL.name("IS_HIDDEN"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("FALSE"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>TRACK_STRUCTURE_VERSIONS.AUTHOR_ALIAS</code>.
     */
    public final TableField<Record, String> AUTHOR_ALIAS = createField(DSL.name("AUTHOR_ALIAS"), SQLDataType.VARCHAR(1000000000), this, "");

    private TrackStructureVersions(Name alias, Table<Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TrackStructureVersions(Name alias, Table<Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>TRACK_STRUCTURE_VERSIONS</code> table reference
     */
    public TrackStructureVersions(String alias) {
        this(DSL.name(alias), TRACK_STRUCTURE_VERSIONS);
    }

    /**
     * Create an aliased <code>TRACK_STRUCTURE_VERSIONS</code> table reference
     */
    public TrackStructureVersions(Name alias) {
        this(alias, TRACK_STRUCTURE_VERSIONS);
    }

    /**
     * Create a <code>TRACK_STRUCTURE_VERSIONS</code> table reference
     */
    public TrackStructureVersions() {
        this(DSL.name("TRACK_STRUCTURE_VERSIONS"), null);
    }

    public <O extends Record> TrackStructureVersions(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
        super(path, childPath, parentPath, TRACK_STRUCTURE_VERSIONS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TrackStructureVersionsPath extends TrackStructureVersions implements Path<Record> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TrackStructureVersionsPath(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
            super(path, childPath, parentPath);
        }
        private TrackStructureVersionsPath(Name alias, Table<Record> aliased) {
            super(alias, aliased);
        }

        @Override
        public TrackStructureVersionsPath as(String alias) {
            return new TrackStructureVersionsPath(DSL.name(alias), this);
        }

        @Override
        public TrackStructureVersionsPath as(Name alias) {
            return new TrackStructureVersionsPath(alias, this);
        }

        @Override
        public TrackStructureVersionsPath as(Table<?> alias) {
            return new TrackStructureVersionsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.CONSTRAINT_95;
    }

    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_956);
    }

    private transient TracksPath _tracks;

    /**
     * Get the implicit join path to the <code>PUBLIC.TRACKS</code> table.
     */
    public TracksPath tracks() {
        if (_tracks == null)
            _tracks = new TracksPath(this, Keys.CONSTRAINT_956, null);

        return _tracks;
    }

    @Override
    public TrackStructureVersions as(String alias) {
        return new TrackStructureVersions(DSL.name(alias), this);
    }

    @Override
    public TrackStructureVersions as(Name alias) {
        return new TrackStructureVersions(alias, this);
    }

    @Override
    public TrackStructureVersions as(Table<?> alias) {
        return new TrackStructureVersions(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TrackStructureVersions rename(String name) {
        return new TrackStructureVersions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TrackStructureVersions rename(Name name) {
        return new TrackStructureVersions(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TrackStructureVersions rename(Table<?> name) {
        return new TrackStructureVersions(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TrackStructureVersions where(Condition condition) {
        return new TrackStructureVersions(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TrackStructureVersions where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TrackStructureVersions where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TrackStructureVersions where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TrackStructureVersions where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TrackStructureVersions where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TrackStructureVersions where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TrackStructureVersions where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TrackStructureVersions whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TrackStructureVersions whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
