/*
 * This file is generated by jOOQ.
 */
package se.dansbart.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import se.dansbart.jooq.DefaultSchema;
import se.dansbart.jooq.Keys;
import se.dansbart.jooq.tables.Artists.ArtistsPath;
import se.dansbart.jooq.tables.Tracks.TracksPath;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TrackArtists extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>TRACK_ARTISTS</code>
     */
    public static final TrackArtists TRACK_ARTISTS = new TrackArtists();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>TRACK_ARTISTS.ID</code>.
     */
    public final TableField<Record, UUID> ID = createField(DSL.name("ID"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("RANDOM_UUID()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>TRACK_ARTISTS.TRACK_ID</code>.
     */
    public final TableField<Record, UUID> TRACK_ID = createField(DSL.name("TRACK_ID"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>TRACK_ARTISTS.ARTIST_ID</code>.
     */
    public final TableField<Record, UUID> ARTIST_ID = createField(DSL.name("ARTIST_ID"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>TRACK_ARTISTS.ROLE</code>.
     */
    public final TableField<Record, String> ROLE = createField(DSL.name("ROLE"), SQLDataType.VARCHAR(1000000000).defaultValue(DSL.field(DSL.raw("'primary'"), SQLDataType.VARCHAR)), this, "");

    private TrackArtists(Name alias, Table<Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TrackArtists(Name alias, Table<Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>TRACK_ARTISTS</code> table reference
     */
    public TrackArtists(String alias) {
        this(DSL.name(alias), TRACK_ARTISTS);
    }

    /**
     * Create an aliased <code>TRACK_ARTISTS</code> table reference
     */
    public TrackArtists(Name alias) {
        this(alias, TRACK_ARTISTS);
    }

    /**
     * Create a <code>TRACK_ARTISTS</code> table reference
     */
    public TrackArtists() {
        this(DSL.name("TRACK_ARTISTS"), null);
    }

    public <O extends Record> TrackArtists(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
        super(path, childPath, parentPath, TRACK_ARTISTS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TrackArtistsPath extends TrackArtists implements Path<Record> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TrackArtistsPath(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
            super(path, childPath, parentPath);
        }
        private TrackArtistsPath(Name alias, Table<Record> aliased) {
            super(alias, aliased);
        }

        @Override
        public TrackArtistsPath as(String alias) {
            return new TrackArtistsPath(DSL.name(alias), this);
        }

        @Override
        public TrackArtistsPath as(Name alias) {
            return new TrackArtistsPath(alias, this);
        }

        @Override
        public TrackArtistsPath as(Table<?> alias) {
            return new TrackArtistsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.CONSTRAINT_72;
    }

    @Override
    public List<UniqueKey<Record>> getUniqueKeys() {
        return Arrays.asList(Keys.UNIQUE_TRACK_ARTIST);
    }

    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_72E, Keys.CONSTRAINT_72EF);
    }

    private transient TracksPath _tracks;

    /**
     * Get the implicit join path to the <code>PUBLIC.TRACKS</code> table.
     */
    public TracksPath tracks() {
        if (_tracks == null)
            _tracks = new TracksPath(this, Keys.CONSTRAINT_72E, null);

        return _tracks;
    }

    private transient ArtistsPath _artists;

    /**
     * Get the implicit join path to the <code>PUBLIC.ARTISTS</code> table.
     */
    public ArtistsPath artists() {
        if (_artists == null)
            _artists = new ArtistsPath(this, Keys.CONSTRAINT_72EF, null);

        return _artists;
    }

    @Override
    public TrackArtists as(String alias) {
        return new TrackArtists(DSL.name(alias), this);
    }

    @Override
    public TrackArtists as(Name alias) {
        return new TrackArtists(alias, this);
    }

    @Override
    public TrackArtists as(Table<?> alias) {
        return new TrackArtists(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TrackArtists rename(String name) {
        return new TrackArtists(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TrackArtists rename(Name name) {
        return new TrackArtists(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TrackArtists rename(Table<?> name) {
        return new TrackArtists(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TrackArtists where(Condition condition) {
        return new TrackArtists(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TrackArtists where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TrackArtists where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TrackArtists where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TrackArtists where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TrackArtists where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TrackArtists where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TrackArtists where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TrackArtists whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TrackArtists whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
