/*
 * This file is generated by jOOQ.
 */
package se.dansbart.jooq.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import se.dansbart.jooq.DefaultSchema;
import se.dansbart.jooq.Keys;
import se.dansbart.jooq.tables.Tracks.TracksPath;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TrackStyleVotes extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>TRACK_STYLE_VOTES</code>
     */
    public static final TrackStyleVotes TRACK_STYLE_VOTES = new TrackStyleVotes();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>TRACK_STYLE_VOTES.ID</code>.
     */
    public final TableField<Record, UUID> ID = createField(DSL.name("ID"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("RANDOM_UUID()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>TRACK_STYLE_VOTES.TRACK_ID</code>.
     */
    public final TableField<Record, UUID> TRACK_ID = createField(DSL.name("TRACK_ID"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>TRACK_STYLE_VOTES.VOTER_ID</code>.
     */
    public final TableField<Record, String> VOTER_ID = createField(DSL.name("VOTER_ID"), SQLDataType.VARCHAR(1000000000), this, "");

    /**
     * The column <code>TRACK_STYLE_VOTES.SUGGESTED_STYLE</code>.
     */
    public final TableField<Record, String> SUGGESTED_STYLE = createField(DSL.name("SUGGESTED_STYLE"), SQLDataType.VARCHAR(1000000000), this, "");

    /**
     * The column <code>TRACK_STYLE_VOTES.TEMPO_CORRECTION</code>.
     */
    public final TableField<Record, String> TEMPO_CORRECTION = createField(DSL.name("TEMPO_CORRECTION"), SQLDataType.VARCHAR(1000000000), this, "");

    /**
     * The column <code>TRACK_STYLE_VOTES.CREATED_AT</code>.
     */
    public final TableField<Record, OffsetDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private TrackStyleVotes(Name alias, Table<Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TrackStyleVotes(Name alias, Table<Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>TRACK_STYLE_VOTES</code> table reference
     */
    public TrackStyleVotes(String alias) {
        this(DSL.name(alias), TRACK_STYLE_VOTES);
    }

    /**
     * Create an aliased <code>TRACK_STYLE_VOTES</code> table reference
     */
    public TrackStyleVotes(Name alias) {
        this(alias, TRACK_STYLE_VOTES);
    }

    /**
     * Create a <code>TRACK_STYLE_VOTES</code> table reference
     */
    public TrackStyleVotes() {
        this(DSL.name("TRACK_STYLE_VOTES"), null);
    }

    public <O extends Record> TrackStyleVotes(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
        super(path, childPath, parentPath, TRACK_STYLE_VOTES);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TrackStyleVotesPath extends TrackStyleVotes implements Path<Record> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TrackStyleVotesPath(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
            super(path, childPath, parentPath);
        }
        private TrackStyleVotesPath(Name alias, Table<Record> aliased) {
            super(alias, aliased);
        }

        @Override
        public TrackStyleVotesPath as(String alias) {
            return new TrackStyleVotesPath(DSL.name(alias), this);
        }

        @Override
        public TrackStyleVotesPath as(Name alias) {
            return new TrackStyleVotesPath(alias, this);
        }

        @Override
        public TrackStyleVotesPath as(Table<?> alias) {
            return new TrackStyleVotesPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.CONSTRAINT_1B;
    }

    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_1B7);
    }

    private transient TracksPath _tracks;

    /**
     * Get the implicit join path to the <code>PUBLIC.TRACKS</code> table.
     */
    public TracksPath tracks() {
        if (_tracks == null)
            _tracks = new TracksPath(this, Keys.CONSTRAINT_1B7, null);

        return _tracks;
    }

    @Override
    public TrackStyleVotes as(String alias) {
        return new TrackStyleVotes(DSL.name(alias), this);
    }

    @Override
    public TrackStyleVotes as(Name alias) {
        return new TrackStyleVotes(alias, this);
    }

    @Override
    public TrackStyleVotes as(Table<?> alias) {
        return new TrackStyleVotes(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TrackStyleVotes rename(String name) {
        return new TrackStyleVotes(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TrackStyleVotes rename(Name name) {
        return new TrackStyleVotes(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TrackStyleVotes rename(Table<?> name) {
        return new TrackStyleVotes(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TrackStyleVotes where(Condition condition) {
        return new TrackStyleVotes(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TrackStyleVotes where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TrackStyleVotes where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TrackStyleVotes where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TrackStyleVotes where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TrackStyleVotes where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TrackStyleVotes where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TrackStyleVotes where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TrackStyleVotes whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TrackStyleVotes whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
