/*
 * This file is generated by jOOQ.
 */
package se.dansbart.jooq.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import se.dansbart.jooq.DefaultSchema;
import se.dansbart.jooq.Keys;
import se.dansbart.jooq.tables.Tracks.TracksPath;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TrackPlaybacks extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>TRACK_PLAYBACKS</code>
     */
    public static final TrackPlaybacks TRACK_PLAYBACKS = new TrackPlaybacks();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>TRACK_PLAYBACKS.ID</code>.
     */
    public final TableField<Record, UUID> ID = createField(DSL.name("ID"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("RANDOM_UUID()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>TRACK_PLAYBACKS.TRACK_ID</code>.
     */
    public final TableField<Record, UUID> TRACK_ID = createField(DSL.name("TRACK_ID"), SQLDataType.UUID, this, "");

    /**
     * The column <code>TRACK_PLAYBACKS.PLATFORM</code>.
     */
    public final TableField<Record, String> PLATFORM = createField(DSL.name("PLATFORM"), SQLDataType.VARCHAR(1000000000), this, "");

    /**
     * The column <code>TRACK_PLAYBACKS.PLAYED_AT</code>.
     */
    public final TableField<Record, OffsetDateTime> PLAYED_AT = createField(DSL.name("PLAYED_AT"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>TRACK_PLAYBACKS.DURATION_SECONDS</code>.
     */
    public final TableField<Record, Integer> DURATION_SECONDS = createField(DSL.name("DURATION_SECONDS"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>TRACK_PLAYBACKS.COMPLETED</code>.
     */
    public final TableField<Record, Boolean> COMPLETED = createField(DSL.name("COMPLETED"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("FALSE"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>TRACK_PLAYBACKS.SESSION_ID</code>.
     */
    public final TableField<Record, String> SESSION_ID = createField(DSL.name("SESSION_ID"), SQLDataType.VARCHAR(1000000000), this, "");

    private TrackPlaybacks(Name alias, Table<Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TrackPlaybacks(Name alias, Table<Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>TRACK_PLAYBACKS</code> table reference
     */
    public TrackPlaybacks(String alias) {
        this(DSL.name(alias), TRACK_PLAYBACKS);
    }

    /**
     * Create an aliased <code>TRACK_PLAYBACKS</code> table reference
     */
    public TrackPlaybacks(Name alias) {
        this(alias, TRACK_PLAYBACKS);
    }

    /**
     * Create a <code>TRACK_PLAYBACKS</code> table reference
     */
    public TrackPlaybacks() {
        this(DSL.name("TRACK_PLAYBACKS"), null);
    }

    public <O extends Record> TrackPlaybacks(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
        super(path, childPath, parentPath, TRACK_PLAYBACKS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TrackPlaybacksPath extends TrackPlaybacks implements Path<Record> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TrackPlaybacksPath(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
            super(path, childPath, parentPath);
        }
        private TrackPlaybacksPath(Name alias, Table<Record> aliased) {
            super(alias, aliased);
        }

        @Override
        public TrackPlaybacksPath as(String alias) {
            return new TrackPlaybacksPath(DSL.name(alias), this);
        }

        @Override
        public TrackPlaybacksPath as(Name alias) {
            return new TrackPlaybacksPath(alias, this);
        }

        @Override
        public TrackPlaybacksPath as(Table<?> alias) {
            return new TrackPlaybacksPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.CONSTRAINT_E;
    }

    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_E4);
    }

    private transient TracksPath _tracks;

    /**
     * Get the implicit join path to the <code>PUBLIC.TRACKS</code> table.
     */
    public TracksPath tracks() {
        if (_tracks == null)
            _tracks = new TracksPath(this, Keys.CONSTRAINT_E4, null);

        return _tracks;
    }

    @Override
    public TrackPlaybacks as(String alias) {
        return new TrackPlaybacks(DSL.name(alias), this);
    }

    @Override
    public TrackPlaybacks as(Name alias) {
        return new TrackPlaybacks(alias, this);
    }

    @Override
    public TrackPlaybacks as(Table<?> alias) {
        return new TrackPlaybacks(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TrackPlaybacks rename(String name) {
        return new TrackPlaybacks(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TrackPlaybacks rename(Name name) {
        return new TrackPlaybacks(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TrackPlaybacks rename(Table<?> name) {
        return new TrackPlaybacks(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TrackPlaybacks where(Condition condition) {
        return new TrackPlaybacks(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TrackPlaybacks where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TrackPlaybacks where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TrackPlaybacks where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TrackPlaybacks where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TrackPlaybacks where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TrackPlaybacks where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TrackPlaybacks where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TrackPlaybacks whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TrackPlaybacks whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
