/*
 * This file is generated by jOOQ.
 */
package se.dansbart.jooq.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import se.dansbart.jooq.DefaultSchema;
import se.dansbart.jooq.Keys;
import se.dansbart.jooq.tables.Tracks.TracksPath;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TrackFeelVotes extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>TRACK_FEEL_VOTES</code>
     */
    public static final TrackFeelVotes TRACK_FEEL_VOTES = new TrackFeelVotes();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>TRACK_FEEL_VOTES.ID</code>.
     */
    public final TableField<Record, UUID> ID = createField(DSL.name("ID"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("RANDOM_UUID()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>TRACK_FEEL_VOTES.TRACK_ID</code>.
     */
    public final TableField<Record, UUID> TRACK_ID = createField(DSL.name("TRACK_ID"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>TRACK_FEEL_VOTES.FEEL_TAG</code>.
     */
    public final TableField<Record, String> FEEL_TAG = createField(DSL.name("FEEL_TAG"), SQLDataType.VARCHAR(1000000000).nullable(false), this, "");

    /**
     * The column <code>TRACK_FEEL_VOTES.CREATED_AT</code>.
     */
    public final TableField<Record, OffsetDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private TrackFeelVotes(Name alias, Table<Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TrackFeelVotes(Name alias, Table<Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>TRACK_FEEL_VOTES</code> table reference
     */
    public TrackFeelVotes(String alias) {
        this(DSL.name(alias), TRACK_FEEL_VOTES);
    }

    /**
     * Create an aliased <code>TRACK_FEEL_VOTES</code> table reference
     */
    public TrackFeelVotes(Name alias) {
        this(alias, TRACK_FEEL_VOTES);
    }

    /**
     * Create a <code>TRACK_FEEL_VOTES</code> table reference
     */
    public TrackFeelVotes() {
        this(DSL.name("TRACK_FEEL_VOTES"), null);
    }

    public <O extends Record> TrackFeelVotes(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
        super(path, childPath, parentPath, TRACK_FEEL_VOTES);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TrackFeelVotesPath extends TrackFeelVotes implements Path<Record> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TrackFeelVotesPath(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
            super(path, childPath, parentPath);
        }
        private TrackFeelVotesPath(Name alias, Table<Record> aliased) {
            super(alias, aliased);
        }

        @Override
        public TrackFeelVotesPath as(String alias) {
            return new TrackFeelVotesPath(DSL.name(alias), this);
        }

        @Override
        public TrackFeelVotesPath as(Name alias) {
            return new TrackFeelVotesPath(alias, this);
        }

        @Override
        public TrackFeelVotesPath as(Table<?> alias) {
            return new TrackFeelVotesPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.CONSTRAINT_3;
    }

    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_31);
    }

    private transient TracksPath _tracks;

    /**
     * Get the implicit join path to the <code>PUBLIC.TRACKS</code> table.
     */
    public TracksPath tracks() {
        if (_tracks == null)
            _tracks = new TracksPath(this, Keys.CONSTRAINT_31, null);

        return _tracks;
    }

    @Override
    public TrackFeelVotes as(String alias) {
        return new TrackFeelVotes(DSL.name(alias), this);
    }

    @Override
    public TrackFeelVotes as(Name alias) {
        return new TrackFeelVotes(alias, this);
    }

    @Override
    public TrackFeelVotes as(Table<?> alias) {
        return new TrackFeelVotes(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TrackFeelVotes rename(String name) {
        return new TrackFeelVotes(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TrackFeelVotes rename(Name name) {
        return new TrackFeelVotes(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TrackFeelVotes rename(Table<?> name) {
        return new TrackFeelVotes(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TrackFeelVotes where(Condition condition) {
        return new TrackFeelVotes(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TrackFeelVotes where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TrackFeelVotes where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TrackFeelVotes where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TrackFeelVotes where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TrackFeelVotes where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TrackFeelVotes where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TrackFeelVotes where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TrackFeelVotes whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TrackFeelVotes whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
