/*
 * This file is generated by jOOQ.
 */
package se.dansbart.jooq.tables;


import java.time.OffsetDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import se.dansbart.jooq.DefaultSchema;
import se.dansbart.jooq.Keys;
import se.dansbart.jooq.tables.PlaylistCollaborators.PlaylistCollaboratorsPath;
import se.dansbart.jooq.tables.Playlists.PlaylistsPath;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Users extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>USERS</code>
     */
    public static final Users USERS = new Users();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>USERS.ID</code>.
     */
    public final TableField<Record, String> ID = createField(DSL.name("ID"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>USERS.USERNAME</code>.
     */
    public final TableField<Record, String> USERNAME = createField(DSL.name("USERNAME"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>USERS.DISPLAY_NAME</code>.
     */
    public final TableField<Record, String> DISPLAY_NAME = createField(DSL.name("DISPLAY_NAME"), SQLDataType.VARCHAR(1000000000), this, "");

    /**
     * The column <code>USERS.AVATAR_URL</code>.
     */
    public final TableField<Record, String> AVATAR_URL = createField(DSL.name("AVATAR_URL"), SQLDataType.VARCHAR(1000000000), this, "");

    /**
     * The column <code>USERS.CREATED_AT</code>.
     */
    public final TableField<Record, OffsetDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>USERS.LAST_LOGIN_AT</code>.
     */
    public final TableField<Record, OffsetDateTime> LAST_LOGIN_AT = createField(DSL.name("LAST_LOGIN_AT"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    private Users(Name alias, Table<Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Users(Name alias, Table<Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>USERS</code> table reference
     */
    public Users(String alias) {
        this(DSL.name(alias), USERS);
    }

    /**
     * Create an aliased <code>USERS</code> table reference
     */
    public Users(Name alias) {
        this(alias, USERS);
    }

    /**
     * Create a <code>USERS</code> table reference
     */
    public Users() {
        this(DSL.name("USERS"), null);
    }

    public <O extends Record> Users(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
        super(path, childPath, parentPath, USERS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class UsersPath extends Users implements Path<Record> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> UsersPath(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
            super(path, childPath, parentPath);
        }
        private UsersPath(Name alias, Table<Record> aliased) {
            super(alias, aliased);
        }

        @Override
        public UsersPath as(String alias) {
            return new UsersPath(DSL.name(alias), this);
        }

        @Override
        public UsersPath as(Name alias) {
            return new UsersPath(alias, this);
        }

        @Override
        public UsersPath as(Table<?> alias) {
            return new UsersPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.CONSTRAINT_4;
    }

    private transient PlaylistsPath _playlists;

    /**
     * Get the implicit to-many join path to the <code>PUBLIC.PLAYLISTS</code>
     * table
     */
    public PlaylistsPath playlists() {
        if (_playlists == null)
            _playlists = new PlaylistsPath(this, null, Keys.CONSTRAINT_36E.getInverseKey());

        return _playlists;
    }

    private transient PlaylistCollaboratorsPath _constraintB8cf;

    /**
     * Get the implicit to-many join path to the
     * <code>PUBLIC.PLAYLIST_COLLABORATORS</code> table, via the
     * <code>CONSTRAINT_B8CF</code> key
     */
    public PlaylistCollaboratorsPath constraintB8cf() {
        if (_constraintB8cf == null)
            _constraintB8cf = new PlaylistCollaboratorsPath(this, null, Keys.CONSTRAINT_B8CF.getInverseKey());

        return _constraintB8cf;
    }

    private transient PlaylistCollaboratorsPath _constraintB8cfd;

    /**
     * Get the implicit to-many join path to the
     * <code>PUBLIC.PLAYLIST_COLLABORATORS</code> table, via the
     * <code>CONSTRAINT_B8CFD</code> key
     */
    public PlaylistCollaboratorsPath constraintB8cfd() {
        if (_constraintB8cfd == null)
            _constraintB8cfd = new PlaylistCollaboratorsPath(this, null, Keys.CONSTRAINT_B8CFD.getInverseKey());

        return _constraintB8cfd;
    }

    @Override
    public Users as(String alias) {
        return new Users(DSL.name(alias), this);
    }

    @Override
    public Users as(Name alias) {
        return new Users(alias, this);
    }

    @Override
    public Users as(Table<?> alias) {
        return new Users(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Users rename(String name) {
        return new Users(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Users rename(Name name) {
        return new Users(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Users rename(Table<?> name) {
        return new Users(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Users where(Condition condition) {
        return new Users(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Users where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Users where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Users where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Users where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Users where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Users where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Users where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Users whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Users whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
