/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type GetKeywords1Params = {
  search?: string;
  mainStyle?: string;
  isActive?: boolean;
  limit?: number;
  offset?: number;
};
