/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type GetTracks1Params = {
  search?: string;
  status?: string;
  flagged?: boolean;
  limit?: number;
  offset?: number;
};
