/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Artist } from './artist';
import type { SortObject } from './sortObject';
import type { PageableObject } from './pageableObject';

export interface PageArtist {
  totalPages?: number;
  totalElements?: number;
  size?: number;
  content?: Artist[];
  number?: number;
  sort?: SortObject;
  pageable?: PageableObject;
  numberOfElements?: number;
  first?: boolean;
  last?: boolean;
  empty?: boolean;
}
