/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Playlist } from './playlist';
import type { User } from './user';

export interface PlaylistCollaborator {
  id?: string;
  playlistId?: string;
  userId?: string;
  permission?: string;
  status?: string;
  invitedBy?: string;
  invitedAt?: string;
  acceptedAt?: string;
  playlist?: Playlist;
  user?: User;
}
