/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface RejectRequest {
  reason?: string;
  dryRun?: boolean;
  deleteContent?: boolean;
}
