/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface StatsDto {
  totalTracks?: number;
  analyzed?: number;
  classified?: number;
  pendingAnalysis?: number;
  pendingClassification?: number;
  coveragePercent?: number;
  lastAdded?: string;
}
