/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Track } from './track';
import type { TrackStructureVersionStructureData } from './trackStructureVersionStructureData';

export interface TrackStructureVersion {
  id?: string;
  trackId?: string;
  track?: Track;
  createdAt?: string;
  description?: string;
  structureData?: TrackStructureVersionStructureData;
  voteCount?: number;
  reportCount?: number;
  isActive?: boolean;
  isHidden?: boolean;
  authorAlias?: string;
}
