/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Track } from './track';
import type { Album } from './album';

export interface TrackAlbum {
  id?: string;
  trackId?: string;
  albumId?: string;
  track?: Track;
  album?: Album;
}
