/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface TrackListDto {
  id?: string;
  title?: string;
  durationMs?: number;
  danceStyle?: string;
  subStyle?: string;
  effectiveBpm?: number;
  confidence?: number;
  hasVocals?: boolean;
  artistName?: string;
  albumCoverUrl?: string;
  playbackPlatform?: string;
  playbackLink?: string;
}
