/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Track } from './track';

export interface TrackFeelVote {
  id?: string;
  trackId?: string;
  track?: Track;
  feelTag?: string;
  createdAt?: string;
}
