/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Track } from './track';
import type { UserInteractionEventData } from './userInteractionEventData';

export interface UserInteraction {
  id?: string;
  trackId?: string;
  track?: Track;
  eventType?: string;
  eventData?: UserInteractionEventData;
  createdAt?: string;
  sessionId?: string;
}
